### ISSUE TITLE
请问怎么加到库里来？

### ISSUE THREAD

**Issue by paizxin** [dkzwm/SmoothRefreshLayout#1]
如何导入依赖

**Comment by dkzwm** [comment]
这两天比较忙。补充完Readme，再严格测试过后会发布第一个版本。到时候就可以远程依赖了。谢谢

**Comment by dkzwm** [comment]
Readme补充了，第一个基础版本已经发布，你可以依赖试下效果，有BUG可以反馈可我。谢谢
