### ISSUE TITLE
状态恢复问题

### ISSUE THREAD

**Issue by LambdaV5** [dkzwm/SmoothRefreshLayout#10]
在activity或者fragment onPause方法被调用后,onresume后第一个item会往上移动一段距离(item高度超过可见区域)

**Comment by dkzwm** [comment]
@LambdaV5 请问是RecyclerView的第一个Item网上移动了点距离还是整个RecyclerView往上移动了一段距离？如果是RecyclerView内部移动了是否RecyclerView设置了Margin或者是否是使用加载更多出现的问题？请描述下具体问题出现的场景，我这边没有遇到过这种问题，根据你的描述无法复现问题，解决起来比较盲目

**Comment by LambdaV5** [comment]
下拉刷新前
![default](https://user-images.githubusercontent.com/17512402/28600974-12b6bf52-71e8-11e7-8b95-74419c2e90d1.png)
下拉刷新后
![default](https://user-images.githubusercontent.com/17512402/28600995-2e7adc00-71e8-11e7-9006-6a7326010a53.png)
recyclerview没有margin,模式为下拉刷新,没有上拉加载

**Comment by dkzwm** [comment]
@LambdaV5 是整体上移了吗？感觉RecyclerView设置了Margin?

**Comment by LambdaV5** [comment]
,应该是整体上移,没有margin

**Comment by dkzwm** [comment]
能麻烦你发下布局吗？或者发下Demo代码到dkzwm@hotmail.com 我好分析下是哪里的问题

**Comment by LambdaV5** [comment]
我突然觉得这个可能不是你的问题,因为我把刷新控件去掉或者换成系统的swiperefreshlayout也会出现这个问题

**Comment by dkzwm** [comment]
额 那你再测试下吧 如果有问题麻烦你反馈给我

**Comment by LambdaV5** [comment]
好的,没问题

**Comment by LambdaV5** [comment]
最新版本(1.3.4)会出现下拉刷新失效或不灵敏的情况

**Comment by dkzwm** [comment]
具体布局是怎样的呢 没布局或者代码 根据几句描述我无法查找是否是库的问题

**Comment by dkzwm** [comment]
@LambdaV5  我看到你在另一个库的Issue描述了是Recyclerview的Item内嵌了Recyclerview，这种用法请将内嵌的Recyclerview的onInterceptTouchEvent返回false，由于你内嵌的Recyclerview是高度撑满Item不需要滑动的，会导致NestedScroll特性的生命周期出现混乱。直接不让内嵌的Recyclerview消耗触摸事件就没问题了。之前有个提issue的我给他解决过这个问题

**Comment by LambdaV5** [comment]
好的,谢谢,我试试.
你们是一伙的?

**Comment by dkzwm** [comment]
@LambdaV5 你主页有你的动态，能看到你提的issue,同样的问题你在BaseRecyclerViewAdapterHelper的库里提了，我看了下描述而已

**Comment by LambdaV5** [comment]
噢噢

**Comment by LambdaV5** [comment]
最新版,刷新正常,谢谢

**Comment by dkzwm** [comment]
@LambdaV5 好的 没问题的话 麻烦关闭下issue 谢谢
