### ISSUE TITLE
吐槽

### ISSUE THREAD

**Issue by wenjianxue** [dkzwm/SmoothRefreshLayout#100]
时隔一年来仓库更新新版本以为走错了，仓库名从com.github.dkzwm.SmoothRefreshLayout 改为了me.dkzwm.widget.srl。看 Update 是仓主误操作导致。。。。能不能在 readme上说明一下。

从1.6.4.3 升级到1.6.5 有部分接口修改了 包括 IRefreshViewCreator以及SmoothRefreshLayout.OnRefreshListener，特别是 SmoothRefreshLayout.OnRefreshListener 的修改与之前的方式不一样，要修改业务代码才能适应更新了。
更新最新版1.6.6.8后发现嵌套CoordinatorLayout、AppBarLayout、ViewPager 滚动变得不太顺畅，1.6.4.3 没有样的问题。1.6.4.3使用了 setLifecycleObserver(QuickConfigAppBarUtil())，1.6.6.8改成了 addLifecycleObserver(....)。

另外，Android 10 非SDK标准接口的测试中发现使用了 SRReflectUtil 反射机制产生了几个 greylist-max-p，可以理解吧毕竟Android 给的接口不能满足需求，只能反射获取了。看名称 compatOlderAbsListViewXXXX 是为了获取OlderAbsListView 的数据，是为了适配某些Listview?没有通读源码，如果仓主方便就解答一下，没空过两天我就关闭issues 了。最后感谢仓主 还在维护这个仓库。
下面列出具体的 greylist-max-p 内容

#44: Reflection greylist-max-p Landroid/widget/AbsListView;->mFlingRunnable use(s):
       Lme/dkzwm/widget/srl/utils/SRReflectUtil;->compatOlderAbsListViewFling(Landroid/widget/AbsListView;I)V

#46: Reflection greylist-max-p Landroid/widget/AbsListView;->reportScrollStateChange use(s):
       Lme/dkzwm/widget/srl/utils/SRReflectUtil;->compatOlderAbsListViewFling(Landroid/widget/AbsListView;I)V
       Lme/dkzwm/widget/srl/utils/SRReflectUtil;->compatOlderAbsListViewFling(Landroid/widget/AbsListView;I)V

#47: Reflection greylist-max-p Landroid/widget/AbsListView;->trackMotionScroll use(s):
       Lme/dkzwm/widget/srl/utils/SRReflectUtil;->compatOlderAbsListViewScrollListBy(Landroid/widget/AbsListView;I)V

**Comment by dkzwm** [comment]
@wenjianxue  你好，感谢你还在使用本库
1.仓库迁移前的更新日志已经在很久以前从版本更新日志中移除了，之前是有说明的，考虑到使用本库的人不是很多，且更新日志页太长就删除了，造成的困扰导致抱歉。
2.接口变动问题，这边主要考虑到最大限度的避免使用者的介入，对很多能力都直接在内部进行了实现，这边考虑到我多数都是业余时间进行的更新测试，加之一个人能力毕竟有限，考虑可能不周，会有一个逐步完善的过程，现阶段的`1.6.6.8`版本应该是`android support`下最后一个支持版本了，这个版本的嵌套滚动我在测试demo中没有发现有不流畅问题，不知道是哪里配置出了问题还是说本库有BUG，如果可以请告知下配置和布局。
3.反射的问题，这边在后续的`1.6.7.androidx`版本开始，将兼容低版本`ListView`的`fling`反射逻辑移除`core`到`util`包，交由用户选择适配低版本。

**Comment by wenjianxue** [comment]
感谢，第二点布局大致如下http://note.youdao.com/noteshare?id=2ee9e630a1507f7cd759b5c2c371b36c&sub=0B17D1D2D9E142B49F95A6D0B33222D4
现在还没有空解决这个问题，如果有进展再进行备注。
