### ISSUE TITLE
升级 到最新版 1.7，上拉加载更多的时候，上拉松手的位置不同，footer 经常不能自动回弹

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#102]
另外我之前提交的96号issues 中的问题，现在下拉自动刷新的时候，header 出不来了，

package me.dkzwm.widget.srl;

import android.content.Context;
import android.util.AttributeSet;
import android.util.Log;

import me.dkzwm.widget.srl.MaterialSmoothRefreshLayout;

public class SyncScrollingRefreshLayout extends MaterialSmoothRefreshLayout {
    private static final String TAG = "SyncScrollingRefreshLay";

    public SyncScrollingRefreshLayout(Context context) {
        super(context);
    }

    public SyncScrollingRefreshLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public SyncScrollingRefreshLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    protected void moveHeaderPos(float delta) {
        super.moveHeaderPos(delta);
        Log.i(TAG, "moveHeaderPos: delta: " + delta);
        if (delta < 0) {
            tryToCompatSyncScroll(getScrollTargetView(), delta);

        }
    }

    protected void notifyUIRefreshComplete(boolean useScroll, boolean notifyViews) {
        super.notifyUIRefreshComplete(false, notifyViews);
        if (useScroll) {
            if (mScrollChecker.isFlingBack()) {
                mScrollChecker.stop();
            }
            tryScrollBackToTopByPercentDuration();
        }
    }
}

**Comment by dkzwm** [comment]
@dahai2070 
第一个问题，这边测试了嵌套滚动和普通滚动视图下的加载更多都能结束刷新后正常回弹，你不妨贴下布局已经配置，最好有debug模式下的日志，这样比较好追踪问题。
 第二个问题`1.7.0.androidx`版本不需要`SyncScrollingRefreshLayout `已经这样实现了，当时只是用来做临时处理，相关代码已合入到最新的`1.7.0.androidx`版本了，去掉相关重载方法再看一下。

**Comment by dahai2070** [comment]
我现在切换回之前版本了，那我再设置为最新的版本试试

第二个问题：现在直接使用 MaterialSmoothRefreshLayout ,配置 refreshLayout.setEnableAutoRefresh(true);

就能实现效果了哈，我试试

**Comment by dkzwm** [comment]
@dahai2070 还需要配置下`setEnableCompatSyncScroll(true)`

**Comment by dahai2070** [comment]
测试了，header 还是显示不了。我还是换回老版本。

**Comment by dkzwm** [comment]
@dahai2070  这边不是很清楚问题出在哪里，新版本是没有对布局相关做修改的，Demo中的示例也没有发生这种情况。

**Comment by dahai2070** [comment]
demo 中没有使用 EnableAutoRefresh的例子，有一个例子是  点在击事件里面,调用autoResh()而已。

**Comment by dkzwm** [comment]
@dahai2070 有的，测试RecyclerView那个

**Comment by dahai2070** [comment]
看到了demo，果然有，并且header 显示顺畅。我先对比下用法。

**Comment by dahai2070** [comment]
我发现 demo 中，力道比较小的时候，刚才是刚触发了自动刷新，但是刷新的header 出不来。刷新的回调是触发了的。这个有点鸡蛋挑骨头了。哈哈哈，

**Comment by dahai2070** [comment]
我发现 demo  WithRecyclerViewActivity 页面，力道比较小的时候，感觉是刚好触发了自动刷新，但是的header 出不来。刷新的回调是触发了的。这个有点鸡蛋挑骨头了。哈哈哈，
