### ISSUE TITLE
AppBarUtil的findRootViewGroup有bug

### ISSUE THREAD

**Issue by dnwalter** [dkzwm/SmoothRefreshLayout#104]
大神，你这个findRootViewGroup有bug。
一个ViewPager里面有几个fragment，我当前用你这个控件的fragment是没有CoordinatorLayout这个布局的，但其他fragment有，结果你这个findRootViewGroup就会找到那个CoordinatorLayout，然后就以为我当前的fragment里面有AppBarLayout，就搞到当前的fragment不能下拉刷新了

**Comment by dkzwm** [comment]
@dnwalter 不好意思，当时没考虑到`ViewPager`的情况，这边`1.7.0.androidx`是修复了这个问题的，`Android Support`库对应的版本已经停止更新了，这边你如果仍要使用`Android Support`库对应的版本。请尝试设置`setOnHeaderEdgeDetectCallBack`和`setOnFooterEdgeDetectCallBack`，手动配置边界判断逻辑

**Comment by dnwalter** [comment]
在努力的看源码中，看怎么重写setOnHeaderEdgeDetectCallBack

**Comment by dnwalter** [comment]
本来还不清楚这个setOnHeaderEdgeDetectCallBack是干什么的，但大神一说我就get到点了，已经解决了。总之是这个callback返回false就会触发下拉，自己看情况返回正确的值就行了
