### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by jyh149129** [dkzwm/SmoothRefreshLayout#105]
smartrefreshlayout和smoothrefreshlayouot两个库很像，但为什么smart用的人多...
除了内在，外表也很重要啊。建议多搞几个漂亮的刷新样式，对初学者应该能很好的吸引.

ps：感谢开源这么好的库！

**Comment by dkzwm** [comment]
@jyh149129  的确是很像，开源时间也比较相近，本库使用的人的确是少了点，哈哈哈。
相较于`SmartRefreshLayout `本库的功能着重点不一样，更看重触摸响应以及滚动的顺滑性。
刷新样式问题，当时考虑到主流也就是经典和material 2种风格，其它样式都是各有各的需求，也就就此罢了，后面时间更充裕的时候再考虑移植一些已有的刷新样式吧。
本库开源目的更多是分享，有人喜欢本库本人就很欣慰，也就没必要做到`SmartRefreshLayout`那么高的关注度了。

**Comment by jyh149129** [comment]
嗯，smooth更注重内功修炼吧。
对作者维护issues的态度赞一个，真的是有问必答。
