### ISSUE TITLE
对RecyclerView嵌套RecyclerView造成滑动冲突的问题

### ISSUE THREAD

**Issue by getglory** [dkzwm/SmoothRefreshLayout#107]
纵向RecyclerView的某个item是横向滚动的RecyclerView。
如果纵向RecyclerView滚动到底部，会导致横向的RecyclerView第一次触摸时无法滑动，需要第二次触摸后才能滑动，并且滑动有明显卡顿。
打印Log发现横向RecyclerView无法滚动时没有调用到dispatchTouchEvent方法。

**Comment by dkzwm** [comment]
😂 不好意思，这边我放假回老家了，身边没电脑，这边只有等上班后我写测试测下，你试着开启setDisableWhenAnotherDirectionMove，看能否解决问题

**Comment by getglory** [comment]
>  不好意思，这边我放假回老家了，身边没电脑，这边只有等上班后我写测试测下，你试着开启setDisableWhenAnotherDirectionMove，看能否解决问题

似乎没有作用。我打印Log发现，当纵向RecyclerView停止滚动后，还会有近3秒的时间重复打印onNestedPreScroll()和onNestedScroll()。当Log停止打印后，滑动横向的RecyclerView才不会被阻碍。

**Comment by getglory** [comment]
>  不好意思，这边我放假回老家了，身边没电脑，这边只有等上班后我写测试测下，你试着开启setDisableWhenAnotherDirectionMove，看能否解决问题

纵向的RecyclerView滚动到底部时才会有这个问题，滑动横向RecyclerView两次之后才能触发滚动，然后重新上下滑动纵向的RecyclerView，再次滚动到底部时，问题会复现。

**Comment by dkzwm** [comment]
@getglory 这边在最新代码上测试没有复现这个问题，你试着依赖`1.7.1-beta-1.androidx`这个版本，看是否有解决问题。如果你是使用的`Support`支持库对应的版本，该库对应的版本都已停止更新，问题也不会再修复了，请知悉。

**Comment by getglory** [comment]
> @getglory 这边在最新代码上测试没有复现这个问题，你试着依赖`1.7.1-beta-1.androidx`这个版本，看是否有解决问题。如果你是使用的`Support`支持库对应的版本，该库对应的版本都已停止更新，问题也不会再修复了，请知悉。

用的是AndroidX的版本。我在GitHub上随便下了个SmoothRefreshLayout的Demo，把依赖改成最新的也是有这个问题。方便留一下邮箱吗，我把Demo发过去，说明下具体情况。

**Comment by dkzwm** [comment]
@getglory aidkzwm@gmail.com

**Comment by getglory** [comment]
> @getglory [aidkzwm@gmail.com](mailto:aidkzwm@gmail.com)

已发送，请查收。

**Comment by getglory** [comment]
> @getglory [aidkzwm@gmail.com](mailto:aidkzwm@gmail.com)

被判断为垃圾邮件退回了，我放网盘吧。

**Comment by getglory** [comment]
> @getglory [aidkzwm@gmail.com](mailto:aidkzwm@gmail.com)

已发送邮件和链接，麻烦你了。

**Comment by dkzwm** [comment]
@getglory 这边下载下来，理论上属于`RecyclerView`的BUG，你的demo使用的不是实现`NestedScrollingChild3`接口的`RecyclerView`，而是实现了`NestedScrollingChild2`接口的版本，在`RecyclerView`最新版本修复了上层视图消耗完毕惯性滑动且`RecyclerView`已经到达边界时未停止内部的`ViewFlinger`的问题，你更新到最新版本即可解决这个问题。SRL这块也未考虑到关闭越界回弹理应不再处理惯性滑动的问题，这边会修改完善部分逻辑。

**Comment by dkzwm** [comment]
@getglory `RecyclerView`从`androidx.recyclerview:recyclerview:1.1.0-alpha01`版本开始支持`NestedScrollingChild3`特性，更新到该版本及以上版本都不会有你说的问题。

**Comment by getglory** [comment]
> @getglory `RecyclerView`从`androidx.recyclerview:recyclerview:1.1.0-alpha01`版本开始支持`NestedScrollingChild3`特性，更新到该版本及以上版本都不会有你说的问题。

非常感谢！我替换下RecyclerView的版本后没有问题就把issue关闭掉

**Comment by getglory** [comment]
> @getglory `RecyclerView`从`androidx.recyclerview:recyclerview:1.1.0-alpha01`版本开始支持`NestedScrollingChild3`特性，更新到该版本及以上版本都不会有你说的问题。

更新后已解决问题，非常感谢！

**Comment by getglory** [comment]
提醒下，需要用androidx.recyclerview:recyclerview:1.1.0-alpha01以上的版本，配合me.dkzwm.widget.srl:core:1.7.1-beta-1.androidx以上版本才能解决问题
