### ISSUE TITLE
support 1.6.6.8 最终版本 加载更多，上滑加载 footerView 有时不能完整显示出来

### ISSUE THREAD

**Issue by jiaowenzheng** [dkzwm/SmoothRefreshLayout#109]
implementation 'me.dkzwm.widget.srl:core:1.6.6.8' 上滑加载更多 footerView 有时不能完整显示出来。androidx 版本不存在此问题。

**Comment by dkzwm** [comment]
@jiaowenzheng 大兄弟，不好意思，这边Support对应版本已经不再更新了，考虑到同时维护2个开发线鸭梨有点大，且2条线属于不同的特性能力集，就没有再更新了，如果有十分影响使用的大BUG可能考虑抽时间修复下，毕竟谷歌已停止更新Support线，使用的也越来越少，业余时间有限情况下只能进行下取舍…

**Comment by jiaowenzheng** [comment]
好的，谢谢！

**Comment by jiaowenzheng** [comment]
> @jiaowenzheng 大兄弟，不好意思，这边Support对应版本已经不再更新了，考虑到同时维护2个开发线鸭梨有点大，且2条线属于不同的特性能力集，就没有再更新了，如果有十分影响使用的大BUG可能考虑抽时间修复下，毕竟谷歌已停止更新Support线，使用的也越来越少，业余时间有限情况下只能进行下取舍…

好的，谢谢！
