### ISSUE TITLE
布局被遮盖问题(1.3.4版)

### ISSUE THREAD

**Issue by LambdaV5** [dkzwm/SmoothRefreshLayout#11]
升级1.3.4版本后出现此问题,1.2.2版本无此问题
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1355#issuecomment-318319889

**Comment by dkzwm** [comment]
@LambdaV5  你切换到SwipeRefreshLayout会有问题吗？ 能否提供下具体的代码？

**Comment by LambdaV5** [comment]
<com.ciwei.bgw.user.widget.MySmoothRefreshLayout**
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/nor"
    app:sr_enable_pull_to_refresh="true"
    app:sr_mode="refresh">

    <com.classic.common.MultipleStatusView
        android:id="@+id/msv_child_order"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:emptyView="@layout/layout_order_empty_view"
        app:loadingView="@layout/layout_loading"
        app:noNetworkView="@layout/layout_no_network"
        tools:context="com.ciwei.bgw.user.ui.frag.order.OrderListFragment">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never"/>
    </com.classic.common.MultipleStatusView>
</com.ciwei.bgw.user.widget.MySmoothRefreshLayout>
**1.2.2版本无此问题**

**Comment by dkzwm** [comment]
@LambdaV5 MultipleStatusView这个内部有设置margin吗，1.2.2的最大区别是不支持margin特性，从1.2.3开始支援的

**Comment by dkzwm** [comment]
@LambdaV5  https://github.com/qyxxjd/MultipleStatusView 是这个项目吗? 是的话 我写Demo测试下

**Comment by LambdaV5** [comment]
是这个库,没有设置margin

**Comment by dkzwm** [comment]
@LambdaV5 
```       
        mRefreshLayout.setOnChildScrollUpCallback(new SmoothRefreshLayout.OnChildScrollUpCallback() {
            @Override
            public boolean canChildScrollUp(SmoothRefreshLayout parent, @Nullable View child, @Nullable IRefreshView header) {
                return ScrollCompat.canChildScrollUp(mRecyclerView);
            }
        });
        mRefreshLayout.setOnChildScrollDownCallback(new SmoothRefreshLayout.OnChildScrollDownCallback() {
            @Override
            public boolean canChildScrollDown(SmoothRefreshLayout parent, @Nullable View child, @Nullable IRefreshView footer) {
                return ScrollCompat.canChildScrollDown(mRecyclerView);
            }
        });
        mRefreshLayout.setLoadMoreScrollTargetView(mRecyclerView);
```

**Comment by LambdaV5** [comment]
只是refresh模式,也用这个吗`mRefreshLayout.setLoadMoreScrollTargetView(mRecyclerView);`

**Comment by dkzwm** [comment]
@LambdaV5  类似这种布局，真实判断处理的是内部嵌套的RecyclerView ，那么判断的视图是否在需要显示刷新视图需要指定下，setLoadMoreScrollTargetView这个是为了做加载更多平滑显示需要设置。我的Demo里有类似嵌套示例，你可以看下，Readme我也有描述

**Comment by dkzwm** [comment]
@LambdaV5 refresh模式不需要设置setLoadMoreScrollTargetView

**Comment by LambdaV5** [comment]
好的,我试试,谢谢

**Comment by dkzwm** [comment]
@LambdaV5 请问问题解决了吗 解决了的话麻烦关闭下issue或者告知下

**Comment by LambdaV5** [comment]
解决了,谢谢

**Comment by LambdaV5** [comment]
问题产生的原因是在loadmore回调成功里面调用了refreshComplete

**Comment by dkzwm** [comment]
@LambdaV5  和这个没关系 233333

**Comment by LambdaV5** [comment]
照你说的做了,如果在loadmore成功的时候调用refreshComplete,问题依然可以复现,只在下拉的时候调用refreshComplete不会出现此问题

**Comment by dkzwm** [comment]
@LambdaV5  设置了 `mRefreshLayout.setLoadMoreScrollTargetView(mRecyclerView);`？

**Comment by LambdaV5** [comment]
嵌套滚动 mRefreshLayout.setOnChildScrollUpCallback(new SmoothRefreshLayout.OnChildScrollUpCallback() {
            @Override
            public boolean canChildScrollUp(SmoothRefreshLayout parent, @Nullable View child, @Nullable IRefreshView header) {
                return ScrollCompat.canChildScrollUp(mRecyclerView);
            }
        });
        mRefreshLayout.setOnChildScrollDownCallback(new SmoothRefreshLayout.OnChildScrollDownCallback() {
            @Override
            public boolean canChildScrollDown(SmoothRefreshLayout parent, @Nullable View child, @Nullable IRefreshView footer) {
                return ScrollCompat.canChildScrollDown(mRecyclerView);
            }
        });
上拉加载我是用的adapter的

**Comment by dkzwm** [comment]
@LambdaV5 你的意思是你在Adapter的加载更多完成回调里调用了refreshComplete()？出现了内容视图偏移的问题？

**Comment by LambdaV5** [comment]
是的,连续上拉的时候会,普通上拉不会

**Comment by dkzwm** [comment]
@LambdaV5  这边修改了BUG，但同时对库有非常大的改动，这边如果急用，请在你封装的MySmoothRefreshLayout内部写个refreshComplete的替代方法，在refreshComplete前判断下isRefreshing或者isLoadingMore 如果是就return掉不处理就行。升级到新版可能会导致修改的地方非常多，因为这边删除了mode这个重复功能属性，具体请看更新日志。不好意思。
