### ISSUE TITLE
越界回弹的效果有点奇怪

### ISSUE THREAD

**Issue by MisoraRin** [dkzwm/SmoothRefreshLayout#110]
似乎并没有衔接原先滑动的速度，依然有碰到边界的感觉。
现在的效果更像是在到边界之后播放了一个动画。
SmartRefreshLayout的越界回弹感觉更自然一些。
请问有优化的可能吗

**Comment by dkzwm** [comment]
主要越界回弹本来就是苹果系OS带的效果，这边是最大限度模仿iOS效果，在iOS上就是手势快速滑动后滚动到边界会极速衰减到静止然后再回弹，感觉上就是碰到了很硬的果冻一样，并不像弹簧一样有比较大的张力，当然如果想动画更加柔和可以配置MinOverScrollDuration和MaxOverScrollDuration，配置更大的越界时长会晓得速度衰减不是那么快。如果是觉得越界距离不够就只能修改代码，或者我开放配置越界距离函数出来。

**Comment by MisoraRin** [comment]
怎么说，感觉有点太棉软了，减速快没问题，但是感觉上怪怪的。有种断裂感，不像是越界回弹，反而像是滑到底部播放了一段动画。
我刚才去试了一下QQ，它的回弹距离更短更快，但是就感觉很流畅。

**Comment by dkzwm** [comment]
那得继承直接修改下回弹时长，mDurationOfFlingBack修改小一些，现在值是550，我是根据我MBP上体验感估算的值，

**Comment by MisoraRin** [comment]
仔细对比了一下，个人感觉原因是回弹的速度慢了一些。
不过已经ok了，这只是一个小建议，改不改都无伤大雅。

**Comment by MisoraRin** [comment]
好的谢谢你的回复。

**Comment by dkzwm** [comment]
本身QQ的效果和苹果系OS的还是不一样的，当然想改成QQ那样也不是很难的，可以配置回滚插值器和时长，调一下能调个大概，毕竟本库最初实现的效果就是QQ那种，只是后面考虑到是模仿iOS就尽量做成iOS的效果，当然个人感觉毕竟有差异，具体达没达到iOS的效果也难说，哈哈哈

**Comment by MisoraRin** [comment]
加油
