### ISSUE TITLE
setHeaderBackgroundColor方法被删除后如何设置背景色？

### ISSUE THREAD

**Issue by getglory** [dkzwm/SmoothRefreshLayout#111]
删除方法 `setHeaderBackgroundColor`、`setFooterBackgroundColor`，封装布局管理器后，背景色填充改为用户在刷新视图层实现。   
有具体的例子吗

**Comment by dkzwm** [comment]
直接设置Header/Footer视图的BackgroundColor

**Comment by getglory** [comment]
> 直接设置Header/Footer视图的BackgroundColor

我设置了颜色，但下拉超过Header高度的时候，上方就露出透明部分
`<?xml version="1.0" encoding="utf-8"?>
<me.dkzwm.widget.srl.SmoothRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/srl_invite"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:sr_enableOverScroll="false">

    <com.yalalat.yuzhanggui.widget.refresh.CustomHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/app_background"/>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_invite"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</me.dkzwm.widget.srl.SmoothRefreshLayout>`

**Comment by dkzwm** [comment]
@getglory 大兄弟，更新下`1.7.1.2.androidx`，然后如下设置
```
SmoothRefreshLayout.LayoutManager layoutManager = mRefreshLayout.getLayoutManager();
if (layoutManager instanceof VRefreshLayoutManager) {
    VRefreshLayoutManager refreshLayoutManager = (VRefreshLayoutManager) layoutManager;
    refreshLayoutManager.setHeaderBackgroundColor(Color);
    refreshLayoutManager.setFooterBackgroundColor(Color);
}
```
之前删除的时候考虑是让用户实现，你既然提出来需要用，想了想还是默认实现好了。

**Comment by getglory** [comment]
> @getglory 大兄弟，更新下`1.7.1.2.androidx`，然后如下设置
> 
> ```
> SmoothRefreshLayout.LayoutManager layoutManager = mRefreshLayout.getLayoutManager();
> if (layoutManager instanceof VRefreshLayoutManager) {
>     VRefreshLayoutManager refreshLayoutManager = (VRefreshLayoutManager) layoutManager;
>     refreshLayoutManager.setHeaderBackgroundColor(Color);
>     refreshLayoutManager.setFooterBackgroundColor(Color);
> }
> ```
> 
> 之前删除的时候考虑是让用户实现，你既然提出来需要用，想了想还是默认实现好了。

好的，非常感谢！
