### ISSUE TITLE
HorizontalSmoothRefreshLayout设置wrap_content不起作用

### ISSUE THREAD

**Issue by dovginka** [dkzwm/SmoothRefreshLayout#113]
suport最终版版

HorizontalSmoothRefreshLayout高度默认全屏了，并把下面的view都出去了

**Comment by dkzwm** [comment]
不是很懂你的意思，意思是说HSRL整体设置自适应高度不起作用还是说内部的内容视图设置自适应高度不起作用？具体布局是怎么样的，理论上不起作用都是内部视图占满高度了，你可以检查下，本质上布局和FrameLayout逻辑没啥大的区别的
