### ISSUE TITLE
NPE: SmoothRefreshLayout.getIndicator()

### ISSUE THREAD

**Issue by yudanhezhongweijie** [dkzwm/SmoothRefreshLayout#114]
你好，我碰到一个奇怪的问题，不知道是什么问题所以来请教一下
![image](https://user-images.githubusercontent.com/43075130/80748321-bb75ce00-8af2-11ea-9d81-e2bdb6c76d0b.png)
![image](https://user-images.githubusercontent.com/43075130/80748413-e102d780-8af2-11ea-90da-4a06ab242542.png)
我目前的情况是这样的。 在一个viewpager里面有3个fragment，每一个都有自己的SRL和header。触发这个错误的操作是在fragment B或者C的交互中触发fragment A的刷新和header的显示（viewpager这个时候还会跳转到fragment A，此时fragment A应该还没有显示出来，程序就崩溃了。)
我猜测是fragment还没显示的话refreshlayout就还不能读取所有的信息是吗？
谢谢

**Comment by dkzwm** [comment]
问题出在VRefreshLayoutManager里的Layout引用为空了，应该视图之前触发了onDetachedFromWindow，视图还没有重新添加到视图树里就操作产生的问题

**Comment by yudanhezhongweijie** [comment]
谢谢
