### ISSUE TITLE
如何同时更新SRL头部和recyclerview adapter data

### ISSUE THREAD

**Issue by yudanhezhongweijie** [dkzwm/SmoothRefreshLayout#116]
你好，我想咨询一下处理SRL头部刷新状态和recyclerview数据更新的问题.
我目前是有一个livedata来检测头部刷新（上拉加载）的状态，另一个livedata是recyclerview的数据。加载的数据相当于插入到原来的list的顶部。我发现如果用过上拉加载触发的refresh 就比较容易触发这个问题，但也不是百分百。如果是通过scroll listener触发的加载就基本上没有数据显示异常的问题

我猜大概的情况就是SRL的头部在更新或者收缩的时候会影响recyclerview的状态，如果这个时候异步更新recyclerview adapter的数据，就会导致数据显示错位。问题在于recyclerview数据更新是异步的，那我想的是等头部刷新结束后再更新数据。
我目前尝试了下面这几个检测，但是还是会有数据错位的情况，请问是我的使用方法不正确还是个bug？应该要如何使用？谢谢
```
                while (binding.refreshLayout.isRefreshing
                    || binding.refreshLayout.isHeaderInProcessing
                    ||binding.refreshLayout.isMovingHeader
                    || binding.refreshLayout.isNotYetInEdgeCannotMoveHeader) {
                    delay(50L)
                }
                mAdapter.setDiffNewData(it.toMutableList())
```

**Comment by dkzwm** [comment]
@fishballzzz SRL至少在头部刷新时是没有对滚动视图做任何操作的，在尾部加载回弹过程中会才会调用同步滚动，你的描述头部更新也会数据错误，所以应该可以排除是SRL的问题。
参考你的代码是使用了BRVA的Diff能力，怀疑是未正确实现Diff能力导致的数据更新错误问题，具体可以查看BRVA的文档。

**Comment by dkzwm** [comment]
@fishballzzz 你的意思是你实际调用的是上拉加载，然后数据插入到列表头的话，默认配置的确会出现错位问题，因为SRL默认开启了同步回滚会在回滚过程中设置滚动，你试试
```
refreshLayout.setEnableCompatSyncScroll(false);
```

**Comment by yudanhezhongweijie** [comment]
> 
> 
> @fishballzzz 你的意思是你实际调用的是上拉加载，然后数据插入到列表头的话，默认配置的确会出现错位问题，因为SRL默认开启了同步回滚会在回滚过程中设置滚动，你试试
> 
> ```
> refreshLayout.setEnableCompatSyncScroll(false);
> ```

感谢回复! 我又尝试了一下，依然会有错位的问题。
我还发现如果头部显示的情况我继续往上拉，错位基本每次都会出现。这个东西实在不好测试。。我也有点像是在猜。。

**Comment by dkzwm** [comment]
@fishballzzz 关闭后都错位，那应该是你未正确实现Diff能力导致的数据更新错误问题。因为SRL对内部有侵入的点就同步滚动这一个地方。

**Comment by yudanhezhongweijie** [comment]
好的，我再检查一下，感谢回复
