### ISSUE TITLE
线上捕获到一个空指针异常

### ISSUE THREAD

**Issue by jyh149129** [dkzwm/SmoothRefreshLayout#118]
使用腾讯bugly捕获到了线上一个空指针异常，不知道如何解决，特发这里，希望作者能指点下思路从哪里入手。
以下是上报的堆栈信息（代码行号可能不准确）
`Attempt to invoke virtual method 'me.dkzwm.widget.srl.c.b me.dkzwm.widget.srl.SmoothRefreshLayout.getIndicator()' on a null object reference

me.dkzwm.widget.srl.manager.VRefreshLayoutManager.boolean offsetChild(me.dkzwm.widget.srl.extra.IRefreshView,me.dkzwm.widget.srl.extra.IRefreshView,android.view.View,android.view.View,android.view.View,int)(VRefreshLayoutManager.java:1)
me.dkzwm.widget.srl.SmoothRefreshLayout.void updatePos(int)(SmoothRefreshLayout.java:20)
me.dkzwm.widget.srl.SmoothRefreshLayout.void movePos(float)(SmoothRefreshLayout.java:9)
me.dkzwm.widget.srl.SmoothRefreshLayout.void moveHeaderPos(float)(SmoothRefreshLayout.java:27)
me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.void run()(SmoothRefreshLayout.java:19)
android.os.Handler.handleCallback(Handler.java:815)
android.os.Handler.dispatchMessage(Handler.java:104)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:5958)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)`

**Comment by jyh149129** [comment]
机型：oppo ，Android 5.1。
这边我自定义了一个header，是否会跟这个有关系，代码如下很简单：
`public class CustomMateriaHeader extends MaterialHeader<IIndicator> {
    public CustomMateriaHeader(Context context) {
        super(context);
    }
    public CustomMateriaHeader(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    public CustomMateriaHeader(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }
    //支持在代码中动态设置刷新头背景色,以适配支持夜间模式
    public void setBackgroundColor(int color){
        mDrawable.setBackgroundColor(color);
    }
}`

**Comment by dkzwm** [comment]
@jyh149129 大兄弟，实在不好意思，之前都太忙了，没时间处理这些，这边你更新下1.7.1.4.androidx，这边处理了下这种情况。
