### ISSUE TITLE
下拉松手才刷新

### ISSUE THREAD

**Issue by ongakuer** [dkzwm/SmoothRefreshLayout#119]
咨询一下，下拉刷新功能，使用后发现在下拉拖拽时，如果滑动超过临界点，不松手再向上拖拽收回，会触发 onRefreshing 的回调，导致开始数据获取。

怎么实现下拉超过临界点，并且松手才算一次刷新？  与 [ReleaseToRefresh Demo](https://github.com/dkzwm/SmoothRefreshLayout/blob/master/app/src/main/java/me/dkzwm/widget/srl/sample/ui/TestReleaseToRefreshActivity.java)  一样呢？ 这个 Demo 里貌似没有特殊配置

目前使用配置如下：

```java
refreshLayout.setHeaderView(RefreshHeaderView(refreshLayout.context)) // 自定义的Header
refreshLayout.setDisableLoadMore(true)
refreshLayout.setDisablePerformLoadMore(true)
refreshLayout.setEnableAutoLoadMore(false)
refreshLayout.setEnableOverScroll(false)
refreshLayout.setDisableWhenAnotherDirectionMove(true)
refreshLayout.setEnableCompatSyncScroll(true)
```

**Comment by dkzwm** [comment]
@ongakuer 如果是拖拽，配置`setEnablePerformFreshWhenFling(false)`看下

**Comment by ongakuer** [comment]
好的，可以了。感谢哈
