### ISSUE TITLE
关于滑动问题

### ISSUE THREAD

**Issue by a1227308812** [dkzwm/SmoothRefreshLayout#12]
就是在滑动的时候由于惯性，当到顶或者到底之后控件会自动把刷新头部拉出来一下，虽然不会触发刷新，但是个人感觉体验不好，可不可以当在惯性下到顶或者到底时不会拉出头部或者底部，直接在第一条或者最后一条停下，然后在手动下拉触发刷新或者加载更多。
请问在哪里可以修改这个惯性问题？

**Comment by dkzwm** [comment]
@a1227308812  setEnableOverScroll(false);关闭越界回弹
