### ISSUE TITLE
Header和Footer的滚动问题

### ISSUE THREAD

**Issue by Techck** [dkzwm/SmoothRefreshLayout#121]
RecyclerView中没有内容时Header能无限下拉，有内容但是没有填满一页时，Footer能无限上拉，请问我需要怎样设置才能控制滚动的距离与正常情况一样？

**Comment by dkzwm** [comment]
不是很明白你的意思....
如果是需要控制最大移动距离可以配置`setMaxMoveRatioOfHeader`或者`setMaxMoveRatioOfFooter`。

**Comment by Techck** [comment]
第一个问题，Footer能无限上拉，我设置了setMaxMoveRatioOfFooter(1.2f)，用得是ClassicFooter，当RecyclerView里面没有数据或者数据没有填充满整个屏幕时，Footer能一直跟随手指往上滚动超过最大限制，但是如果数据填充超过了整个屏幕就不会出现这个问题。
第二个问题，Header能无限下拉，意思差不多，但是只在没有填充数据的情况下会出现。

**Comment by dkzwm** [comment]
@Techck 请更新下`1.7.1.6.androidx`版本，问题已修改，你这种情况之前没有覆盖到。感谢！

**Comment by Techck** [comment]
我使用的就是1.7.1.6.androidx

**Comment by dkzwm** [comment]
@Techck 兄弟，我才上传的`1.7.1.6.androidx`，你再仔细看看

**Comment by Techck** [comment]
更新版本号后还存在一个问题，如果RecyclerView没有填充数据，手指在界面上滑动时，Footer还能向上滚动，Header的indicator.hasTouched()方法返回的是false，

**Comment by dkzwm** [comment]
没有复现你这个问题

**Comment by Techck** [comment]
初始化设置了setDisableRefresh(false);setDisableLoadMore(false);，在旧版本上是没问题的，更新了新版本后就出现我所说的问题

**Comment by dkzwm** [comment]
这边测试就是直接开始刷新和加载很多，内部视图为空数据的RecyclerView，不存在刷新控制住加载更多没控制住的问题，逻辑是一样的。

**Comment by Techck** [comment]
我的意思是，内部视图为空数据的RecyclerView，在以前的版本中上拉不会出现加载更多，但是现在出现了，是否是需要设置某些属性？

**Comment by dkzwm** [comment]
`setDisableLoadMoreWhenContentNotFull(true)`

**Comment by Techck** [comment]
如果我调用了这个方法，就会出现一种情况：我加载了第一页的数据，但是数据没有并没有填满RecyclerView的一页，就会造成我无法上拉加载下一页的数据。

**Comment by dkzwm** [comment]
首先`1.7.1.6.androidx`与之前的版本相比只修改了最大移动距离控制代码，不存在之前的版本在空布局时不能拉出`Footer`的问题，我这边测试上个版本是能拉出的，其次如果你想空布局时不能拉出`Footer`，可以在空数据时禁用上拉加载功能，当填充数据后再打开。

**Comment by Techck** [comment]
我继承了SmoothRefreshLayout，并在初始化时设置了如下参数。从1.6.4.3升级到1.7.1.6.androidx，就出现了我所说的问题。
setDisableRefresh(false);
setDisableLoadMore(false);
// 设置下拉刷新为Material样式，覆盖在内容之上
setEnablePinContentView(true);
setEnableKeepRefreshView(true);
setEnablePinRefreshViewWhileLoading(true);
// 开启自动加载更多
setEnableAutoLoadMore(true);
// 默认是打开了越界回弹的。
setEnableOverScroll(false);
// 内部视图含有横向滑动视图(例如ViewPager)时需设置该属性为ture（默认:false）
setDisableWhenAnotherDirectionMove(true);
setEnableSmoothRollbackWhenCompleted(true);
// 设置下拉刷新最大距离
setMaxMoveRatioOfHeader(1.5f);
// 设置下拉到哪个位置开始刷新
setRatioOfHeaderToRefresh(1.5f);
// 设置刷新时保持的位置
setRatioToKeepHeader(1.5f);
// 设置上拉加载最大距离
setMaxMoveRatioOfFooter(1.2f);

**Comment by dkzwm** [comment]
那可能之前的版本有BUG，毕竟这个项目一直是我一个人抽空余时间在维护，这边你升级到新版按照我描述的空白时禁用加载更多，填充数据后开启加载更多即可。

**Comment by Techck** [comment]
好的，明白了，感谢！
