### ISSUE TITLE
二级刷新，上拉加载更多回调怎么不触发

### ISSUE THREAD

**Issue by longkehuawei** [dkzwm/SmoothRefreshLayout#122]
二级刷新，上拉加载更多，这个不支持么？

**Comment by dkzwm** [comment]
上拉加载和二级刷新没有冲突吧，测试开启上拉加载功能没有发现不能上拉加载。

**Comment by longkehuawei** [comment]
这样开启上拉加载么？app:sr_enableLoadMore="true"，我试了，好像不行

**Comment by longkehuawei** [comment]
> 上拉加载和二级刷新没有冲突吧，测试开启上拉加载功能没有发现不能上拉加载。

 mRefreshLayout.setOnRefreshListener(
                new TwoLevelRefreshingListenerAdapter() {
                    @Override
                    public void onTwoLevelRefreshing() {
                        mRefreshLayout.setEnableInterceptEventWhileLoading(true);
                        mTwoLevelCount++;
                        mHandler.postDelayed(
                                new Runnable() {
                                    @Override
                                    public void run() {
                                        startActivity(
                                                new Intent(
                                                        getApplicationContext(),
                                                        SecondFloorActivity.class));
                                        mRefreshLayout.refreshComplete(200);
                                    }
                                },
                                2000);
                    }

                    @Override
                    public void onRefreshing() {
                        mCount++;
                        mHandler.postDelayed(
                                new Runnable() {
                                    @Override
                                    public void run() {
                                        String times =
                                                getString(R.string.number_of_one_level_refresh)
                                                        + mCount;
                                        mRefreshLayout.refreshComplete();
                                        mTextView.setText(times);
                                    }
                                },
                                1000);
                    }

                    @Override
                    public void onLoadingMore() {
//                        super.onLoadingMore();
                        mCount++;
                        mHandler.postDelayed(
                                new Runnable() {
                                    @Override
                                    public void run() {
                                        String times =
                                                getString(R.string.number_of_one_level_refresh)
                                                        + mCount;
                                        mRefreshLayout.refreshComplete();
                                        mTextView.setText(times);
                                    }
                                },
                                1000);
                    }
                });

**onLoadingMore()** 这个方法不回调

**Comment by longkehuawei** [comment]
> 上拉加载和二级刷新没有冲突吧，测试开启上拉加载功能没有发现不能上拉加载。

有这个demo么，我用现在demo测试好像不行

**Comment by dkzwm** [comment]
就`demo`里的`TestTwoLevelRefreshActivity`对应的`xml`文件添加了`app:sr_enableLoadMore="true"`，测试能触发加载更多同时回调没有问题。

**Comment by longkehuawei** [comment]
> 就`demo`里的`TestTwoLevelRefreshActivity`对应的`xml`文件添加了`app:sr_enableLoadMore="true"`，测试能触发加载更多同时回调没有问题。

好的，我现在好像可以了，谢谢呀
