### ISSUE TITLE
头用MaterialHeader，foot 用ClassicFooter，下拉MaterialHeader头上面空一段白色的

### ISSUE THREAD

**Issue by longkehuawei** [dkzwm/SmoothRefreshLayout#123]
头用MaterialHeader，foot 用ClassicFooter，下拉MaterialHeader头上面空一段白色的，有方法头部固定，foot 接到后面么，不覆盖下面的布局

**Comment by dkzwm** [comment]
使用`MaterialSmoothRefreshLayout`，依次设置`ClassicFooter `,再调用`materialStyle`方法。
