### ISSUE TITLE
此框架目前不支持viewbinding的adapter

### ISSUE THREAD

**Issue by ElevenVi** [dkzwm/SmoothRefreshLayout#124]
此框架目前不支持viewbinding的adapter，如果还在维护，需要更新以支持这个官方组件
viewbinding是官方推出的视图绑定组件，支持java和kotlin，但是结合这个刷新库以后，出现bug
现象是使用
`View view = LayoutInflater.from(mContext).inflate(R.layout.xxxx, parent,false);`
方式绑定适配器视图，recycler能在刷新库的包裹下自由滑动并且抛掷，但是使用`XxxxBinding.inflate(LayoutInflater.from(viewGroup.getContext()),viewGroup,false);`
方式绑定视图的话，初次进入页面，recycler能滑动但不能抛掷（不能快速滑动），如果想让recycler进行抛掷，需要触发一次recycler越界（触发刷新或加载或越界回弹）
这个问题不解决，这个库基本就不能用了，因为以后的android原生开发，都会迁移到viewbinding中

**Comment by dkzwm** [comment]
测试没有重现你所说的问题，原理上也不存在这种BUG，编译时动态生成的Binding类仅仅只做了视图的搜索、类型匹配、绑定对象而已，实际效果和`LayoutInflater.from`没有任何区别，只是一个是开发者手动操作，一个编译器动态生成的本地代码。
测试我是直接修改的`demo`中的`NestedPageWithSrlFragment`类
