### ISSUE TITLE
OverScroll 能自定义吗?

### ISSUE THREAD

**Issue by hyl87** [dkzwm/SmoothRefreshLayout#125]
能不能像RecyclerView 提供一个 setEdgeEffectFactory 方法 可以自定义 OverScroll

**Comment by dkzwm** [comment]
官方的EdgeEffect效果主要是在画布上进行绘画，不会操作视图进行移动的。本库的OverScroll是需要对视图进行移动的，如果需要官方的EdgeEffect效果，可以直接关闭本库的OverScroll，使用内容视图的EdgeEffect效果

**Comment by hyl87** [comment]
哦了
