### ISSUE TITLE
ext-dynamic-rebound 这个依赖不下来

### ISSUE THREAD

**Issue by hyl87** [dkzwm/SmoothRefreshLayout#126]

**Comment by hyl87** [comment]
提示找不到 not found

**Comment by dkzwm** [comment]
jcenter要跑路了，切到jitpack了。你按照readme描述重新依赖下。

**Comment by hyl87** [comment]
Failed to resolve: com.github.dkzwm:SmoothRefreshLayout:ext-util 
还是不行 都找不到了

**Comment by dkzwm** [comment]
注意根`build.gradle`里
```

allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
    }
}
```
需要指定jitpack的仓库地址。

**Comment by hyl87** [comment]
![image](https://user-images.githubusercontent.com/1303038/113272456-3a304800-930e-11eb-9507-0ee07f7efe3b.png)
加了的 @dkzwm

**Comment by dkzwm** [comment]
网络的问题，翻下墙吧，我这边才测试依赖没有问题。

**Comment by hyl87** [comment]
好了 重启电脑才搞定，不知道什么原因

**Comment by hyl87** [comment]
又依赖不下来了
目前就只有 'com.github.dkzwm:SmoothRefreshLayout:core:1.7.2' 这个可以成功 其他的都要失败

**Comment by dkzwm** [comment]
`1.7.2`这个版本相较于`1.7.1.6.androidx`没有任何更新,仅仅用来测试`JitPack`,这边测试发现`JitPack`服务不靠谱，准备迁移到`Maven Central`。
