### ISSUE TITLE
 Could not resolve all files for configuration ':app:debugCompileClasspath'.

### ISSUE THREAD

**Issue by yrasulzade** [dkzwm/SmoothRefreshLayout#127]
I am getting this error when I try to run app.

Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.dkzwm:SmoothRefreshLayout:core.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by dkzwm** [comment]
Have you configured the following code in the `build.gradle` file in the root directory?
```
allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by dkzwm** [comment]
If you have already configured it, please try to clear the cache or restart the IDE, hope it can help you！

**Comment by yrasulzade** [comment]
Yes, I have configured everything correctly. I just cleared and rebult IDE, also restarted my notebook. Same error occurs. Do you have any idea how to solve it?

**Comment by dkzwm** [comment]
em.. I don’t know what the problem is, I can’t help you temporarily. I will test it tomorrow, hope I can find the reason tomorrow.

**Comment by dkzwm** [comment]
There should be a bug in the `JitPack` repository, here you can use the dependency of `JCenter` first while `JCenter` has not been closed.
```
    implementation 'me.dkzwm.widget.srl:core:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-util:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-material:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-horizontal:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-classics:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-two-level:1.7.1.6.androidx'
    implementation 'me.dkzwm.widget.srl:ext-dynamic-rebound:1.7.1.6.androidx'
```

**Comment by yrasulzade** [comment]
When I tried to use all 7 implementations with androidx, it gave me error saying 'Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.

But all I need was `core` library. When I used implementation  with androidx version (`me.dkzwm.widget.srl:core:1.7.1.6.androidx') it worked perfectly.

Thanks for your effort
