### ISSUE TITLE
Cannot resolve method transformPointToViewLocal in ViewGroup

### ISSUE THREAD

**Issue by yrasulzade** [dkzwm/SmoothRefreshLayout#128]
When I try to copy the `core` package to use it in my own project I get this error.  I don`t know how to fix it. 

Btw, I couldn\`t use your library in my project, that\`s why I am trying to copy the whole `core` package.

![quesa](https://user-images.githubusercontent.com/43597558/113356077-c95f4f00-9352-11eb-8e30-51da749d5f99.PNG)

**Comment by dkzwm** [comment]
This is a hidden method, you need to put the jar of `core/libs/classes.jar` at the top of the dependency before compiling.
You can view the code from line 111 to line 135 in the `core/build.gradle` file for the specific configuration.
