### ISSUE TITLE
里面有没有集成列表item的左滑删除功能啊？

### ISSUE THREAD

**Issue by a1227308812** [dkzwm/SmoothRefreshLayout#13]
有没有列表item的左滑删除功能啊？

**Comment by dkzwm** [comment]
@a1227308812  列表操作属于内部视图事务，内部视图事务本库是不参与，列表操作请移步其它滑动删除库
[SwipeDelMenuLayout](https://github.com/mcxtzhang/SwipeDelMenuLayout)
[SwipeRevealLayout](https://github.com/chthai64/SwipeRevealLayout)
这2个库都可以实现的。
