### ISSUE TITLE
横向刷新嵌套recycleView，无法取消，就是我手指右滑再左滑取消刷新操作会判定为执行刷新

### ISSUE THREAD

**Issue by LvBing1995** [dkzwm/SmoothRefreshLayout#130]

**Comment by LvBing1995** [comment]
recycleView无法取消，但是HorizontalScrollView可以

**Comment by dkzwm** [comment]
手指抬起时位置达到超过触发刷新的位置就会触发刷新，没有取消的操作

**Comment by LvBing1995** [comment]
> 手指抬起时位置达到超过触发刷新的位置就会触发刷新，没有取消的操作

找到原因了，可能是焦点问题，我把您的Demo中HorizontalRecyclerViewAdapter类里把mTextView.setOnClickListener和mTextView.setOnLongClickListener注释掉后，我执行刷新取消操作会出现问题。手势步骤:1.手指先右滑让刷新的header出来 2.继续往右这个时候如果我抬起手指那么会促发刷新方法，但是我不抬起手指而是把手指往左滑想取消此次手势操作，但是这个时候会促发刷新。但是点击事件写了后就不会出现这个问题。

**Comment by dkzwm** [comment]
不好意思，你按需更新下如下依赖，应该可以修复你说的问题了。
```
implementation 'com.github.dkzwm:srl-core:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-classics:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-material:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-dynamic-rebound:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-horizontal:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-two-level:1.7.2.1'
implementation 'com.github.dkzwm:srl-ext-util:1.7.2.1'
```
