### ISSUE TITLE
[QUESTION] How to stop footer scaling? 

### ISSUE THREAD

**Issue by yrasulzade** [dkzwm/SmoothRefreshLayout#131]
@dkzwm, I dont want to have footer scaling in my layout. When user reaches end of screen and tries to drag up, layout scales up too. I installed your sample APK. In that APK,  every activity has footer scaling, so I couldnt find a way to turn it off.

 Can you help me? Thanks.

**Comment by dkzwm** [comment]
Does trying call `setEnableOverScroll(false)` have an effect?

**Comment by dkzwm** [comment]
Or call `setDisableLoadMore(true)`?
Hope i understand what you mean correctly ₍₍ (̨̡ ‾᷄ᗣ‾᷅ )̧̢ ₎₎

**Comment by yrasulzade** [comment]
`setEnableOverScroll(false)` worked perfectly. Thanks for help :)
