### ISSUE TITLE
空指针异常canChildScrollDown

### ISSUE THREAD

**Issue by yyj001** [dkzwm/SmoothRefreshLayout#133]
大佬，请问一下，我们项目在线上报了空指针异常，但是我们自己无法复现。我们是嵌套了一个普通的recyclerview使用的。堆栈如下
  | me.dkzwm.widget.srl.util.ScrollCompat.canChildScrollDown(ScrollCompat.java:70)
  | me.dkzwm.widget.srl.SmoothRefreshLayout.isNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout.java:3833)
  | me.dkzwm.widget.srl.SmoothRefreshLayout.isNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout.java:3819)
  | me.dkzwm.widget.srl.SmoothRefreshLayout.canScrollVertically(SmoothRefreshLayout.java:3251)
  | android.view.ViewGroup.isNeedScrollToTop(ViewGroup.java:2038)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1976)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | android.view.ViewGroup.dispatchStatusBarTop(ViewGroup.java:1972)
  | com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:494)
  | android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5808)
  | android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5676)
  | android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5124)
  | android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5177)
  | android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5143)
  | android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5300)
  | android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5151)
  | android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5357)
  | android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5124)
  | android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5177)
  | android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5143)
  | android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5151)
  | android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5124)
  | android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5177)
  | android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5143)
  | android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5333)
  | android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5503)
  | android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3109)
  | android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2652)
  | android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2643)
  | android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3086)
  | android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
  | android.os.MessageQueue.nativePollOnce(Native Method:0)
  | android.os.MessageQueue.next(MessageQueue.java:363)
  | android.os.Looper.loop(Looper.java:176)
  | android.app.ActivityThread.main(ActivityThread.java:8349)
  | java.lang.reflect.Method.invoke(Native Method:0)
  | com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
  | com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
版本是1.6.6.8,  如果新版本已经修复了的话我升级一下

**Comment by yyj001** [comment]
我在初始化的时候尝试手动调用    mRefreshLayout.scrollTargetView = recyclerView，还是不行

**Comment by dkzwm** [comment]
Support库对应版本已停止更新了，所以即使有BUG也不会修了，你可以尝试更新到最新版本，或者针对空指针异常做层保护，看日志应该是view为空了，你可以自己实现下对应接口来规避这种问题。

**Comment by yyj001** [comment]
好的，那我们升级到最新版本看看
