### ISSUE TITLE
New Android 12 non-sdk restrictions are coming

### ISSUE THREAD

**Issue by 7Koston** [dkzwm/SmoothRefreshLayout#135]
Please revisit your project code, because it uses some sdk which won't be available in Android 12
Like `Landroid/view/ViewGroup;->transformPointToViewLocal([FLandroid/view/View;)V` in `SmoothRefreshLayout.java:3081`
More information here:
https://developer.android.com/about/versions/12/non-sdk-12

**Comment by dkzwm** [comment]
@7Koston Thx. I know it.
I will release a new version to be compatible with it.

**Comment by dkzwm** [comment]
The version has been released.
