### ISSUE TITLE
与 AppBarLayout + ViewPager  配合使用后的滚动问题 

### ISSUE THREAD

**Issue by ongakuer** [dkzwm/SmoothRefreshLayout#136]
使用场景布局如下

```
CoordinatorLayout

    AppBarLayout
        ViewGroup (height = 200dp, layout_scrollFlags="scroll|exitUntilCollapsed")

    ViewPager (height = match_parent, layout_behavior="@string/appbar_scrolling_view_behavior")
        SmoothRefreshLayout
            RecyclerView 或 NestedScrollView
```

当 RecyclerView 向上滑动100dp后（连带AppBarLayout也一起滑动）。 然后去滑动 AppBarLayout ，大概率滑动没有反应。

**Comment by ongakuer** [comment]
上面的情况，如果通过设置  isNotYetInEdgeCannotMoveHeader 可以临时解决

```kotlin
setOnHeaderEdgeDetectCallBack(object : SmoothRefreshLayout.OnHeaderEdgeDetectCallBack {
            override fun isNotYetInEdgeCannotMoveHeader(
                parent: SmoothRefreshLayout?, child: View?, header: IRefreshView<*>?
            ): Boolean {
                
                return false 
            }
        })
```

另外，源码中  isNotYetInEdgeCannotMoveHeader 的 header  传成了 mFooterView 

isNotYetInEdgeCannotMoveFooter 也一样传反了

https://github.com/dkzwm/SmoothRefreshLayout/blob/ec94499239cbaa51b0f74d6f75fdb680970f2e05/core/src/main/java/me/dkzwm/widget/srl/SmoothRefreshLayout.java#L3512

**Comment by dkzwm** [comment]
@ongakuer 感谢反馈，关于第一个滑动AppBarLayout无法滑动的问题，测试剔除SRL也是一样的问题，不属于SRL的BUG。第二个参数传递错误这边会发个版本修复下。疏忽大意了....

**Comment by ongakuer** [comment]
我是使用 NestedScrollView 测试的，剔除SRL是可以正常拖拽 AppBarLayout的 😂 。   

可能业务场景不同，如果 AppBarLayout 的内容很多的情况下，拖动了一点 SRL的内容，就导致 AppBarLayout 不能正常浏览体验貌似不太好。

主要因为 AppBarLayoutUtil 默认实现的 isNotYetInEdgeCannotMoveHeader ， 判断了mFullyExpanded。 如果可以配置就好了 

https://github.com/dkzwm/SmoothRefreshLayout/blob/0e0cfbd2b041c3cdd63ff3d47c8fc784f6752514/core/src/main/java/me/dkzwm/widget/srl/util/AppBarLayoutUtil.java#L64

**Comment by dkzwm** [comment]
@ongakuer 这边使用`NestedScrollView `测试发现的确有点问题，这边修改以下发布一个版本。感谢反馈！

**Comment by ongakuer** [comment]
感谢维护项目 😄
