### ISSUE TITLE
多层嵌套出现冲突

### ISSUE THREAD

**Issue by youliye** [dkzwm/SmoothRefreshLayout#137]
具体问题就是:
我的activity里边有一个viewpager,viewpager的子view也是viewpager,方向都是横向,当父viewpager的第一个item里边含有多个view的时候,向左滑动没问题,再返回来的时候,子view就划不动了,直接就触发了刷新的view

代码就是demo上复制的
private fun initRefresh(){
        val header= MaterialHeader<IIndicator>(mActivity)
        header.setColorSchemeColors(intArrayOf(Color.RED, Color.BLUE, Color.GREEN, Color.BLACK))
        header.setPadding(PixelUtl.dp2px(mActivity, 25f), 0, PixelUtl.dp2px(mActivity, 25f), 0)
        hsrl.setHeaderView(header)

        val footer= MaterialFooter<IIndicator>(mActivity)
        footer.setProgressBarColors(intArrayOf(Color.RED, Color.BLUE, Color.GREEN, Color.BLACK))
        hsrl.setFooterView(footer)

        hsrl.setDisableLoadMore(false)
        hsrl.setDisablePerformLoadMore(false)
        hsrl.setEnableKeepRefreshView(true)
        hsrl.setDisableWhenAnotherDirectionMove(true)
        hsrl.setOnRefreshListener(
            object : RefreshingListenerAdapter() {
                override fun onRefreshing() {
                    getJieTuList(true)
                }

                override fun onLoadingMore() {
                    getJieTuList(false)
                }
            })
        hsrl.setRatioToKeep(1f)
        hsrl.setRatioToRefresh(1f)
    }

**Comment by dkzwm** [comment]
这种需要你自定义边界判断逻辑，自带能力考虑到性能不会遍历那么深从而不会识别到多个'ViewPager'嵌套。只能由使用者根据实际应用场景进行适配。
