### ISSUE TITLE
ColorOS 12 上发生的问题（可持续复现）

### ISSUE THREAD

**Issue by fankes** [dkzwm/SmoothRefreshLayout#140]
### 最外层若继续嵌套了 ViewPage 或 CoordinatorLayout 则百分之百触发此问题
https://user-images.githubusercontent.com/37344460/143922302-6a81b57d-8146-47e4-9efa-c9fbf813f0db.mp4

**Comment by fankes** [comment]
若您有精力继续维护项目的话，可以回复我，我在有空的时候会上传一个复现问题的demo，辛苦您还望能帮忙看一下这个问题

**Comment by dkzwm** [comment]
Android12本身自带拉伸滚动效果,无论系统版本最好都配置禁用系统原生的EdgeEffect.当然如果你是需要系统本身的拉伸滚动效果可以根据系统版本进行配置，在Android12使用系统原生效果。详细见[拉伸滚动效果](https://developer.android.com/about/versions/12/behavior-changes-all#overscroll)

**Comment by fankes** [comment]
> EdgeEffect

原生的 EdgeEffect 效果我一直都是调为禁用状态，目前问题出在视频所述， SmoothRefreshLayout 延迟响应回弹事件

**Comment by dkzwm** [comment]
我手里没有相关设备，猜想应该是Fling滚动传递消耗有问题，也许是ROM的BUG BUG。抽空我在Android12虚拟机上跑看看

**Comment by fankes** [comment]
> 我手里没有相关设备，猜想应该是Fling滚动传递消耗有问题，也许是ROM的BUG BUG。抽空我在Android12虚拟机上跑看看

我已经在原生 Android 12 虚拟机跑过了，没有问题，只有 ColorOS 12 有这个问题
可以去 OPPO 开放平台申请一个云手机调试，我是刚好手头有 OPPO 手机测出来这个问题，盲猜 ColorOS12 乱改了什么东西
## 补充一句 ColorOS 11 没有问题
在 CoordinatorLayout 和 TabLayout 联动嵌套和直接使用代码创建单独的 SmoothRefreshLayout 使用 addView 塞入容器，不使用 Layout Inflate
以上两种情况 SmoothRefreshLayout 内部套入 RecycleView 这个 BUG 能得到 100% 复现

**Comment by fankes** [comment]
> 在 CoordinatorLayout 和 TabLayout 联动嵌套和直接使用代码创建单独的 SmoothRefreshLayout 使用 addView 塞入容器，不使用 Layout Inflate 以上两种情况 SmoothRefreshLayout 内部套入 RecycleView 这个 BUG 能得到 100% 复现

这个地方指的是在一个通过 xml 加载的容器中使用代码动态创建一个 new SmoothRefreshLayout 并 add 入父容器中，同时 SmoothRefreshLayout 中塞入 RecycleView，layoutparam 均为 match_parent

**Comment by fankes** [comment]
麻烦了，有时间再看看吧，现在 ColorOS12 也刚公测不久，如果日后通过官方更新这个问题被修复了，那就再说，目前可以说不是特别影响用户体验范围的 BUG

**Comment by peerless2012** [comment]
这个问题有答案了吗？

**Comment by fankes** [comment]
> 这个问题有答案了吗？

没有，我试过 C.24 C.39 都还有这个问题，甚至是一加的手机
在同样魔改版的 氧OS12 的 C.40 上没发生这个问题

**Comment by dkzwm** [comment]
由于我这里没有相关设备且在原生系统上未复现该问题，实在是没法进行测试，如果你们方便可以自己断点调试下。

**Comment by fankes** [comment]
> 由于我这里没有相关设备且在原生系统上未复现该问题，实在是没法进行测试，如果你们方便可以自己断点调试下。

如果有 oppo 开发者账号的话其实可以去云测看一下

**Comment by fankes** [comment]
> 由于我这里没有相关设备且在原生系统上未复现该问题，实在是没法进行测试，如果你们方便可以自己断点调试下。

这个问题在 C.46 的 ColorOS 12 上已测试被修复，是C12公测版本的BUG，该问题暂时先这样，有问题再看。
