### ISSUE TITLE
无法拉取到依赖

### ISSUE THREAD

**Issue by 13120241790** [dkzwm/SmoothRefreshLayout#141]
implementation 'com.github.dkzwm:srl-core:1.7.2.4'
    implementation 'com.github.dkzwm:srl-ext-horizontal:1.7.2.4'
    implementation 'com.github.dkzwm:srl-ext-util:1.7.2.4'

无法拉取到依赖，是不是 Jcenter 关停了拉取不到了。作者打算迁移到别的仓库吗？着急想使用，提供 jar 包也行

**Comment by 13120241790** [comment]
1.7.2.1 能正常拉取

**Comment by dkzwm** [comment]
我看了没问题呢，从1.7.2开始就迁移到`Sonatype`了，我这边测试是可以拉取的。你试着全局翻墙看下，最近GFW对外网访问劣化严重。

**Comment by 13120241790** [comment]
> 我看了没问题呢，从1.7.2开始就迁移到`Sonatype`了，我这边测试是可以拉取的。你试着全局翻墙看下，最近GFW对外网访问劣化严重。
好的，感谢及时回复给您点赞
