### ISSUE TITLE
设置setEnablePinContentView为true时，执行加载更多后的显示细节问题

### ISSUE THREAD

**Issue by jyh149129** [dkzwm/SmoothRefreshLayout#146]
设置setEnablePinContentView或者setEnablePinRefreshViewWhileLoading为true时，加载更多完成后，无法自动滚动显示出底部新加载的条目，而是需要手动滚动，请问这是该选项的默认行为还是bug？

**Comment by dkzwm** [comment]
Pin代表刷新视图是浮动在刷新内容之上而不是跟随刷新内容，那么自然无法和内容做到自动滚动显示出内容条目，因为如果将内容拉出视觉上很奇怪

**Comment by jyh149129** [comment]
一直以为setEnablePinContentView这个只是对于下拉起效的。想不到对于上拉体验也有影响。。。看来只能选择其一了。
