### ISSUE TITLE
惯性滑动越界后的动画有点突兀

### ISSUE THREAD

**Issue by gitgeek4dx** [dkzwm/SmoothRefreshLayout#15]
手指抬起后惯性滑动，刷新头和脚布局惯性滑动的效果有点突兀，慢慢的惯性滑，页面快要停止的时候，触发了刷新头的惯性滑动，一下就变得滑动速度很快

**Comment by dkzwm** [comment]
@gitgeek4dx  请使用1.4.2版本，新版修改了实现。我这边测试了5部手机，效果应该好很多了。如果还是很突兀，试着修改`setOverScrollDistanceRatio()`的值，默认是0.8f.可以改小点，移动距离会小一些。如果问题解决了麻烦反馈给我。谢谢。

**Comment by dkzwm** [comment]
暂时别用，发现有大问题。等修复再用。233333

**Comment by dkzwm** [comment]
@gitgeek4dx  已经可以依赖了

**Comment by dkzwm** [comment]
@gitgeek4dx  1.4.2版本我修改的比较匆忙，没有进行系统测试。今天无意间发现了有些问题。暂时请使用1.4.1版本，等今天抽空修复了再依赖。不好意思。

**Comment by dkzwm** [comment]
@gitgeek4dx  1.4.3 发布了。修复了一些BUG，优化了回弹效果

**Comment by gitgeek4dx** [comment]
@dkzwm 快速滑动到达顶部时触发的效果流畅自然了很多，但慢速依然很突兀，就是惯性滑到顶部几乎快停下的时候，会突然跳一下

**Comment by dkzwm** [comment]
@gitgeek4dx  你`setOverScrollDistanceRatio `把距离比再调小点，调到`.4`或者`.5`,然后把`setOverScrollDurationRatio`可以适当调大点。本库对内部视图没有做侵入处理，所以无法得知具体内部视图移动距离，都是直接依赖手势算出加速度，用插值器运算出大概移动距离的。后续会再尝试优化下效果。主要是本库不想侵入内部视图，造成高度耦合问题。

**Comment by gitgeek4dx** [comment]
@dkzwm 已解决，设置上面两个属性之后，效果已经很好。多谢！
另外，内容视图是否不能设置为GONE？如果在无数据时的空视图和有数据时的列表视图之间切换显示隐藏，只能设置INVISIBLE？

**Comment by dkzwm** [comment]
@gitgeek4dx 支持GONE啊，关于空视图，本库之前就已经支持多状态视图，你直接在XML定义空状态对应的视图布局ID，然后使用就行了。切换状态会有一个过渡动画处理，你可以看下Demo App的。Demo中的WithListViewActivity是多功能集成使用范例

**Comment by gitgeek4dx** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.jqugou.app, PID: 9984
                                                              android.view.InflateException: Binary XML file line #30: The content view is empty. Do you forget to added it in the XML layout file or add it in code ?
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)

上面是报错信息，下面是布局文件，RecyclerView置为gone就报这个错，第30行就是最后RefreshLayout的终止符。

    <com.jqugou.app.view.CustomWidgets.refreshview.JquDrawerRefreshLayout
        android:id="@+id/refresh_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/Divider_TenHeight"
        android:fadingEdge="none"
        android:fitsSystemWindows="true">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView_main_find"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/Divider_TenHeight"
            android:visibility="gone"
            android:fadingEdge="none">
        </android.support.v7.widget.RecyclerView>

    </com.jqugou.app.view.CustomWidgets.refreshview.JquDrawerRefreshLayout>

**Comment by dkzwm** [comment]
@gitgeek4dx  不好意思 我理解成其他视图去了，TargetView是不支持GONE的，关于此我不是很明白空状态视图为什么不放JquDrawerRefreshLayout里面，因为必须存在TargetView，否则无法判断是否到顶和是否到底，GONE属性下View是不会绘制的。空视图理论上应该放在RecyclerView里或者JquDrawerRefreshLayout里才是合理的吧

**Comment by dkzwm** [comment]
@gitgeek4dx  发布了1.4.4版本，这个版本继续优化了下效果。你可以看试下。
