### ISSUE TITLE
可以设置刷新完成后刷新view停留多久才开始回弹吗？

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#16]
可以设置刷新完成后刷新view停留多久才开始回弹吗？

**Comment by LongAgoLong** [comment]
还有，如何判断是否可以调用下一次autoRefresh

**Comment by dkzwm** [comment]
@LongAgoLong 
第一个问题：`refreshComplete(long delayDurationToChangeState) `；参数`delayDurationToChangeState`表示延迟多久修改状态为`SR_STATUS_COMPLETE`.设置大于0的值代表立即触发刷新视图的 `onRefreshComplete(SmoothRefreshLayout layout, boolean isSuccessful)`回调。体验上即刷新完成刷新视图停留`delayDurationToChangeState`时长。
第二个问题：1.4.2版本判断是否可以触发autoRefresh可以依靠设置`OnUIPositionChangedListener`。在`onChanged(byte status, IIndicator indicator)`回调中判断`status`==`SR_STATUS_INIT`时再判断内部视图是否在顶部。也可以借鉴自动加载更多的实现，继承SmoothRefreshLayout，扩展`onScrollChanged()`方法。每次内部视图滚动判断是否到顶部且`status`==`SR_STATUS_INIT`即触发autoRefresh；

**Comment by dkzwm** [comment]
@LongAgoLong  1.4.2版本我修改的比较匆忙，没有进行系统测试。今天无意间发现了有些问题。暂时请使用1.4.1版本，等今天抽空修复了再依赖。不好意思。

**Comment by LongAgoLong** [comment]
refreshComplete这个方法不应该设为静态吧？因为之前所有的都是调用refreshComplete无参的那个方法，现在想着最方便就是重写refreshComplete（）然后内部调用有参的那个，可是居然被静态了……

**Comment by dkzwm** [comment]
final`refreshComplete ()`方法目的是为了防止过于内部状态异常。因为这个方法逻辑牵涉比较多，而且是唯一一个停止刷新的入口。担心扩展会出问题，所以final。这里不会去掉final关键字的。

**Comment by dkzwm** [comment]
@LongAgoLong   1.4.3 发布了。修复了一些BUG，优化了回弹效果
