### ISSUE TITLE
Stop the loading more animation

### ISSUE THREAD

**Issue by mradzinski** [dkzwm/SmoothRefreshLayout#17]
Is there a way or method to stop the loading more animation after the app has finished loading more items? I saw there's a `refreshComplete()` method, but it doesn't stop the loading more animation. 

I'm actually using this library as a "pull UP to refresh" (the opposite of pull down to refresh), so I need a way to manually stop that animation regardless of if it loaded any new elements or not.

**Comment by dkzwm** [comment]
@mradzinski Hi, thank you for your question. Your needs when loading is done , skip the animation directly to display the items?  
Do it like this:
```
        mRefreshLayout.setOnRefreshListener(new RefreshingListenerAdapter() {
            @Override
            public void onRefreshBegin(final boolean isRefresh) {
                //do something you needed
                mRefreshLayout.setDurationToCloseFooter(0);
                mRefreshLayout.refreshComplete();
                mRefreshLayout.setDurationToCloseFooter(500);
            }
        });
```
Set "setDurationToCloseFooter (0)" before calling "refreshComplete ()", so that you can skip the animation and then set "setDurationToCloseFooter (needs duration)";
Hope to help you！

**Comment by mradzinski** [comment]
I'm currently doing something like:

```
        mRefreshLayout.setOnLoadMoreScrollCallback { _, _ ->
            requestMoreItems()
        }
```

But it doesn't seem to do anything at all,  ```requestMoreItems()``` is never executed. Which one is the callback that will be executed when loading more items?

**Comment by dkzwm** [comment]
@mradzinski  OnRefreshListener is the callback when the refreshing/loadingMore has triggered. The param `isRefresh` when in loading more it will be `false`;

**Comment by mradzinski** [comment]
Oh, I was calling the wrong method then. Working fine now! I'll close this issue. Cheers and thanks!

**Comment by dkzwm** [comment]
@mradzinski  You are welcome! If you have any questions, please feel free to ask questions. Thx!
