### ISSUE TITLE
关于上拉回弹效果的疑问

### ISSUE THREAD

**Issue by pengjunhong** [dkzwm/SmoothRefreshLayout#19]
如果有这样一个场景：在一个列表中，我只设置下拉刷新，但是不设置上拉加载，在列表滑动到底部时，继续上拉会有回弹的效果。

**Comment by pengjunhong** [comment]
上面的问题在看源码，已处理好了，初步感觉控件挺不错，想要使用到自己的封装的控件中，不知道作者有没有群或者怎样能联系作者，以后遇到问题，能够及时反馈。

**Comment by dkzwm** [comment]
@pengjunhong  可以看下Demo中的TestBaseRecyclerViewAdapterActivity的效果是你的需求吗？你的意思是列表不可能有新数据添加到列表尾部，想列表到底仍可以继续上拉？

**Comment by dkzwm** [comment]
你直接开Issue就可以了，我一般都能收到提醒

**Comment by pengjunhong** [comment]
@dkzwm 嗯 是的 列表到底仍可以继续上拉，只要有回弹效果就好了

**Comment by dkzwm** [comment]
参考TestOverScrollActivity   
```
        refreshLayout.setDisableLoadMore(false);
        refreshLayout.setDisablePerformLoadMore(true);
```

**Comment by pjh520** [comment]
嗯，已经处理好了。。

**Comment by pengjunhong** [comment]
嗯 已经处理好了
