### ISSUE TITLE
下来头部放大

### ISSUE THREAD

**Issue by s3hengwu** [dkzwm/SmoothRefreshLayout#20]
大神，问一下CoordinatorLayout的demo.
可以实现头部图片下拉的时候图片变大的效果吗？类似qq空间

**Comment by dkzwm** [comment]
@s3hengwu  本库无法实现嵌套CoordinatorLayout下拉图片放大效果。但我看QQ空间的效果实际上没有下拉刷新的，只有PULL-ZOOM效果，因为一般情况下2者是互斥的，即使都存在对滑动事件的处理分发也比较复杂容易出现错误，QQ空间的做法是只要拉到最大距离就刷新，这种效果修改下PULL-ZOOM相关类库的代码就能实现。如果只需要PULL-ZOOM这类效果是有很多库的，关键字搜索Pull zoom 就可以了。
