### ISSUE TITLE
请看下面链接，不知道是不是支持这样的

### ISSUE THREAD

**Issue by pengjunhong** [dkzwm/SmoothRefreshLayout#22]
@dkzwm 

https://github.com/scwang90/SmartRefreshLayout/blob/master/art/md_smart.md

![1](https://user-images.githubusercontent.com/18617995/30247423-f19c5b14-9646-11e7-8890-ee96655dcdab.png)

**Comment by dkzwm** [comment]
@pengjunhong  本库和SmartRefreshLayout查找TargetView逻辑上不一样，默认SmartRefreshLayout是自动搜索可滚动视图同时支持手动制定视图，本库相当于只支持手动制定（除SmartRefreshLayout外基本都是手动制定）。这是SmartRefreshLayout的一大特性，也是SmartRefreshLayout的优势。本库对内部视图侵入做到最小化，目的是将控制权交给使用者，提高效率。当然如果觉得本库使用麻烦，推荐使用SmartRefreshLayout。毕竟该库的用户很多，作者也在持续维护。就看用户的需求是怎么样的。

**Comment by dkzwm** [comment]
@pengjunhong 如果是说SmartRefreshLayout的另一特性，即根据触摸点查找顶层视图作为TargetView。本库也无此功能。因为本库对TargetView没有多少侵入，大多数情况并不关心TargetView是什么视图。本库主要注重效率和内存使用，以最少的资源兼顾丰富的功能去解决刷新痛点是本库的目的。

**Comment by pengjunhong** [comment]
@dkzwm 嗯嗯，我现在做的也只是怕以后会有这样的需求，想要搞个扩展性良好的刷新库。SmartRefreshLayout也有它的不足，不然我也不会研究别的刷新库，你的这个开源库是我找这么久，最适合我的了，还有个就是刚刚上面提到的效果，已经使用你的库实现了。还不错。

**Comment by dkzwm** [comment]
@pengjunhong  能帮到你就好，谢谢
