### ISSUE TITLE
升级1.4.6后recyclerview的惯性滑动没了

### ISSUE THREAD

**Issue by LambdaV5** [dkzwm/SmoothRefreshLayout#23]

**Comment by dkzwm** [comment]
@LambdaV5  Demo中的TestBaseRecyclerViewAdapterActivity的测试是有越界回弹的，是否是配置出了问题

**Comment by LambdaV5** [comment]
不是越界回弹，是你滑动很快的时候依然只能滑动一小段距离

**Comment by dkzwm** [comment]
@LambdaV5 你的意思是刷新视图可见情况下，用力滑动没有传递惯性，感觉加速动作被打断？  这个是为了避免惯性移动情况下导致内部视图滑动了但刷新视图未完全隐藏做的暂时性权衡。后面抽空我会做下实现解决这个问题

**Comment by LambdaV5** [comment]
刷新视图不可见，此时刷新事务已经完成

**Comment by dkzwm** [comment]
@LambdaV5 不好意思，麻烦重写下onNestedPreFling 
修改代码如下
```
        if (isEnabledOverScroll())
            return onFling(velocityX, -velocityY) || dispatchNestedPreFling(velocityX, velocityY);
        else return dispatchNestedPreFling(velocityX, velocityY);
```

**Comment by LambdaV5** [comment]
没关系，你这么快回复我已经很感动啦，敢问你搞嵌套滚动这块摸了多久啦

**Comment by dkzwm** [comment]
@LambdaV5  没多久吧。你看下应该修复了，没问题，我今天会发个版本，顺便带上一点新的特性。如果还有问题，我这边仔细查找下原因

**Comment by LambdaV5** [comment]
onFling(velocityX, -velocityY)这个返回值是void

**Comment by dkzwm** [comment]
@LambdaV5  1.4.6版本之前是void，1.4.6版本合并了嵌套滚动的惯性代码，onFling返回是boolean

**Comment by LambdaV5** [comment]
ok啦

**Comment by dkzwm** [comment]
@LambdaV5 逻辑写反了，Sorry!
```
        if (isEnabledOverScroll())
            return !onFling(velocityX, -velocityY) || dispatchNestedPreFling(velocityX, velocityY);
        else return dispatchNestedPreFling(velocityX, velocityY);
```
