### ISSUE TITLE
QQWebStyle 嵌套XWalkWebView，手势和webView冲突

### ISSUE THREAD

**Issue by fairytale110** [dkzwm/SmoothRefreshLayout#24]
web内容超过一屏，上滑没问题，但是上滑后下滑手势，就没法滚动页面了，被你的这个layout拦截了，，，，还有就是刚进入这个activity时马上下拉能看到头部内容，但是加载完页面后下拉，头部就是一片黑，，，，
`
I/ViewRootImpl: onBatchedInputEventPending @@@@
`
`
E/ViewRootImpl: lhf  @@ scheduleConsumeBatchedInput: mConsumeBatchedInputScheduled = true,mPendingInputEventHead = null,mTraversalScheduled=false, this = ViewRoot{1d9d6565 xx.com/net.xxx.ui.xx.xxActivity,ident = 3}
`

**Comment by dkzwm** [comment]
@fairytale110  你好，能提供下DEMO吗，这边未测试过XWalkView.

**Comment by dkzwm** [comment]
@fairytale110  分支issue24的代码已上传，你看下是否有解决你的问题。关于你的上滑后下滑手势无法滚动页面，我测试没这个问题呢，是我没懂你的意思还是你设置有误？关于一片黑是由于`XWalkView`内部是使用`SurfaceView`实现的，如果不重布局，`SurfaceView`的绘制区域默认还是那块，估计应该是`XWalkView`的BUG。直接在自定义刷新视图内强制重新布局就行了。你可以检下来看下

**Comment by dkzwm** [comment]
@fairytale110 1.4.7.1版本发布了，你说的“关于你的上滑后下滑手势无法滚动页面”的问题应该修复了。

**Comment by fairytale110** [comment]
你上面说这个解决了，谢谢：）
XWalkView 下拉黑色问题很尴尬，确实是它自己的BUG，但是项目需要，哎，尴尬
