### ISSUE TITLE
recyclerView内容未满屏，上拉加载更多手势处理问题

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#25]
recyclerView内容未满屏，上拉加载更多手势处理问题

**Comment by dkzwm** [comment]
@LongAgoLong  您更新下1.4.7.2版本，这边应该修复了，如果还有问题麻烦告知下，不好意思。

**Comment by LongAgoLong** [comment]
问题暂时没有出现，但是，之前说的那个滚动到顶部，刷新头部会出现的问题又出现了。setEnableOverScroll(false)已关闭

**Comment by LongAgoLong** [comment]
在内容为listview的时候

**Comment by dkzwm** [comment]
@LongAgoLong 1.4.7.3版本应该修复了。

**Comment by LongAgoLong** [comment]
辛苦了

**Comment by dkzwm** [comment]
好的
