### ISSUE TITLE
还是上拉加载的判断

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#26]
当LayoutManager为GridLayoutManager且不满屏或者使用GridView的时候，上拉加载判断不正确。

**Comment by dkzwm** [comment]
@LongAgoLong  自动加载更多？上拉加载和满不满屏没什么关系啊

**Comment by LongAgoLong** [comment]
不是自动，是手势滑动上拉加载，使用GridView的时候就是一直抖动，无法上滑。RecyclerView使用GridLayoutManager的时候，未满屏偶现无法上拉，变成回弹了

**Comment by dkzwm** [comment]
嵌套？内部有滚动视图？

**Comment by LongAgoLong** [comment]
并没有嵌套，就是一个Gridview

**Comment by dkzwm** [comment]
具体布局是怎样的呢，这边测试没有发现问题。有DEMO吗？

**Comment by LongAgoLong** [comment]
我再试试，看看能不能重现

**Comment by dkzwm** [comment]
@LongAgoLong  请问你那边重现了吗？是否是本库的BUG还是其他问题？如果有问题，你看能否提供DEMO或者DEBUG日志，这边看下是什么问题。

**Comment by LongAgoLong** [comment]
把SelectableRoundedImageView换成ImageView后就没出现过了，怀疑是glide和SelectableRoundedImageView搭配使用的问题，抱歉，打扰了。

**Comment by dkzwm** [comment]
额，好的。这边后面测试下使用SelectableRoundedImageView配合Glide 看是否有触摸处理上的问题。

**Comment by dkzwm** [comment]
@LongAgoLong 这边测试了SelectableRoundedImageView结合Glide在未满屏幕情况下的情况，没有发现问题。可能是其他原因。你说你解决了，那这个Issue我先关闭了。如果后面发现问题，请再反馈给我。谢谢！
