### ISSUE TITLE
TestBaseRecyclerViewAdapterActivity例子里怎么设置footview的style?

### ISSUE THREAD

**Issue by tmxd09887** [dkzwm/SmoothRefreshLayout#29]
试过setFooterView，无法生效，后来发现必须setDisableLoadMore(false);才能定义footview，但是出现了两个footview同时加载loading,原来那个loading无法去掉。

以下是部分代码
`mRefreshLayout.setDisableLoadMore(false);
MaterialFooter footer=new MaterialFooter(context);
footer.setProgressBarColors(new int[]{Color.RED, Color.BLUE, Color.GREEN, Color.BLACK});
mRefreshLayout.setFooterView(footer);
mRefreshLayout.setDisableRefresh(true);`
基本是直接用的https://github.com/dkzwm/SmoothRefreshLayout/issues/27 里的代码

**Comment by dkzwm** [comment]
@tmxd09887 TestBaseRecyclerViewAdapterActivity的例子是用来演示如何配合BaseRecyclerViewAdapter提供的加载更多能力进行刷新。你如果想使用本库的上拉加载更多能力请去掉BaseRecyclerViewAdapter所提供能力相关的代码即去掉Adapter的`setOnLoadMoreListener`代码即可。

**Comment by tmxd09887** [comment]
谢谢

mRefreshLayout.setOnRefreshListener同时监听下拉和上拉？

好像是if (isRefresh) 来判断是否上拉还是下拉？

文档里没看到。试了下，应该是这样。

**Comment by dkzwm** [comment]
@tmxd09887 是的
