### ISSUE TITLE
自定义头部后还没滚动到底部就触发了加载更多

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#3]
自定义头部后还没滚动到底部就触发了加载更多
up主可以联系我，我把demo给你，你看一下

**Comment by dkzwm** [comment]
你发Demo到dkzwm@hotmail.com 我抽空给看下是否是库的BUG

**Comment by dkzwm** [comment]
是个检测Bug,我刚才修正了，会发布一个修复版本，Thx @LongAgoLong !
