### ISSUE TITLE
ClassicFooter和ClassicHeader怎么定义字体颜色？

### ISSUE THREAD

**Issue by tmxd09887** [dkzwm/SmoothRefreshLayout#30]
<me.dkzwm.widget.srl.extra.header.ClassicHeader
        android:id="@+id/classicHeader_with_listView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/colorPrimary"
        app:sr_style="style_scale"/>

好像只能定义背景？

谢谢

**Comment by dkzwm** [comment]
@tmxd09887  setTitleTextColor&&setLastUpdateTextColor

**Comment by tmxd09887** [comment]
看了下ClassicFooter没有这两个属性
ClassicHeader有

**Comment by dkzwm** [comment]
@tmxd09887 我等下会发个版本，会带点BUG修正和新特性，你依赖下就有了

**Comment by dkzwm** [comment]
@tmxd09887  1.5.0.2发布了，你可以依赖看下。谢谢

**Comment by tmxd09887** [comment]
非常感谢
