### ISSUE TITLE
横向嵌套viewpager，当处于刷新中，这时左右滑动Viewpager感觉体验不是很好滑一下卡一下

### ISSUE THREAD

**Issue by williamsim** [dkzwm/SmoothRefreshLayout#31]

**Comment by dkzwm** [comment]
@williamsim  你的布局是怎样的，是SmoothRefreshLayout嵌套ViewPager？是否开启 `setDisableWhenAnotherDirectionMove`. 你可以下载Demo到你的手机上，测试下是否Demo也存在你说的问题，如果没有的话，就应该是你的配置或者布局嵌套问题。

**Comment by dkzwm** [comment]
@williamsim  你可以把你的配置和布局代码贴出来，这边好方便排查问题，谢谢。

**Comment by dkzwm** [comment]
@williamsim  请问你的问题解决了吗？
