### ISSUE TITLE
TwoLevelSmoothRefreshLayout  无法正常滚动问题，楼主快明查

### ISSUE THREAD

**Issue by ManBali** [dkzwm/SmoothRefreshLayout#32]
<android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:sr_enable_two_level_refresh="true">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout>
    </android.support.design.widget.CoordinatorLayout>

这种情况下，可以正常的滚动RecyclerView 的内容 

但在外部包一层的时候，无法正常的滚动.

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout
            android:id="@+id/refreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:sr_enable_two_level_refresh="true">
            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recyclerView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </RelativeLayout>
        </me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout>
    </android.support.design.widget.CoordinatorLayout>
</layout>

楼主快明查啊

**Comment by dkzwm** [comment]
需要使用 setLoadMoreScrollTargetView 方法，设置recyclerView为滚动内容视图

**Comment by dkzwm** [comment]
@wsf5918  请问使用`setLoadMoreScrollTargetView`方法了吗？问题解决了吗？如果解决了麻烦关闭下Issue.谢谢
