### ISSUE TITLE
reset方法中getHandler().removeCallbacksAndMessages(null)导致的问题

### ISSUE THREAD

**Issue by kasogg** [dkzwm/SmoothRefreshLayout#35]
点击tab切换viewpager的时候发现ripple drawable只执行了一半，后来发现是onDetachedFromWindow->onDestroy()->reset()方法中getHandler().removeCallbacksAndMessages(null)移除了所有的callback导致的

**Comment by dkzwm** [comment]
@kasogg 设计目的主要是担心使用者不规范使用造成内存泄露，其实默认移除用到过的消息即可。最快速的方法你重载下`reset`方法吧。这边考量下是否只移除本库用过的消息。

**Comment by dkzwm** [comment]
@kasogg  你更新下`1.5.1.1`版本，应该已经修复了。如果没问题，麻烦你关闭下issue。谢谢

**Comment by kasogg** [comment]
修复的好快，已解决，非常感谢！
