### ISSUE TITLE
当手指在recyclerview上按下不释放往上滑动时(此时recyclerview顶部和AppBarLayout底部持平)AppBarLayout并不会先往上滑动,如果是快速滑动时AppBarLayout会先往上滑动

### ISSUE THREAD

**Issue by LambdaV5** [dkzwm/SmoothRefreshLayout#37]
<SmoothRefreshLayout
android:id="@+id/content_view"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:fitsSystemWindows="true">

<android.support.design.widget.CoordinatorLayout
android:layout_width="match_parent"
android:layout_height="match_parent"
>

<android.support.design.widget.AppBarLayout
android:id="@+id/app_bar_layout"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:background="@null"
app:elevation="0dp"
>

<android.support.design.widget.CollapsingToolbarLayout
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:background="@color/white"
android:clipChildren="false"
app:contentScrim="@color/half_white"
app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

<com.lambda.widget.BannerLayout
android:id="@+id/banner"
android:layout_width="match_parent"
android:layout_height="104dp"
android:scaleType="fitXY"
android:visibility="gone"
app:autoPlayDuration="5000"
app:indicatorPosition="centerBottom"
app:indicatorShape="oval"
app:indicatorSpace="3dp"
app:indicatorStyle="dot"
app:indicatorVerticalMargin="2dp"
app:layout_collapseMode="parallax"
app:layout_collapseParallaxMultiplier="0.5"
app:scrollDuration="1100"
app:selectedIndicatorColor="@color/white"
app:selectedIndicatorHeight="7dp"
app:selectedIndicatorWidth="7dp"
app:unSelectedIndicatorColor="@color/half_white"
app:unSelectedIndicatorHeight="7dp"
app:unSelectedIndicatorWidth="7dp"/>
</android.support.design.widget.CollapsingToolbarLayout>
        

<View
android:layout_width="match_parent"
android:layout_height="1px"
android:background="@color/divider"/>

<com.ciwei.bgw.user.widget.MagicIndicatorEx
android:id="@+id/tab_pack"
android:layout_width="match_parent"
android:layout_height="40dp"
android:background="@color/white"
android:textSize="@dimen/sp_14"
app:indicatorColor="@color/colorPrimary"
app:indicatorHeight="2dp"
app:selectedTextColor="@color/colorPrimary"
app:unselectedTextColor="@color/light_gray_b"/>
</android.support.design.widget.AppBarLayout>

<android.support.v7.widget.RecyclerView
android:id="@+id/rv_pack"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:paddingBottom="44dp"
app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
</android.support.design.widget.CoordinatorLayout>
</SmoothRefreshLayout>

**Comment by dkzwm** [comment]
@LambdaV5  [TestNestedActivity](https://github.com/dkzwm/SmoothRefreshLayout/blob/master/app/src/main/java/me/dkzwm/widget/srl/sample/ui/TestNestedActivity.java)，按照这个这样配置的？

**Comment by dkzwm** [comment]
@LambdaV5  还有RecyclerView没有指定
```
        <android.support.v7.widget.RecyclerView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
```

**Comment by LambdaV5** [comment]
是的
 mBinding.appBarLayout.addOnOffsetChangedListener(
                (appBarLayout, verticalOffset) -> {
                    mOffset = verticalOffset;
                    mMinOffset = Math.min(mMinOffset, mOffset);
                });
        mBinding.contentView.setOnChildNotYetInEdgeCannotMoveHeaderCallBack((parent, child, header)
                -> parent.isInStartPosition() && (mOffset != 0 || ScrollCompat.canChildScrollUp
                (mRecyclerView)));
        mBinding.contentView.setOnChildNotYetInEdgeCannotMoveFooterCallBack((parent, child, footer)
                -> mMinOffset != mOffset || ScrollCompat.canChildScrollDown(mRecyclerView));

**Comment by dkzwm** [comment]
@LambdaV5  加上`app:layout_behavior="@string/appbar_scrolling_view_behavior"` 是否可以了？

**Comment by LambdaV5** [comment]
阔以了,thanks,之前没注意

**Comment by dkzwm** [comment]
@LambdaV5  那麻烦你关闭下issue，谢谢
