### ISSUE TITLE
关于和BaseRecyclerViewAdapter嵌套的问题

### ISSUE THREAD

**Issue by getglory** [dkzwm/SmoothRefreshLayout#38]
当数据没有加载满一页时，会自动触发BaseRecyclerViewAdapter加载更多的监听。
需要在数据完成之后，调用
mRefreshLayout.refreshComplete();
mQuickAdapter.disableLoadMoreIfNotFullPage();
另外能设置第一次初始化时不自动下拉刷新吗

**Comment by dkzwm** [comment]
@getglory 
1.未满一屏BRVA会自动触发加载更多，必须配置`disableLoadMoreIfNotFullPage()`这是本库无能无力的，毕竟加载更多使用的是BRVA提供的能力，
2.自动下拉刷新是你使用了`autoRefresh()`方法，你不使用该方法就不会触发自动刷新。

**Comment by getglory** [comment]
@dkzwm 好的谢谢

**Comment by dkzwm** [comment]
@getglory  不用，有问题再反馈。这边关闭该Issue了。
