### ISSUE TITLE
调用autoRefresh()的同时如何让scroll也到顶部

### ISSUE THREAD

**Issue by 454464335** [dkzwm/SmoothRefreshLayout#39]
两个问题:
1:调用autoRefresh()主动刷新的同时如何让scroll也到顶部
2:如何监听滚动状态是已经滚动到到顶部还是底部
在OnUIPositionChangedListener中status值无论是在顶部还是在底部都返回1,无法判断

**Comment by dkzwm** [comment]
@454464335  
1:核心库没有提供能力让内部视图滚动到顶部，需要自定义，你可以看`develop`分支下的`ext-utils`包里的`QuickConfigAutoRefreshUtil`类，该类提供了具体实现（由于提供的工具得考虑很多情况，所以内部有对滚动视图做判断，代码会比较繁长）。你可以参考或者拷贝直接拿去用。后续考虑多种情况并测试后会发布`1.6.1.3`版本,这个版本会将这个工具带入`ext-utils`包中。
2:关于监听滚动状态是否在顶部还是底部，2种方法，一种直接判断内部视图是否再顶部或者底部就是`isChildNotYetInEdgeCannotMoveHeader`和`isChildNotYetInEdgeCannotMoveFooter` 2个方法的实现。第二种设置`OnUIPositionChangedListener `，记录`IIndicator` 返回的当前移动状态和上次的移动状态进行比较,例如上次移动`getMovingStatus`的状态是`MOVING_HEADER`，这次为`MOVING_CONTENT`,则表示已经回滚到顶部。当然最好是使用第一种判断。`QuickConfigAutoRefreshUtil`就是结合多种情况进行的组合判断。
