### ISSUE TITLE
二级刷新 TwoLevelSmoothRefreshLayout中放了Listview 滑动事件冲突

### ISSUE THREAD

**Issue by Doraemonhub** [dkzwm/SmoothRefreshLayout#41]
listview无法滑动了，只要有下拉操作触发的就是 下拉刷新？

**Comment by Doraemonhub** [comment]
恳请作者帮忙解答一下

**Comment by dkzwm** [comment]
@Doraemonhub  朋友，不好意思。今天公司事情很多。得晚上回去我才有时间进行测试。看是否有BUG。实在抱歉。

**Comment by Doraemonhub** [comment]
好的，好的 辛苦您了！

**Comment by dkzwm** [comment]
@Doraemonhub 能否贴下你的布局呢，我这边直接更换内部视图为ListView，可以移动，也可以触发二级刷新。是否有嵌套？

**Comment by Doraemonhub** [comment]
就是在二级刷新的demo中 我替换了listview也不可用啊，没有什么嵌套啊

**Comment by dkzwm** [comment]
@Doraemonhub 你描述的情况是说，只要下拉就会把刷新视图拉出来，还是说下拉只能触发刷新，无法触发二级刷新？最好能贴下你的布局。你是否是直接替换了我DEMO中二级刷新界面里的TextView?.外面套的FrameLayout你没有去掉？如果是这种嵌套，请如下设置，滚动边界判断应以ListView的边界为准
```
   mRefreshLayout.setOnChildNotYetInEdgeCannotMoveHeaderCallBack(new SmoothRefreshLayout
                .OnChildNotYetInEdgeCannotMoveHeaderCallBack() {
            @Override
            public boolean isChildNotYetInEdgeCannotMoveHeader(SmoothRefreshLayout parent,
                                                               @Nullable View child,
                                                               @Nullable IRefreshView header) {
                return ScrollCompat.canChildScrollUp(mListView);
            }
        });
        mRefreshLayout.setOnChildNotYetInEdgeCannotMoveFooterCallBack(new SmoothRefreshLayout
                .OnChildNotYetInEdgeCannotMoveFooterCallBack() {
            @Override
            public boolean isChildNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout parent,
                                                               @Nullable View child,
                                                               @Nullable IRefreshView footer) {
                return ScrollCompat.canChildScrollDown(mListView);
            }
        });
```

**Comment by Doraemonhub** [comment]
嗯  好的，本来想给您贴下代码 因为这两天有事不在家，我回去了先按照您说的试一下，有问题给您说

**Comment by dkzwm** [comment]
@Doraemonhub  老铁，有问题再反馈就是。PS:您这个词太沉重了，233333333。

**Comment by Doraemonhub** [comment]
布局如下：
<me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/two_level_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/bg_content"
    android:orientation="vertical"
    app:sr_enable_two_level_refresh="true">

    <LinearLayout
        android:id="@+id/ll_today"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/bg_content"
        android:orientation="vertical">

        <include layout="@layout/include_headbar_immersion" />

        <View
            android:layout_width="match_parent"
            android:layout_height="0.5dp"
            android:background="@color/gray_pressed" />

        <FrameLayout
            android:layout_width="fill_parent"
            android:layout_height="fill_parent">

            <ListView
                android:id="@+id/list_explore"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                android:cacheColorHint="@android:color/transparent"
                android:choiceMode="singleChoice"
                android:divider="@null"
                android:drawSelectorOnTop="true"
                android:fadingEdge="none"
                android:footerDividersEnabled="false"
                android:headerDividersEnabled="false"
                android:listSelector="@color/transparent"
                android:scrollbarStyle="outsideOverlay"
                android:scrollbars="none"
                android:scrollingCache="true"
                android:smoothScrollbar="true" />

            <include
                layout="@layout/emptyview"
                android:visibility="gone" />

            <ImageView
                android:id="@+id/img_newcustomer"
                android:layout_width="@dimen/dp_150"
                android:layout_height="@dimen/dp_150"
                android:layout_gravity="bottom|right"
                android:layout_marginBottom="@dimen/dp_180"
                android:layout_marginRight="@dimen/dp_36"
                android:src="@mipmap/ic_cloudo" />
        </FrameLayout>
    </LinearLayout>
</me.dkzwm.widget.srl.TwoLevelSmoothRefreshLayout>
现在的问题是无法触发一级刷新，只要下拉就只能触发二级刷新

**Comment by dkzwm** [comment]
@Doraemonhub 应该是配置的触发二级刷新高度低于了一级刷新高度,Demo中的简单自定义二级刷新头部的高度是`match_parent`的。你可以检查下是否是高度比设置有误。下面的Demo中的配置代码：
```
        //设置触发刷新的头部高度比
        mRefreshLayout.setRatioOfHeaderHeightToRefresh(.12f);
        //设置滚动到保持二级刷新的头部位置的时长
        mRefreshLayout.setDurationOfBackToKeepTwoLevelHeaderViewPosition(1000);
        //设置关闭二级刷新头部回滚到起始位置的时长
        mRefreshLayout.setDurationToCloseTwoLevelHeader(0);
        //设置二级刷新时保持头部的Offset(占头部的高度比)
        mRefreshLayout.setOffsetRatioToKeepTwoLevelHeaderWhileLoading(1f);
        //设置触发提示二级刷新的头部高度比
        mRefreshLayout.setRatioOfHeaderHeightToHintTwoLevelRefresh(.15f);
        //设置触发二级刷新的头部高度比
        mRefreshLayout.setRatioOfHeaderHeightToTwoLevelRefresh(.25f);
```

**Comment by Doraemonhub** [comment]
我按照你上边给我说的那个  “滚动边界判断应以ListView的边界为准” 这个可以了

**Comment by Doraemonhub** [comment]
辛苦了！！
