### ISSUE TITLE
twoLevel刷新完成后跳转问题

### ISSUE THREAD

**Issue by Doraemonhub** [dkzwm/SmoothRefreshLayout#42]
@Override
            public void onTwoLevelRefreshBegin() {
                twoLevelRefreshLayout.setEnabledInterceptEventWhileLoading(true);
                myHandler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        twoLevelRefreshLayout.refreshComplete();
                    }
                }, 2000);
            }
按照demo中的代码，二级页面刷新完成后，在二级页面中停留2s ，然后  twoLevelRefreshLayout.refreshComplete(); 跳回到一级页面中，现在需要在刷新完成后跳入一个新的页面，

    @Override
            public void onRefreshComplete(boolean isSuccessful) {
                twoLevelRefreshLayout.setEnabledInterceptEventWhileLoading(false);
                SecondLevelActivity_.intent(getActivity()).start();
            }

中间的问题是，在进入二级界面之后，延迟两秒，会先跳到一级页面中然后再跳转到我指定的SecondLevelActivity中，怎么设置能直接 从二级页面中跳入指定的SecondLevelActivity中呢？

**Comment by dkzwm** [comment]
@Doraemonhub  你的意思是当二级刷新开始并让视图滚动铺满屏幕的一瞬间打开SecondLevelActivity？
这种你需要设置`OnUIPositionChangedListener`,判断 `IIndicator`中记录的`getCurrentPos`是否等于二级刷新视图的高度，等于即可触发跳转，跳转的SecondLevelActivity可以设置成透明主题并去掉过场动画。

**Comment by dkzwm** [comment]
@Doraemonhub 在`OnUIPositionChangedListener `中最好进行下组合判断，判断下当前状态是否处于二级刷新中且`indicator.getCurrentPos()==mRefreshLayout.getHeaderHeight()`且`status==Iindicator.MOVING_HEADER`。

**Comment by Doraemonhub** [comment]
好的，我试一下！
