### ISSUE TITLE
Is it possible to use this library with Lottie

### ISSUE THREAD

**Issue by mradzinski** [dkzwm/SmoothRefreshLayout#44]
Let's say I want to play a Lottie file while refreshing. Is this library capable of it? (starting, looping, stopping it, etc) 

In case you don't know about Lottie: https://github.com/airbnb/lottie

Thanks

**Comment by dkzwm** [comment]
@mradzinski Hi, I didn't use Lottie, I search related information.
In theory, you can customize the layout and LottieAnimationView nested inside, according to the callback provided by the IRefreshView interface to control the animation, it should be feasible.
If you don't know how to customize, I'll take a time to write a DEMO here！

**Comment by mradzinski** [comment]
As far as I saw the IRefreshView interface should provide me of enough callbacks to start and end the animation. My only concern is the measuring and if there's some way to figure out the progress (displacement), in other words to know how much the user has revealed of the custom view. It would be nice to be able to actually control the animation by the amount of the custom view that is visible to the user (lottie allows this by setting the animation progress, so all I need is a way to know how much the user has revealed of the custom view).

**Comment by dkzwm** [comment]
@mradzinski  When the UI pos changed, It will be triggered the `onRefreshPositionChanged` callback.
In SRL, `IIndicator` is the most important interface, you can use callbacks provided by the `IIndicator` to get more information, such as current pos, current percent, last pos, etc...

**Comment by dkzwm** [comment]
In theory, the calling sequence is `onRefreshPrepare`(Prepared)-> `onRefreshPositionChanged`(Get the current progress to customize the ani)->...->`onRefreshBegin`(Refreshing, looping ani)->`onRefreshComplete`(Completed, stop the ani)->`onRefreshPositionChanged`(Rolling back)->...->`onReset`(Done)

**Comment by mradzinski** [comment]
Will `onRefreshPositionChanged` be called after `onRefreshComplete` even if that refresh was successful? If thats the case, is there a way to know when `onRefreshPositionChanged` is being triggered by the user and not by a rollback/refresh completed?

**Comment by dkzwm** [comment]
@mradzinski  `onRefreshPositionChanged(SmoothRefreshLayout layout, byte status, T indicator)` The param `status` is provided to determine what state the current SRL is in. 
```
    public static final byte SR_STATUS_INIT = 1;
    public static final byte SR_STATUS_PREPARE = 2;
    public static final byte SR_STATUS_REFRESHING = 3;
    public static final byte SR_STATUS_LOADING_MORE = 4;
    public static final byte SR_STATUS_COMPLETE = 5;
```

**Comment by mradzinski** [comment]
Awesome, I think I have all the information I need. Thanks a ton man! I'll close the issue. If at any point I hit some wall I'll let you know.

Cheers and thanks again for your help and superb library! :)

**Comment by dkzwm** [comment]
Well, I hope it can help you. It's my pleasure! :)
