### ISSUE TITLE
关于使用第三方EmptyView

### ISSUE THREAD

**Issue by jyh149129** [dkzwm/SmoothRefreshLayout#46]
引入了第三方EmptyView来显示空布局及错误布局，项目地址：https://github.com/czy1121/loadinglayout
具体布局如下：
`<me.dkzwm.widget.srl.MaterialSmoothRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/lvRefLayer"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:sr_content="@id/lvList">
    <ezy.ui.layout.LoadingLayout
        android:id="@+id/emptyLoading"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/lvList"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never" />
    </ezy.ui.layout.LoadingLayout>
</me.dkzwm.widget.srl.MaterialSmoothRefreshLayout>`

java 代码：
`  lvRefLayer.materialStyle();
   lvRefLayer.setDisableRefresh(false);
   lvRefLayer.setDisableLoadMore(false);
   lvRefLayer.setEnableAutoLoadMore(true);
   lvRefLayer.setEnableAutoRefresh(true);
   lvRefLayer.setDisableLoadMoreWhenContentNotFull(true);`

但引起下拉刷新及上拉无法使用，表现为下拉及上拉都没有显示刷新动画

**Comment by dkzwm** [comment]
@jyh149129  `app:sr_content `现在的版本只支持指定为SRL内顶层视图，需要代码指定下
```
   mRefreshLayout.setOnHeaderEdgeDetectCallBack(new SmoothRefreshLayout.OnHeaderEdgeDetectCallBack() {
            @Override
            public boolean isNotYetInEdgeCannotMoveHeader(SmoothRefreshLayout parent,
                                                          @Nullable View child,
                                                          @Nullable IRefreshView header) {
                return ScrollCompat.canChildScrollUp(mRecyclerView);
            }
        });
        mRefreshLayout.setOnFooterEdgeDetectCallBack(new SmoothRefreshLayout.OnFooterEdgeDetectCallBack() {
            @Override
            public boolean isNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout parent,
                                                          @Nullable View child,
                                                          @Nullable IRefreshView footer) {
                return ScrollCompat.canChildScrollDown(mRecyclerView);
            }
        });
mRefreshLayout.setLoadMoreScrollTargetView(mRecyclerView);
```

**Comment by jyh149129** [comment]
谢谢这么快就回复，我试下再反馈

**Comment by jyh149129** [comment]
谢谢，正常了
