### ISSUE TITLE
RecyclerView与CoordinatorLayout一起嵌套使用

### ISSUE THREAD

**Issue by Wensibob** [dkzwm/SmoothRefreshLayout#47]
RecyclerView与CoordinatorLayout一起嵌套使用时，当从下往上华东列表时没有问题，当时当AppBarLayout完全折叠起来时，从上往下拉列表，这个时候是AppBarLayout先展开之后再展开列表，这个逻辑是有问题的，正常来说是要先把列表展开，然后再展开AppBarLayout，之后才执行刷新的操作，建议按照酷安APP的效果：
![目前的效果](https://user-images.githubusercontent.com/24890876/39615166-478d29e4-4fa7-11e8-8a00-7a16da541f95.png)
![酷安APP的效果](https://user-images.githubusercontent.com/24890876/39615173-51bae6b8-4fa7-11e8-97df-6bff816cb1a4.jpg)

**Comment by dkzwm** [comment]
@Wensibob  不好意思，才看到邮件。这个效果是需要更改`CollapsingToolbarLayout`的`layout_scrollFlags`来实现的，我的Demo中的Flag是`scroll|enterAlways|exitUntilCollapsed`，要实现你的效果只需要去掉`enterAlways`改成`scroll|exitUntilCollapsed`就可以了。
