### ISSUE TITLE
请教一下为什么我copy来的demo好用，自己引的库就有问题？

### ISSUE THREAD

**Issue by mumu1990** [dkzwm/SmoothRefreshLayout#48]
请教一下为什么我copy来的demo好用，自己引的库就有问题？
我用的是多方布局那个，侧拉加载详情的效果。出现的问题是侧拉刷新的时候，viewPager会随着手指移动而变窄

**Comment by dkzwm** [comment]
@mumu1990  你是否引用的1.6.4版本，这个版本横向刷新有个BUG，我错误的设置了内容视图的偏移，因为横向刷新用的比较少，暂时就没有发新版本。不好意思。
这边修复这个问题你可以新建个类重写下`HorizontalSmoothRefreshLayout`的`offsetChild`方法。将
```
''' '''
mTargetView.offsetTopAndBottom(change)
''' '''
```
这段修改为
```
mTargetView.offsetLeftAndRight(change)
```
看下是否是这个问题导致的。

**Comment by LiHexiang** [comment]
解决了  谢谢大神及时回复

**Comment by dkzwm** [comment]
好的，这边修复的版本我发布了，你可以直接使用新版。
