### ISSUE TITLE
测试拉伸收缩效果有问

### ISSUE THREAD

**Issue by ghost** [dkzwm/SmoothRefreshLayout#49]
测试拉伸收缩效果（1.6.2版本添加）可以加上 下拉刷新以及加载更多吗？看了demo，没找到相关示例！！！还有，为什么我设置了autoRefresh(false);一进去还是会自动刷新呢?

**Comment by dkzwm** [comment]
@fcscr126608  不好意思，才看到邮件。
1.下拉刷新和拉伸收缩理论上是不可能同时支持的，例如，当内部视图到顶部时，再下拉是应该触发拉伸效果还是下拉刷新效果呢，本质上就是冲突的。
2.关于autoRefresh的问题，如果是拉伸模式下，理论上调用自动刷新是不能有效果的，这里库里的判断没有处理好。
如果是支持下拉刷新/加载更多的同时支持横向的拉伸效果，理论上是没问题的。

**Comment by ghost** [comment]
@dkzwm 谢谢。确实是不能同时有拉伸效果和下拉刷新共存。
![image](https://user-images.githubusercontent.com/35981460/40869028-c57fcc84-6646-11e8-8910-23abbfee20d2.png)
这里的autoRefresh 设置为false，但是一进页面还是会自动刷新？？？是不是设置错啦？

**Comment by dkzwm** [comment]
的确有点问题，如果是收缩模式调用autoRefresh是不应该有效果的。我不清楚你的意思是否是想触发一次自动收缩动画？如果是，那暂时还不支持这么做

**Comment by ghost** [comment]
你好。谢谢你的回答。我的意思是在使用MaterialSmoothRefreshLayout的时候，发现autoRefresh怎么设置都还是会自动刷新。我用的是demo中的WithRecyclerViewActivity进行测试的。现在是想禁止自动下拉刷新！感谢！

**Comment by dkzwm** [comment]
autoRefresh是主动触发一次自动刷新的意思，后面的参数是控制是`atOnce`否立即触发刷新回调，`smooth`是否使用滚动动画过渡。直接不调用就不会触发刷新。

**Comment by ghost** [comment]
谢谢。原来是这个意思。已经解决，可以关闭了。感谢！
