### ISSUE TITLE
没有到底加载更多功能

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#5]
有autoRefresh方法，但是也应该有个autoLoadMore方法，这样监听滚动到底部调用这方法就可以实现到底自动加载更多

**Comment by dkzwm** [comment]
自动加载请使用Adapter实现，https://github.com/CymChad/BaseRecyclerViewAdapterHelper 这个项目就可以，LoadMore模式主要是提供给需要上拉加载更多的使用的，自动加载更多不适合在ViewGroup层进行实现.
滚动到底部自动加载本项目在实现上可参考 ：
mRefreshLayout.setEnableKeepRefreshView(true);
mRefreshLayout.setEnablePullToRefresh(true);
mRefreshLayout.setRatioOfFooterHeightToRefresh(0.01f);（具体比例看footer高度，如果高度为300 可设置为0.004f）;
这样如果滚动到底部且移动1个像素就会触发加载更多。但这样会改变头部刷新视图为移动到触发刷新位置就会触发刷新

**Comment by dkzwm** [comment]
mRefreshLayout.setOnUIPositionChangedListener(new SmoothRefreshLayout.OnUIPositionChangedListener() {
            @Override
            public void onChanged(byte status, IIndicator indicator) {
                if (indicator.getMovingStatus() == IIndicator.MOVING_HEADER) {
                    mRefreshLayout.setEnablePullToRefresh(false);
                } else {
                    mRefreshLayout.setEnablePullToRefresh(true);
                }
            }
        });
这样实现能实现头部视图为释放刷新，尾部视图为到触发位置自动加载。但这样不是很优雅

**Comment by LongAgoLong** [comment]
可不可以提供一个方法调起加载更多呢？然后可以自行在recyclerView或者listview之类的滚动中去做判断，滚动到底部调用方法就可以实现加载更多？

**Comment by dkzwm** [comment]
一种方法是使用Adapter实现,SmoothRefreshLayout使用Refresh模式进行操作;
另一种方法我后续提供出来，只要滚动到底部就会触发加载更多。
至于主动触发加载更多实现上会有很大的操作局限，因为触发加载更多的前提是视图滚动到底部，如果没有滚动到底部主动触发加载更多的效果很不好（交由使用者控制的话不可控）

**Comment by dkzwm** [comment]
新的特性 我已经添加了 自动加载更多和到底部自动加载更多 2个特性。请注意自动加载更多触发前提，否则体验很差。你可以Clone下来看下效果，没问题我会发布一个1.2.2版本到Maven
