### ISSUE TITLE
拉伸收缩效果有问题。

### ISSUE THREAD

**Issue by TJHello** [dkzwm/SmoothRefreshLayout#51]
当我使用了CoordinatorLayout{ AppBarLayout ，ViewPager{ Fragment { SmoothRefreshLayout{ HomeRecyclerView } }}}这样的布局的时候，如果数据过少，不满屏，拉伸收缩功能，会导致item拉伸变形。

**Comment by dkzwm** [comment]
你的意思是如果不满屏就禁用拉伸收缩功能？

**Comment by dkzwm** [comment]
@TJHello  麻烦你更新下1.6.4.3版本，触摸拖动下拉伸功能是有BUG

**Comment by dkzwm** [comment]
No feedback, so close this issue!
