### ISSUE TITLE
demo编译报错

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#52]
![qq 20180629091036](https://user-images.githubusercontent.com/16161738/42068466-c5ee5b7a-7b7e-11e8-8c38-017593380121.png)

**Comment by dkzwm** [comment]
@LongAgoLong  请问你的AS和Gradle版本是多少？我这里没出现过这种情况，`sr_style`这个xml属性是定义在`core`包下面的，是否有导入`core`包？我这边的AS是3.1.3，Gradle版本是4.4的。

**Comment by LongAgoLong** [comment]
as 3.0.1 gradle 4.4

**Comment by dkzwm** [comment]
@LongAgoLong  如果能升级就升级下，不行的话，你可以注释掉`sr_style`的代码，
将`ext-classic`->`res`->`values`->`attrs`->`AbsClassicRefreshView`内的属性注释掉，
将`ext-classic`->`java`->`me.dkzwm.widget.srl.extra.AbsClassicRefreshView`的55行到62行代码注释掉.即
```
       if (attrs != null) {
            final TypedArray arr = context.obtainStyledAttributes(attrs, R.styleable
                    .AbsClassicRefreshView, 0, 0);
            @RefreshViewStyle
            int style = arr.getInt(R.styleable.AbsClassicRefreshView_sr_style, mStyle);
            mStyle = style;
            arr.recycle();
        }
```
这样就行了。希望能帮到你
