### ISSUE TITLE
仿原生的这种布局支持把recyclerView换成viewpager吗？

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#53]
![qq 20180629110141](https://user-images.githubusercontent.com/16161738/42071064-d267f5de-7b8b-11e8-9d07-50be1e2f98fb.png)

**Comment by dkzwm** [comment]
如果ViewPager内没有滚动视图，这样做没问题，如果ViewPager内有滚动视图，这个判断逻辑就不好处理了，因为每个Item的滚动程度可能不一样，得自定义边界判断逻辑.如非必要请将SRL放入ViewPager的Item顶层布局。

**Comment by LongAgoLong** [comment]
神奇的产品总会有神奇的需求……

**Comment by dkzwm** [comment]
@LongAgoLong  你可以试试Clone下`develop`分支下的Demo代码，运行一下，实现了你这样的布局能力。这边会在1.6.5版本开始支持类似需求，但同时会去除状态视图功能（该功能提供的能力不足以满足实际使用的需求）。如果满足你的需求，你可以直接添加依赖
```
    implementation 'me.dkzwm.widget.srl:core:1.6.5-beta-1'
    implementation 'me.dkzwm.widget.srl:ext-utils:1.6.5-beta-1'
    implementation 'me.dkzwm.widget.srl:ext-material:1.6.5-beta-1'
    implementation 'me.dkzwm.widget.srl:ext-horizontal:1.6.5-beta-1'
    implementation 'me.dkzwm.widget.srl:ext-classic:1.6.5-beta-1'
    implementation 'me.dkzwm.widget.srl:ext-two-level:1.6.5-beta-1'
```
这边从1.6.5版本开始，将仓库由JitPack转移到JCenter，以便能更方便的测试。

**Comment by dkzwm** [comment]
No feedback, so close this issue!
