### ISSUE TITLE
Question Auto-LoadMore?

### ISSUE THREAD

**Issue by Anurag--Singh** [dkzwm/SmoothRefreshLayout#54]
Thank-you for creating a great library.

I have read in the documentation as: 

> Auto-LoadMore、Scroll to bottom to Auto-LoadMore（Recommended to use the Adapter while use ListView/GridView/RecyclerView).

I want to understand the implementation of 

> Scroll to bottom to Auto-LoadMore（Recommended to use the Adapter while use ListView/GridView/RecyclerView

with the help of code. 

Is it possible to fetch the data in advance before the user reaches the end of the list?

**Comment by dkzwm** [comment]
@Anurag--Singh  Sorry,So late to reply.
If you want to use this lib to implementation the scroll to bottom to Auto-LoadMore feature, you can check the `app`->`src`->`main`->`java`->`me.dkzwm.widget.srl.sample.ui.WithListViewActivity` code.

 If you want to richer implementation, you can implementation `OnPerformAutoLoadMoreCallBack` interface,

If you want to use Adapter to implementation the scroll to bottom to Auto-LoadMore feature, you can use this lib `https://github.com/CymChad/BaseRecyclerViewAdapterHelper`.

**Comment by Anurag--Singh** [comment]
Thankyou for providing an answer to my question with suggestion of Auto-LoadMore feature.
