### ISSUE TITLE
嵌套CoordinatorLayout时，CoordinatorLayout的下滑冲突了

### ISSUE THREAD

**Issue by choimroc** [dkzwm/SmoothRefreshLayout#56]
这个时候只有SmoothRefreshLayout能下滑，CoordinatorLayout一下滑就会触发下拉刷新

**Comment by dkzwm** [comment]
@choimroc 不好意思，才看到消息。
请问你的布局是什么样子的，用的什么版本，Demo中是有CoordinatorLayout嵌套示例的，是否是按照Demo中的配置进行的配置？

**Comment by onexuan** [comment]
可通过setScrollTargetView设置目标滚动view，并增加 AppBarLayout的addOnOffsetChangedListener，判断是否在顶部或底部，并增加
setOnHeaderEdgeDetectCallBack(this);　
setOnFooterEdgeDetectCallBack(this);
实现滚动判断
@choimroc
