### ISSUE TITLE
setEnableAutoLoadMore 无效了吗？

### ISSUE THREAD

**Issue by cx324** [dkzwm/SmoothRefreshLayout#57]
升级为最新版本之后setEnableAutoLoadMore好像无效了，之前使用setEnableScrollToBottomAutoLoadMore是有用的

**Comment by dkzwm** [comment]
@cx324 不好意思，才看到邮件。
我这边测试setEnableAutoLoadMore有效果呢，能否提供下布局和配置，方便查找问题？

**Comment by cx324** [comment]
@dkzwm 应该是布局问题，我在Demo中看到了是有效的。我的布局是CoordinatorLayout包裹Appbarlayout以及Smooth，Smooth包裹一个NestedScrollView，NestedScrollView包裹LinearLayout，LinearLayout竖向布局，里面包裹一个ViewStub以及RecyclerView。ViewStub按需加载。可能是NestedScrollView导致的。因为ViewStub不管加载没有，setEnableAutoLoadMore都无效，我打算通过给RecyclerView添加Header来将ViewStub里面的东西取出来，然后去掉NestedScrollView。

**Comment by dkzwm** [comment]
@cx324 额，这布局是感觉怪怪的，你也可以尝试代码指定下`setScrollTargetView`看能否达成需求

**Comment by cx324** [comment]
@dkzwm 现在自定义一个Header，需要同时写一个AbsClassicRefreshView以及LastUpdateTimeUpdater吗？

**Comment by dkzwm** [comment]
不是很懂，你的意思只是想修改默认Classic样式的刷新视图？那你直接继承下修改代码就行，不是的话就自定义就行

**Comment by cx324** [comment]
@dkzwm 仔细看了下Classic，是不是只需要继承AbsClassicRefreshView，然后仿照ClassicConfig写一个布局就可以啦.

**Comment by cx324** [comment]
@dkzwm 还是要写一个AbsClassicRefreshView，因为我的刷新布局里面没有ProgressBar，所以ClassicHeader，AbsClassicRefreshView，LastUpdateTimeUpdater这仨个我都要重写？

**Comment by dkzwm** [comment]
原是没有考虑可以再在Classic基础上进行继承自定义的，因为本身实现一个刷新视图实际上是很简单的，具体可以看你的需求是怎样就进行实现就行了，写好布局，根据回调方法完成该做的工作就行。
如果指定单纯的去掉ProgressBar，直接在`ClassicHeader`和`ClassicFooter`基础上改动下就行，在`onRefreshPrepare`回调里待`super.onRefreshPrepare`后把ProgressBar设为INVISIBLE就行

**Comment by cx324** [comment]
@dkzwm 我就按照Classic的流程来自定义吧，谢谢指导。

**Comment by dkzwm** [comment]
不用谢，这边Issue我关闭了，有问题你再打开本Issue就行😀
