### ISSUE TITLE
setOnRefreshListener没有回调

### ISSUE THREAD

**Issue by yangxin540** [dkzwm/SmoothRefreshLayout#58]
项目中有很多tab，切来切去，就会出现起始的tab中的setOnRefreshListener回调不到的问题

**Comment by dkzwm** [comment]
@yangxin540 SRL内部没有代码置`mRefreshListener`为`null`，理论上不存在`mRefreshListener`不会掉的问题的，这边你能提供下详细的问题描述或者出现场景吗，例如Header的刷新是否显示刷新完成只是回调没触发？
