### ISSUE TITLE
Refresh Method

### ISSUE THREAD

**Issue by pratikg711** [dkzwm/SmoothRefreshLayout#59]
Is there any method which allows me to know:
1. What is the refreshing state? (isRefreshing/ isNotRefreshing)  ? 
2. Or any method which can enable/disabling the refreshing state ?

This is not exactly an issue, I am not able to find the methods which allow me to control the refreshing state of the Layout (Refering the English Doc.)

**Comment by dkzwm** [comment]
Hi, sorry to late to reply.
  1.`isRefreshing()` or `isLoadingMore` is that methd. 
  2.`refreshComplete()` method will disable the refresh state. `autoRefresh` or `autoLoadMore` will enable the refresh state.
You can checkout the demo and Run it, so that you can easily understand the methods.

**Comment by pratikg711** [comment]
@dkzwm Okay Thanks for your help. Let me try.

Btw it a very good library great work.
