### ISSUE TITLE
Bug Fix 

### ISSUE THREAD

**Issue by onexuan** [dkzwm/SmoothRefreshLayout#60]
https://github.com/dkzwm/SmoothRefreshLayout/blob/master/core/src/main/java/me/dkzwm/widget/srl/SmoothRefreshLayout.java

3118 row

protected boolean isNotYetInEdgeCannotMoveHeader(View view) {
        if (mInEdgeCanMoveHeaderCallBack != null) {
            return mInEdgeCanMoveHeaderCallBack.isNotYetInEdgeCannotMoveHeader(this, view,
                    mFooterView);
        }
        return ScrollCompat.canChildScrollUp(view);
    }

**Comment by dkzwm** [comment]
@onexuan  感谢，Copy代码的时候没注意

**Comment by onexuan** [comment]
还有：
protected boolean isNotYetInEdgeCannotMoveHeader(View view) {
if (mInEdgeCanMoveHeaderCallBack != null) {
return mInEdgeCanMoveHeaderCallBack.isNotYetInEdgeCannotMoveHeader(this, view,
mHeaderView);
}
return ScrollCompat.canChildScrollUp(view);
}

两处：mInEdgeCanMoveHeaderCallBack!=null 和 mHeaderView

@dkzwm

**Comment by dkzwm** [comment]
@onexuan 我这实在是很弱智了(ಥ_ಥ)，感谢

**Comment by onexuan** [comment]
谢谢作者，这个库我昨天看到，今天就集成成功了，很开心，之前一直在github找有没有代码少，接口简单的库，因为我用的是CoordinatorLayout，一些开源库对它的支持不是很友好，你的库封装得确实不错！虽早上遇到一些小困难，但后来顺利解决。
解决方式是https://github.com/dkzwm/SmoothRefreshLayout/issues/56#issuecomment-422278408
我的嵌套层比较特殊：
```
<MaterialSmoothRefreshLayout>
<RelativeLayout>
<CoordinatorLayout>
<AppBarLayout>
<CollapsingToolbarLayout></CollapsingToolbarLayout>
</AppBarLayout>
<RecyclerView/>
</CoordinatorLayout>
</RelativeLayout>
</MaterialSmoothRefreshLayout>
```
作者再可改进CoordinatorLayout+ AppBarLayout嵌套问题
