### ISSUE TITLE
Cloning library gives multiple "Failed to resolve: common" errors, and cannot run

### ISSUE THREAD

**Issue by amanzan** [dkzwm/SmoothRefreshLayout#62]
I'm trying to test the library, so I cloned it but it doesn't even run, it gives multiple "Failed to resolve: common" errors that open the build.gradle file. No idea how to make it run.

Any help?

**Comment by dkzwm** [comment]
@amanzan Hi. Demo depends the [MultipleStatusView](https://github.com/qyxxjd/MultipleStatusView) for testing functions. It is possible that the author deleted old version 1.3 and can't depend it anymore. I removed the code and you can try to re-clone this lib.

**Comment by amanzan** [comment]
@dkzwm I tried different things from Stackoverflow and finally I made it work. In case it is useful for anyone else, you just have to move **google()** repository before **jcenter()** in **allprojects** **repositories**

**Comment by amanzan** [comment]
`allprojects {
     repositories {
         google()
         jcenter()
         maven { url 'https://jitpack.io' }
     }
 }`

**Comment by dkzwm** [comment]
@amanzan  That means your version of Android Studio is too low, you should try the latest Android Studio
```
allprojects {
    repositories {
        google()

        // If you're using a version of Gradle lower than 4.1, you must instead use:
        // maven {
        //     url 'https://maven.google.com'
        // }
        // An alternative URL is 'https://dl.google.com/dl/android/maven2/'
    }
}
```

**Comment by amanzan** [comment]
@dkzwm it was not that, I am using the latest version :)
