### ISSUE TITLE
 AAPT: error: duplicate value for resource 'attr/layout_gravity' with config ''.

### ISSUE THREAD

**Issue by 89Jockin** [dkzwm/SmoothRefreshLayout#63]
引入的时候报了这个错误

**Comment by dkzwm** [comment]
请问能提供你是用的版本和Gradle版本，甚至详细错误日志吗。本库依赖了Android本身提供的layout_gravity。看错误信息是有重复的attr。但本库理论上不会报这个错的，因为没有定义而且直接使用的系统属性，没有重定义

**Comment by 89Jockin** [comment]
1.6.5和1.6.4.3都会报，
 
    buildToolsVersion = "28.0.2"
    compileVersion    = 27
    minSdkVersion     = 16
    targetSdkVersion  = 27

gradle:3.3.0-alpha08

**Comment by dkzwm** [comment]
行，下周二我试试。节日有事没法处理，不好意思

**Comment by 89Jockin** [comment]
嗯，没事，加油

**Comment by dkzwm** [comment]
@89Jockin 更新到`1.6.5-beta-3`可以解决这个问题
