### ISSUE TITLE
Scale only at the top?

### ISSUE THREAD

**Issue by amanzan** [dkzwm/SmoothRefreshLayout#65]
Would it be possible to have the scale effect just at the top, not at the bottom?

**Comment by dkzwm** [comment]
@amanzan Hi, sorry to reply so late.
You can try to configure the SRL like this:
```
 refreshLayout.setDisableLoadMore(true);
 refreshLayout.setEnableOverScroll(false);
```

**Comment by amanzan** [comment]
Thanks, it's not exactly what I needed, so I created a fork anyway :)
