### ISSUE TITLE
me.dkzwm.widget.srl:ext-material:1.6.5-beta-3包貌似没上传

### ISSUE THREAD

**Issue by 670832188** [dkzwm/SmoothRefreshLayout#66]
博主您好，
Failed to resolve: me.dkzwm.widget.srl:ext-material:1.6.5-beta-3

**Comment by dkzwm** [comment]
@670832188 应该是墙的锅，仓库里有文件，我测试可以依赖，你再试试，最好全局代理再依赖。

**Comment by 670832188** [comment]
但是这个库的其他包都能下载，我再看看
