### ISSUE TITLE
google测试报的问题

### ISSUE THREAD

**Issue by LongAgoLong** [dkzwm/SmoothRefreshLayout#67]
![qq 20181102173729](https://user-images.githubusercontent.com/16161738/47907485-51ad4180-dec6-11e8-8c9e-a63ffe0409fb.png)

**Comment by dkzwm** [comment]
@LongAgoLong  如果先调用了`autoTwoLevelRefreshHint`再调用`autoRefresh`就会抛异常的，`autoTwoLevelRefreshHint `的过程未结束状态下，设计上为了避免这种情况，直接抛出异常，应避免这样使用。

**Comment by LongAgoLong** [comment]
先调用autoRefresh再调用autoTwoLevelRefreshHint吗？每次调用autoRefresh都需要调用autoTwoLevelRefreshHint？

**Comment by LongAgoLong** [comment]
哦哦，明白了，autoTwoLevelRefreshHint这个方法只是展示二级刷新提示，谢谢。
