### ISSUE TITLE
什么时候发布稳定版本

### ISSUE THREAD

**Issue by onexuan** [dkzwm/SmoothRefreshLayout#68]
作者你好，什么时候发布稳定版本？

**Comment by dkzwm** [comment]
@onexuan 不好意思才看到，这周应该能发，最近杂事有点多，抽空我全部验证后就应该可以发了。

**Comment by onexuan** [comment]
@dkzwm 好的，因为我看你的分支一直有在更新，所以不确定是否稳定了

**Comment by dkzwm** [comment]
1.6.5版本已发
