### ISSUE TITLE
Android P上的非 SDK 接口检测问题

### ISSUE THREAD

**Issue by wenjianxue** [dkzwm/SmoothRefreshLayout#69]
Android P上新增加了非 SDK 接口检测，发现SmoothRefreshLayout中有一些方法使用了反射去获取和修改非 SDK 接口，比如：
类：SRReflectUtil
方法：safelyRemoveListeners
描述：获取ViewTreeObserver私有属性mOnScrollChangedListeners，并且调用mOnScrollChangedListeners的remove方法
其中：获取ViewTreeObserver私有属性mOnScrollChangedListeners 属于light greylist, reflection
调用mOnScrollChangedListeners的remove方法 属于**dark greylist, reflection**
建议修改

**Comment by dkzwm** [comment]
@wenjianxue 不好意思才看到，这边已修改实现方式不会出现这个问题，待稳定版本发布就不会出现这问题了，现在的主分支已经合并了新实现的代码。

**Comment by wenjianxue** [comment]
好的，是版本1.6.5吧，大概什么时候发布呢？有计划吗？

**Comment by dkzwm** [comment]
计划本周找个时间全部测试一次就发，可以等等，着急的话可以检出主分支代码直接用。

**Comment by wenjianxue** [comment]
了解。
PS：以目前的情况看设置 debuggable=false 可以暂时屏蔽非 SDK 接口检测问题。
感谢 @dkzwm 及时的回答
