### ISSUE TITLE
嵌套的问题

### ISSUE THREAD

**Issue by dogodogod** [dkzwm/SmoothRefreshLayout#7]
CoordinatorLayout中嵌套ViewPager，ViewPager中的Fragment里去嵌套SmoothRefreshLayout不能达到预期的效果。上下滑动时不能和AppBarLayout联动

**Comment by dkzwm** [comment]
是否调用了setPageTransformer并使用了ToxicBakery的ViewPagerTransforms项目？请去掉setPageTransformer方法或者自己实现PageTransformer，ViewPagerTransforms实现上设置了视图的Enable属性，会造成SmoothRefreshLayout无法响应嵌套滑动。我等下会更新Demo,你对照着Demo看下效果

**Comment by dkzwm** [comment]
@lazyshep  Demo我已经上传，你可以下载Demo或者Clone项目看下效果。

**Comment by dogodogod** [comment]
好的，我过会试一下

**Comment by dkzwm** [comment]
@lazyshep  好的。没问题的话，麻烦通知下我，我好关闭issue。或者麻烦你关闭下这个issue

**Comment by dogodogod** [comment]
啊啊啊，我发现不是你的问题。我自己这里把SmoothRefreshLayout下的RecyclerView设置了setNestedScrollingEnabled(false)........导致了不能联动。感觉大触的控件
