### ISSUE TITLE
横向刷新recyclerview

### ISSUE THREAD

**Issue by arronvera** [dkzwm/SmoothRefreshLayout#70]
横向刷新recyclerview的第一条就触发了，并没有滑动到recyvlerview的最后一条再触发刷新

**Comment by dkzwm** [comment]
@arronvera 不是很明白你的意思，你的意思是到加载更多时显示到第一条就触发了刷新？RecyvlerView是不满一屏？

**Comment by arronvera** [comment]
> @arronvera 不是很明白你的意思，你的意思是到加载更多时显示到第一条就触发了刷新？RecyvlerView是不满一屏？

嗯嗯 就是一条是满屏的

**Comment by dkzwm** [comment]
我这边测试没有发现横向刷新有你说的问题呢，我是直接一个item占满一屏幕，横向4个item，还是说你直接调用了autoLoadMore？

**Comment by arronvera** [comment]
> 我这边测试没有发现横向刷新有你说的问题呢，我是直接一个item占满一屏幕，横向4个item，还是说你直接调用了autoLoadMore？

setOnRefreshListener怎么判断头部和尾部刷新呢

**Comment by dkzwm** [comment]
1.6.5之前的是根据`onRefreshBegin(boolean isRefresh)`参数`isRefresh`判断，1.6.5之后会直接使用2个方法区分即`onRefreshing`和`onLoadingMore`，但1.6.5我还没发，所以暂时先用着老版本吧。

**Comment by arronvera** [comment]
这是我的设置，始终无法进入回调函数中。 
refreshLayout.setDisableRefresh(true);//禁用头部刷新
        refreshLayout.setDisableLoadMore(false);//启用尾部刷新
        refreshLayout.setOnRefreshListener(new RefreshingListenerAdapter() {
            @Override
            public void onRefreshBegin(boolean isRefresh) {
            }
        });

**Comment by dkzwm** [comment]
```
        MaterialFooter footer = new MaterialFooter(this);
        mRefreshLayout.setFooterView(footer);
```
设置了FooterView吗

**Comment by arronvera** [comment]
设置了
MaterialFooter footer = new MaterialFooter(getContext());
        footer.setProgressBarColors(new int[]{Color.RED, Color.BLUE, Color
                .GREEN, Color.BLACK});
        refreshLayout.setFooterView(footer);

**Comment by dkzwm** [comment]
```
mRefreshLayout.setDisablePerformLoadMore(false);
```
是否关闭了触发加载更多功能。

**Comment by arronvera** [comment]
> ```
> mRefreshLayout.setDisablePerformLoadMore(false);
> ```
> 是否关闭了触发加载更多功能。

可以了呢，解决了，谢谢
