### ISSUE TITLE
调用autoLoadMore  （）之后，上拉加载更多的footer 一直存在，

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#71]
refreshLayout1.setDisableRefresh(true);
        refreshLayout1.setDisableLoadMore(false);
        refreshLayout1.setDisableLoadMoreWhenContentNotFull(true);
以上是做的设置，

调用autoLoadMore（）之后，上拉加载更多的footer 一直存在， 调用refreshComplete();也不会消失，
不知道是不是 外面用了 NestedScrollView的原因，

**Comment by dahai2070** [comment]
我就是想在网络请求的时候，用代码控制，显示footer,请求结束，隐藏footer,

**Comment by dahai2070** [comment]
final public void refreshComplete(boolean isSuccessful, long delayDurationToChangeState) {
        if (sDebug)
            SRLog.d(TAG, "refreshComplete(): isSuccessful: %s", isSuccessful);
        mIsLastRefreshSuccessful = isSuccessful;
        if (!isRefreshing() && !isLoadingMore())
            return; //我断点发现，到这儿被return 了，但是我是先调用的 autoLoadMore（），再执行的网络请求，不知道为何会这样，
        long delay = mLoadingMinTime - (SystemClock.uptimeMillis() - mLoadingStartTime);
        if (delayDurationToChangeState <= 0) {
            if (delay <= 0) {
                performRefreshComplete(true, true);
            } else {
                if (mDelayToRefreshComplete == null)
                    mDelayToRefreshComplete = new DelayToRefreshComplete();

先触发了上面的代码，再触发了下面的代码
  protected void performRefresh(boolean notify) {
        //loading start milliseconds since boot
        mLoadingStartTime = SystemClock.uptimeMillis();
        if (sDebug) SRLog.d(TAG, "onRefreshBegin systemTime: %s", mLoadingStartTime);
        if (isRefreshing()) {
            if (mHeaderView != null)
                mHeaderView.onRefreshBegin(this, mIndicator);
        } else if (isLoadingMore()) {
            if (mFooterView != null)
                mFooterView.onRefreshBegin(this, mIndicator);
        }
        if (notify && mRefreshListener != null) {
            mRefreshListener.onRefreshBegin(isRefreshing());
        }
    }

**Comment by dahai2070** [comment]
这个是我调用的代码 
 private void loadDonationData() {
        refreshLayout1.autoLoadMore();//开启自动加载更多，显示footer
        Map<String, Object> body = new HashMap<>();
        body.put("page", donationPage);
        body.put("size", donationSize);
        body.put("topicId", topic.getoId());
        RetrofitManager.getInstance().createReq(DonationService.class)
                .queryTopicDonations(body)
                .enqueue(new Callback<CommonResult>() {
                    @Override
                    public void onResponse(Call<CommonResult> call, Response<CommonResult> response) {
                        refreshLayout1.refreshComplete(); //结束刷新
                        CommonResult result = response.body();
                        if (!response.isSuccessful() || result == null) {
                            Log.e(TAG, "onResponse: " + response.message());
                            return;
                        }
                        if (result.isNotOK()) {
                            Log.e(TAG, "onResponse: " + result.getMsg());

**Comment by dahai2070** [comment]
我把这个方法延迟1秒执行，refreshLayout1.refreshComplete(); 能实现fooder 消失，但是好像没有之前使用refreshLayout那么协调了，recyclerView 会生硬的抖动几下，

**Comment by dkzwm** [comment]
你的调用autoLoadMore的时机是否在view已经完成测量后？有可能网络请求太快，由于view没有完成测量拿不到view的高度，无法触发视图移动。直接设置刷新监听，在监听回调里请求后再结束刷新会有问题吗？

**Comment by dkzwm** [comment]
@dahai2070 我看你的描述和代码不是很清楚你这是什么样的需求造就的这样的实现，你可以提供下布局结构代码和配置代码，我这边重现看是需求本身问题还是本库实现可能有问题。另外触发成功刷新准确的是在刷新回调里得知的。

**Comment by dahai2070** [comment]
“另外触发成功刷新准确的是在刷新回调里得知的”，可能是我使用问题，我调用autoLoadMore方法 后，footer 就显示出来了， 我就直接做 网络请求了，

**Comment by dahai2070** [comment]
“ dkzwm commented a day ago” 感谢你回复，你昨天的回复，我没注意看到

**Comment by dkzwm** [comment]
@dahai2070 recyclerView抖动是什么样的场景，看你的描述之前的版本不抖动？
最好配置
```
//避免触摸事件打断回滚动画
mRefreshLayout.setEnableSmoothRollbackWhenCompleted(true);
//如果还存在抖动就打开老版本的触摸事件处理逻辑
mRefreshLayout.setEnableOldTouchHandling(true);
```
你可以试试，还会抖动，最好提供下布局和配置，我复现查查。

**Comment by dahai2070** [comment]
当使用了 NestedScrollView  嵌套SmoothRefreshLayout再嵌套 recyclerView , 显示footer的时候，recyclerView 上移是被当做SmoothRefreshLayout的子view 上移，而不是 把整个NestedScrollView  上移，当footer 消失的时候，整个界面会抖动几下（上下移动速度很快吧，感觉比较生硬），具体用语言不是很好描述，

**Comment by dahai2070** [comment]
显示footer的时候，recyclerView 上移是被当做SmoothRefreshLayout的子view 上移，而不是 把整个NestedScrollView中**的内容** 上移，

**Comment by dkzwm** [comment]
我不是很懂为什么在SmoothRefreshLayout外还有嵌套一层NestedScrollView，NestedScrollView只支持一个Item，代表着只能有SmoothRefreshLayout一个View,而SmoothRefreshLayout里又有RecyclerView这个可滚动视图，那实际NestedScrollView完全可以去掉没什么用吧，而且这种嵌套下高度计算会有问题的吧

**Comment by dahai2070** [comment]
上来加载的触发，我是自己根据滑动是否到底做的判断，因为我看SmoothRefreshLayout介绍页面，说自动加载最好自己做判断，我就想那就只用SmoothRefreshLayout来显示footer,所以出现上面的问题。

**Comment by dahai2070** [comment]
是这样的，因为页面中，有图片（放recyclerView），有评论(放recyclerView)，反正好几个recyclerView，所以用了NestedScrollView，

**Comment by dahai2070** [comment]
就是一开始做评论的加载，我用了 SmoothRefreshLayout，

**Comment by dkzwm** [comment]
自动判断逻辑意思是你可以自定义判断逻辑
```
        mRefreshLayout.setOnPerformAutoLoadMoreCallBack(new SmoothRefreshLayout.OnPerformAutoLoadMoreCallBack() {
            @Override
            public boolean canAutoLoadMore(SmoothRefreshLayout parent, @Nullable View child) {
                return false;
            }
        });
```
例如你判断到了倒数第三条就要开始加载就需要在回调里判断滚动是否到倒数第三条了，滚动到了倒数第三条的话就返回`true`，就会触发自动加载

**Comment by dkzwm** [comment]
如果你想将整个NestedScrollView都网上顶上去，那你需要把SmoothRefreshLayout作为最顶层视图，然后设置
```
mRefreshLayout.setScrollTargetView(mRecyclerView);
```

**Comment by dahai2070** [comment]
哦哦，感谢。
