### ISSUE TITLE
在华为9.0系统，上下分屏无法滚动

### ISSUE THREAD

**Issue by onexuan** [dkzwm/SmoothRefreshLayout#73]
在华为9.0系统，进入最近使用的应用，点击分屏，上下分屏后无法滚动

**Comment by dkzwm** [comment]
@onexuan 我使用Demo在9.0上分屏模式下没出现这种问题，你可以设置`sDebug=true`，再触摸提供下日志。我手里没有华为手机所以没法调试。

**Comment by onexuan** [comment]
我调调看看

**Comment by onexuan** [comment]
我这边界面增加一个判断isInMultiWindowMode解决无法滚动，不SmoothRefreshLayout库问题
