### ISSUE TITLE
2675行 ViewCompat.isNestedScrollingEnabled(targetView) NPE

### ISSUE THREAD

**Issue by LambdaV5** [dkzwm/SmoothRefreshLayout#74]
ViewCompat.isNestedScrollingEnabled(targetView) ,其中targetView可能为空

**Comment by dkzwm** [comment]
@LambdaV5 谢谢，这个问题已知，只是我本地的版本一直没有提交，问题已修复，最近比较忙，待我测试完一起提交。

**Comment by LambdaV5** [comment]
thanks
