### ISSUE TITLE
1.6.5版本 为什么会把ErrorView  EmptyView 移除？我觉得很好用啊

### ISSUE THREAD

**Issue by hyl87** [dkzwm/SmoothRefreshLayout#75]

**Comment by dkzwm** [comment]
@hyl87 原本加入这个功能来自于我实际工作中的业务需求，很轻量的实现带来的效益还是比较可观的，毕竟可以减少一层嵌套，但随着本库功能的迭代，考虑到多层嵌套滚动和状态切换时各种状态的判断，继续支持这个功能带来的性能损失已经超过了其带来的效益，有点得不偿失。
由于每次动作都需要对内部视图做多次判断，以及重布局时位置关系的控制都过于复杂并且其动画效果也没有明显优势，对于不需要使用状态视图功能的用户来说这点性能损失是不可接受的，固在1..6.5之后的版本移除了这部分能力。
1.6.5之后的版本转向优化本库在部分逻辑上带来的性能损失，提高绘制效率，使滑动、动画更加流畅，所以状态视图能力不会再加入了，如果需要使用状态能力只能使用1.6.4.3版本或者使用其它开源状态视图库，
