### ISSUE TITLE
DialogFragment 里面 recyclerView 使用GridLayoutManager 滑动之后的第一次点击无效

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#77]
DialogFragment 里面 recyclerView 使用GridLayoutManager 滑动之后的第一次点击无效
感觉就像是 recyclerView  失去焦点的感觉，
我把SmoothRefreshLayout 注释掉，就没有这个情况出现了，
求助。

**Comment by dahai2070** [comment]
滑出屏幕的item,再滑回屏幕，才会出现 第一次点击无效的问题，

**Comment by dkzwm** [comment]
@dahai2070 本周我没有带电脑回家，暂时没法定位问题，只能星期一去公司我定位问题，这边你可以尝试切换触摸处理逻辑，1.6.5以上有2套触摸逻辑，你先切换试试，周一我定位到问题，如果是本库的BUG会在周一修复

**Comment by dahai2070** [comment]
切换触摸逻辑，我去看看文档，文档有介绍怎么切换的吧，非常感谢你的回复。

**Comment by dahai2070** [comment]
setEnableOldTouchHandling  是指的这个方法吗？切换到旧的触摸处理

**Comment by dkzwm** [comment]
是的，你可以切换看看，不行的话明天我测试看

**Comment by dahai2070** [comment]
调用此方法后     refreshLayout.setEnableOldTouchHandling(true); 
问题还是依旧，第一下点击无效，

**Comment by dahai2070** [comment]
明天我再来，感谢你哦。

**Comment by dkzwm** [comment]
@dahai2070 这边尝试修复了一个点击丢失问题，问题为在手势滑动过程中的点击，由于手势对应的嵌套滑动仍然在进行中，导致消费点击事件出现了异常。这边我会发一个`1.6.6.1-beta-1`版本，你依赖测试下是否已修复，如果已修复麻烦告诉我一下，谢谢。

**Comment by dahai2070** [comment]
收到，正在测试

**Comment by dahai2070** [comment]
试了下。问题还是在，滑动完全停止后，第一次点击还是无效。

**Comment by dahai2070** [comment]
在“抛滑”（手指滑一下就离开屏幕）的情况下，滑动到边界（滑动到最顶端或者是最低端），就会出现，如果手指不离开屏幕，那就没问题。

**Comment by dkzwm** [comment]
是否关闭了越界滚动，我今天测试是开启了越界滚动下修复的问题，这边我明天测试看对关闭了越界滚动功能是否修复了

**Comment by dahai2070** [comment]
我试试呢 开启越界滚动，我都不知道 越界滚动是做什么的，

**Comment by dahai2070** [comment]
嗯，果然，开启越界滚动之后，问题得以解决。非常感谢。

**Comment by dahai2070** [comment]
我使用了你的作品在我app 里面，如果我app 日后做成了，我会来联系你，给你合理的报酬。非常感谢你以及众多的无私开源者。
