### ISSUE TITLE
setDisableLoadMoreWhenContentNotFull Bug

### ISSUE THREAD

**Issue by onexuan** [dkzwm/SmoothRefreshLayout#79]
反馈setDisableLoadMoreWhenContentNotFull 底部显示问题

显示不正常，会显示在列表之上
mSmoothRefreshLayout.materialStyle();
mSmoothRefreshLayout.setDisableLoadMore(false);
mSmoothRefreshLayout.setEnableOverScroll(false);
mSmoothRefreshLayout.setScrollTargetView(recyclerView);
mSmoothRefreshLayout.setEnableSmoothRollbackWhenCompleted(true);
mSmoothRefreshLayout.setDisableLoadMoreWhenContentNotFull(false);

把materialStyle()放在最后，显示正常
mSmoothRefreshLayout.setDisableLoadMore(false);
mSmoothRefreshLayout.setEnableOverScroll(false);
mSmoothRefreshLayout.setScrollTargetView(recyclerView);
mSmoothRefreshLayout.setEnableSmoothRollbackWhenCompleted(true);
mSmoothRefreshLayout.setDisableLoadMoreWhenContentNotFull(false);
mSmoothRefreshLayout.materialStyle();

**Comment by dkzwm** [comment]
不是核心库的BUG，ext-materials库的配置只是个通用配置，你可以看下这个配置会设置监听动态修改顶部视图和底部视图的显示样式，由于你并未开启底部加载更多启用这个通用配置，此时底部并未打开，设置监听就很浪费资源了，所以判断未启用底部就没添加监听，要想使用通用配置就必须将setEnableLoadMore打开后启用配置。

**Comment by onexuan** [comment]
好的，=我试下

**Comment by onexuan** [comment]
没有你说的setEnableLoadMore方法，就是setDisableLoadMore吧？

**Comment by dkzwm** [comment]
@onexuan  是的，昨天我是在手机上回复的，时间有点仓促，没有细看代码，
```
    public void materialStyle() {
        setRatioOfFooterToRefresh(.95f);
        setMaxMoveRatioOfFooter(1f);
        setRatioToKeep(1f);
        setMaxMoveRatioOfHeader(1.5f);
        setEnablePinContentView(true);
        setEnableKeepRefreshView(true);
        setEnablePinRefreshViewWhileLoading(true);
        setEnableNextPtrAtOnce(true);
        if (mHeaderView instanceof MaterialHeader)
            ((MaterialHeader) mHeaderView).doHookUIRefreshComplete(this);
        //问题出在这里，如果先关闭了Footer，调用materialStyle()不会添加这个监听，这个监听主要是用来改变Header和Footer的布局样式。Header基本和SwipeRefreshLayout的样式相同，Footer则是普通的跟随内容布局样式。由于这个只是个通用配置，其主要是模仿SwipeRefreshLayout的大体功能.方便使用者快速使用的目的，默认SRL是关闭了Footer的，需要手动启用，这个时候只能先手动配置`setDisableLoadMore`为`false`后再调用`materialStyle()`。
        if (!isDisabledLoadMore()) {
            removeOnUIPositionChangedListener(mOnUIPositionChangedListener);
            addOnUIPositionChangedListener(mOnUIPositionChangedListener);
        }
    }

```

**Comment by onexuan** [comment]
好的，那应该算解决问题了
