### ISSUE TITLE
你好，设置setEnableNoMoreData的问题

### ISSUE THREAD

**Issue by seemelala** [dkzwm/SmoothRefreshLayout#80]
setEnableNoMoreData设置之后页面滑动会出现卡住的情况，你可以在WithRecyclerViewActivity中试试，或者直接在demo的WithListViewActivity多加载几页就会出现这个情况

**Comment by dkzwm** [comment]
@seemelala  感谢反馈，这边测试的时候没覆盖到这种场景，这边会在1.6.6.2修正这个问题。

**Comment by seemelala** [comment]
好的，幸苦

**Comment by dkzwm** [comment]
@seemelala 你更新下1.6.6.2版本，这个问题修复了。如果还有问题，麻烦反馈给我，谢谢。

**Comment by seemelala** [comment]
嗯嗯。好的。麻烦了哈
