### ISSUE TITLE
我不是很确定是否和 smoothRefreshLayout 有关，当使用recyclerView+GridLayoutManager 的a时候

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#81]
我不是很确定是否和 smoothRefreshLayout 有关，当使用recyclerView+GridLayoutManager 的时候，
下来刷新过程中（刷新的header一直显示的情况下），手动向上滑动，当滑动到上边界的时候，抛出异常，
是recyclerView 6292 行代码 中抛出的，
`    if (offsetPosition < 0 || offsetPosition >= RecyclerView.this.mAdapter.getItemCount()) {
                        throw new IndexOutOfBoundsException("Inconsistency detected. Invalid item position " + position + "(offset:" + offsetPosition + ")." + "state:" + RecyclerView.this.mState.getItemCount() + RecyclerView.this.exceptionLabel());
                    }
`
我尝试了，如果使用LinearLayoutManager,则 不会出现这个问题，
之前使用LinearLayoutManager（没有smoothRefreshLayout 的情况下），偶尔也会抛出这个异常，我是按网上的方法，新建一个类，继承于LinearLayoutManager，并重写onLayoutChildren（），在这个方法中，捕获异常；  我也尝试依葫芦画瓢，新建一个类继承于GridLayoutManager ，，，代码如下，
`public class WrapContentGradLayoutManager extends GridLayoutManager {
    public WrapContentGradLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public WrapContentGradLayoutManager(Context context, int spanCount) {
        super(context, spanCount);
    }

    public WrapContentGradLayoutManager(Context context, int spanCount, int orientation, boolean reverseLayout) {
        super(context, spanCount, orientation, reverseLayout);
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
}`
无效，还是抛异常。

**Comment by dkzwm** [comment]
这个明显不是SRL造成的，应该是你对Adapter数据源做了删除操作导致下标越界了

**Comment by dahai2070** [comment]
我排除下，非常感谢你。

**Comment by dkzwm** [comment]
没事，注意设置的数据源是否指向了动态更新的数据源，导致数据更新没有通知adapter导致数据Count不一致了

**Comment by dahai2070** [comment]
应该是你说的情况，我在做下拉刷新的时候，清空了数据，当recyclerView 上移，生成item的时候，出问题的，之前一直没发现这个问题，因为从服务端返回请求数据较快，刚才偶然我在服务端打了断点，，app一直处于 refreshing 中，，我才发现的问题，

**Comment by dahai2070** [comment]
验证了，就是我清空了数据，，与SRL 无关。
