### ISSUE TITLE
NestedScrollView与横向滑动

### ISSUE THREAD

**Issue by Chen-keeplearn** [dkzwm/SmoothRefreshLayout#82]
按照大佬TestHorizontalRecyclerViewActivity这个demo，是否NestedScrollView与横向滑动存在冲突？我在xml中的NestedScrollView嵌套了横向的recyclerView滑动，似乎不能刷新与加载更多

**Comment by dkzwm** [comment]
@Lalways  `setDisableWhenAnotherDirectionMove(true)` 需要设置下，默认是只要触摸就拦截，如果有其它方向布局嵌套其中需要打开这个。

**Comment by dkzwm** [comment]
@Lalways 不好意思没注意看内容，能麻烦你具体说下布局如何吗

**Comment by dkzwm** [comment]
@Lalways 这边暂时麻烦你继承重载下movePos方法
```
 @Override
    protected void movePos(float delta) {
        if (delta == 0f) {
            if (sDebug) Log.d(TAG, "movePos(): delta is zero");
            mIndicatorSetter.setCurrentPos(mIndicator.getCurrentPos());
            return;
        }
        if (delta > 0 && mMode == Constants.MODE_SCALE && calculateScale() >= 1.2f) {
            return;
        }
        int to = mIndicator.getCurrentPos() + Math.round(delta);
        // over top
        if (!mScrollChecker.$IsScrolling && to < IIndicator.START_POS) {
            to = IIndicator.START_POS;
            if (sDebug) Log.d(TAG, "movePos(): over top");
        }
        mIndicatorSetter.setCurrentPos(to);
        int change = to - mIndicator.getLastPos();
        //这的锅，原逻辑在嵌套滚动模式下不会触发让父视图继续传递触摸事件导致SRL层级的嵌套滚动被打断了
        //if (getParent() != null && !mNestedScrolling && mIndicator.hasTouched())
        if (getParent() != null && mIndicator.hasTouched())
            getParent().requestDisallowInterceptTouchEvent(true);
        if (isMovingHeader()) updatePos(change);
        else if (isMovingFooter()) updatePos(-change);
    }
```

**Comment by Chen-keeplearn** [comment]
<me.dkzwm.widget.srl.HorizontalSmoothRefreshLayout
                    android:id="@+id/home_horizontal_refresh"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/rv_shop"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="11dp"
                        android:layout_marginRight="11dp"
                        android:nestedScrollingEnabled="false" />
                </me.dkzwm.widget.srl.HorizontalSmoothRefreshLayout>
这是我xml中的一段布局，嵌套在NestedScrollView下的，下面是我的部分java代码


//添加header
        MaterialHeader header = new MaterialHeader(getActivity());
        header.setColorSchemeColors(new int[]{Color.RED, Color.BLUE, Color.GREEN, Color.BLACK});
        header.setPadding(PixelUtl.dp2px(getActivity(), 25), 0,
                PixelUtl.dp2px(getActivity(), 25), 0);
        shopRefresh.setHeaderView(header);
        //添加footer
        MaterialFooter footer = new MaterialFooter(getActivity());
        footer.setProgressBarColors(new int[]{Color.RED, Color.BLUE, Color.GREEN, Color.BLACK});
        shopRefresh.setFooterView(footer);
        //禁用Footer刷新（默认:false）
        shopRefresh.setDisableLoadMore(false);
        //到底部自动加载（默认:false）
        shopRefresh.setEnableAutoLoadMore(true);
        //固定内容视图（默认:false）
        shopRefresh.setEnablePinContentView(true);
        //固定刷新视图在所设置的应该停留的位置，并且不响应移动，即Material样式（默认:false）,
        // 设置前提是开启了setEnablePinContentView和setEnableKeepRefreshView2个选项，否则运行时会抛出异常
        shopRefresh.setEnablePinRefreshViewWhileLoading(true);
        rvShop.setLayoutManager(new GridLayoutManager(getActivity(), 1,
                LinearLayoutManager.HORIZONTAL,false));
        shopsAdapter = new HomeShopsAdapter(R.layout.item_home_shops_list, shopsBeans);
        rvShop.setAdapter(shopsAdapter);
        shopRefresh.setOnRefreshListener(new RefreshingListenerAdapter() {
            @Override
            public void onRefreshing() {
                shopCurPage = 1;
                getShopData();
                shopRefresh.refreshComplete();
            }

            @Override
            public void onLoadingMore() {
                shopCurPage++;
                getShopData();
                shopRefresh.refreshComplete();
            }
        });
然后实现不了recyclerView横向的刷新和加载更多，不知道我的问题描述清楚没有，或是我的姿势不对，请大佬指点，我就是看了demo，一些iss，没找到相关信息，我怀疑是不是滑动冲突了


另外刚刚大佬加我重写方法中，$IsScrolling我重写的时候好像不能应用该字段，会报错。废话多，望大佬见谅

**Comment by dkzwm** [comment]
@Lalways 不好意思，这边大概今晚会发1.6.6.3来解决这个问题。原来测试的时候没测试过这种场景，遗漏了，顺便会解决点其他问题。

**Comment by Chen-keeplearn** [comment]
完全没必要说什么不好意思，反而是我们应该感谢你，大佬辛苦啦

**Comment by dkzwm** [comment]
@Lalways  大兄弟，你依赖下1.6.6.3-beta-1版本，试下是否修复了，如果修复了麻烦告诉我一下，我这边好发布 1.6.6.3。Thx！

**Comment by Chen-keeplearn** [comment]
好像依赖了1.6.6.3-beta-1这个版本，但是好像还是那样

**Comment by dkzwm** [comment]
@Lalways 还是无法触发刷新?我这边也是这种布局下，是可以的。我这边有点不是非常明白你的问题是什么表现，你最好描述下，否则我也不好定位问题

**Comment by Chen-keeplearn** [comment]
可能是我使用的姿势不对，我再看看

**Comment by dkzwm** [comment]
@Lalways 大兄弟，你依赖下1.6.6.3-beta-2版本, 我这边注意看了你的布局，问题出在RecyclerView的高度是自适应的同时HSRL的高度也是自适应的，这个时候由于HSRL传递给Header和Footer的高度都是零导致Header和Footer高度都为0即不可见了。但存在一个问题，由于HSRL和RV都是自适应高度，第一次进入没有数据的情况下是无法看到刷新效果的，因为这个时候HSRL的高度为0，待数据填充后高度不为0就能正常操作了。
