### ISSUE TITLE
我又来打扰了，refreshLayout 嵌套 recyclerView ，禁用下拉刷新，使用bottom_sheet_behavior 的时候，recyclerView 的下拉事件被拦截了，

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#84]
我又来打扰了，refreshLayout 嵌套 recyclerView ，禁用下拉刷新，并且使用bottom_sheet_behavior 的时候整个view 以底部弹出框显示，recyclerView 的下拉事件被拦截了，recyclerView只能上滑，不能向下滑动了，我尝试不使用 refreshLayout ，recyclerView可以上下滑动，目前没有方向，不知道从哪儿着手解决问题，大佬给指点下，感谢。
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <View
        android:id="@+id/place_holder"
        android:layout_width="match_parent"
        android:layout_height="70dp"
        android:visibility="gone"/>

    <RelativeLayout
        android:id="@+id/title_bar"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:background="@drawable/comment_view_background_shape">

        <RelativeLayout
            android:id="@+id/left_layout"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_centerVertical="true"
            android:layout_marginStart="3dp"
            android:background="@drawable/tx_title_bar_click_layout_ripple_bg"
            android:clickable="true">

            <ImageView
                android:id="@+id/left_image"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:scaleType="centerInside"
                android:src="@drawable/ease_back" />
        </RelativeLayout>

        <TextView
            android:id="@+id/tv_comment_count"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:textColor="@color/text_gray"
            android:textSize="14sp" />

        <View
            android:layout_width="match_parent"
            android:layout_height="0.5dp"
            android:layout_alignParentBottom="true"
            android:background="@color/placeholder" />
    </RelativeLayout>

    <me.dkzwm.widget.srl.MaterialSmoothRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        android:orientation="vertical">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_comment_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white" />
    </me.dkzwm.widget.srl.MaterialSmoothRefreshLayout>

</LinearLayout>`
以上是 布局是作为一个自定义View(我取名CommentView) 的布局，自定义view显示 在另外一个activity 的布局里面，以下是activity布局的一部分 
`      
   .......
    <com.srbl.mytx.widget.CommentView
        android:id="@+id/comment_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/bottom_sheet_behavior"/>

    <com.srbl.mytx.widget.CommentBottomBar
        android:id="@+id/comment_bottom_bar"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>
`

以下是activity中控制自定义View的代码 
  bottomSheetBehavior = BottomSheetBehavior.from(findViewById(R.id.comment_view));
        bottomSheetBehavior.setHideable(true);
        //设置默认先隐藏
        bottomSheetBehavior.setState(BottomSheetBehavior.STATE_HIDDEN);
      //控制显示 
      //  bottomSheetBehavior.setState(BottomSheetBehavior.STATE_COLLAPSED);

**Comment by dkzwm** [comment]
@dahai2070 这边没有重写`canScrollVertically`导致BottomSheetBehavior以为内部视图不需要再消耗滚动距离，这边简单的设置下`mRefreshLayout.setNestedScrollingEnabled(false); `就可以了，后面我发个实现了这个接口的版本。

**Comment by dahai2070** [comment]
收到，我加上测试一下。

**Comment by dahai2070** [comment]
解决了，感谢，我记得我加了你QQ的，但是当时忘记备注了，能再发我一下你QQ吗

**Comment by dkzwm** [comment]
@dahai2070 我没有公开过我的QQ，所以应该是没有添加过的，而且我基本没用QQ了，你加了我应该也很难在QQ上找到我，我每天都会上Github，找我并不难，你有问题可以开Issue。

**Comment by dahai2070** [comment]
其实我是有个其他问题想请教下，我使用了一个开源的播放器，名为 饺子播放器，也是github上找的开源的，我现在用了 BottomSheetBehavior 来控制一个底部弹出框，我给这个弹出框设置了一个 marginTop的时候,
`   
...........................
<com.srbl.mytx.widget.CommentView
        android:id="@+id/comment_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="70dp"  //设置layout_marginTop
        app:layout_behavior="@string/bottom_sheet_behavior" />

    <com.srbl.mytx.widget.CommentBottomBar
        android:id="@+id/comment_bottom_bar"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>`

当我点了播放器，再弹出这个弹出框的时候，当弹出框弹出后，会往下回弹一个距离，距离就是我设置的 marginTop的值，等于说  弹出框距离屏幕顶端的距离就是 两个marginTop的距离了，
如果我打开页面，不点播放，只弹出 底部弹出框，就一切正常，像我这个情况，大概该从哪儿着手检查呢？

**Comment by dahai2070** [comment]
如果大佬很忙，忽略我问题也没什么的，已经非常感谢了

**Comment by dahai2070** [comment]
刚才 继续测试了下，放recyclerView 里面的item 没有填充满的时候，上下滑动 弹出框有点不协调，在BottomSheetBehavior.STATE_COLLAPSED 和BottomSheetBehavior.STATE_EXPANDED 两个状态直接可能出现跳动，有时候是没法从 折叠状态上滑到完全展开状态，

**Comment by dkzwm** [comment]
@dahai2070 简单的处理可以将
```
android:layout_marginTop="70dp"
```
改成CommentView里的第一个View的属性，这样能解决这个问题。

**Comment by dahai2070** [comment]
嗯，layout_marginTop的问题，我就是这样解决的，
我最后说的问题，现在已经解决了，我更新到最新版，然后当没有更多数据的时候，我禁用上拉加载更多，问题就解决了。
