### ISSUE TITLE
viewpager横向刷新，很难滑到下一个，快速滑动滑不过去

### ISSUE THREAD

**Issue by renzhenfei** [dkzwm/SmoothRefreshLayout#85]

**Comment by dkzwm** [comment]
@renzhenfei 我这边测试没问题，能否提供下具体布局和配置代码，是否是布局不合理的问题。

**Comment by renzhenfei** [comment]
`    <me.dkzwm.widget.srl.HorizontalSmoothRefreshLayout
        android:id="@+id/refreshView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v4.view.ViewPager
            android:id="@+id/vp0"
            android:layout_width="wrap_content"
            android:layout_height="match_parent" />

    </me.dkzwm.widget.srl.HorizontalSmoothRefreshLayout>`
`refreshLayout = rootView.refreshView
        val header = MaterialHeader<DefaultIndicator>(activity)
        header.setColorSchemeColors(intArrayOf(Color.RED, Color.BLUE, Color.GREEN, Color.BLACK))
        refreshLayout?.setHeaderView(header)
        val footer = MaterialFooter<DefaultIndicator>(activity)
        footer.setProgressBarColors(intArrayOf(Color.RED, Color.BLUE, Color.GREEN, Color.BLACK))
        refreshLayout?.setFooterView(footer)
        refreshLayout?.setDisableLoadMore(true)
        refreshLayout?.setDisableRefresh(true)
        refreshLayout?.setDisablePerformLoadMore(false)
        refreshLayout?.setEnableKeepRefreshView(true)
        refreshLayout?.setDisableWhenAnotherDirectionMove(true)`
布局其实很简单的，我通过监听ViewPager的滑动方向控制刷新可用解决了。
再提一个建议，刷新完后调用refreshComplete的时候有个动画就更好了

**Comment by renzhenfei** [comment]
> @renzhenfei 我这边测试没问题，能否提供下具体布局和配置代码，是否是布局不合理的问题。

@

**Comment by renzhenfei** [comment]
> @renzhenfei 我这边测试没问题，能否提供下具体布局和配置代码，是否是布局不合理的问题。

测试横向刷新的demo里面refreshComplete的时候是有动画的，我这么写就没有，一下就消失了

**Comment by dkzwm** [comment]
设计上没考虑过ViewPager这种需求，你可以设置`setOnLoadMoreScrollCallback`，每次触发`onScroll`回调调用`view.scrollBy((int) delta, 0);`看下是否可行

**Comment by renzhenfei** [comment]
> 设计上没考虑过ViewPager这种需求，你可以设置`setOnLoadMoreScrollCallback`，每次触发`onScroll`回调调用`view.scrollBy((int) delta, 0);`看下是否可行
好的我试下

**Comment by renzhenfei** [comment]
> 设计上没考虑过ViewPager这种需求，你可以设置`setOnLoadMoreScrollCallback`，每次触发`onScroll`回调调用`view.scrollBy((int) delta, 0);`看下是否可行
`refreshLayout?.setOnLoadMoreScrollCallback { _, delta -> Log.e("setOnLoadMore = ",delta.toString()) }`
这个回调不会触发 =。=

**Comment by renzhenfei** [comment]
之后会考虑支持吗

> 设计上没考虑过ViewPager这种需求，你可以设置`setOnLoadMoreScrollCallback`，每次触发`onScroll`回调调用`view.scrollBy((int) delta, 0);`看下是否可行

之后会考虑支持吗

**Comment by dkzwm** [comment]
@renzhenfei ViewPager惯性丢失我这边会发布1.6.6.5来处理修复这个问题，发了会通知你，这边更新后你不需要手动禁止刷新，避免手动禁止导致动画丢失。

**Comment by dkzwm** [comment]
@renzhenfei 已上传，你更新下，现在应该能快速滑到下一页或者上一页了。

**Comment by dkzwm** [comment]
@renzhenfei 已上传，你更新下，现在应该能快速滑到下一页或者上一页了。

**Comment by renzhenfei** [comment]
> @renzhenfei 已上传，你更新下，现在应该能快速滑到下一页或者上一页了。

感谢，我试一下

**Comment by renzhenfei** [comment]
> @renzhenfei 已上传，你更新下，现在应该能快速滑到下一页或者上一页了。

1.没有滑动的那么丝滑了，有时候会颤动
2.加载更多不生效了，拉不过去

**Comment by dkzwm** [comment]
触摸逻辑没有修改，只针对ViewPager做了特殊处理，所以不存在滑动有变化的问题，应该是你的错觉，另外加载更多不生效是否是你关闭了加载更多。

**Comment by renzhenfei** [comment]
没有的，有时候能拉动一点点。ViewPager的滑动确实有变化的

**Comment by dkzwm** [comment]
我注意到你的ViewPager的宽度是自适应的，这是什么样的考量呢，是否可以更改为match_parent呢再测试下，我这边测试都是全部match_parent，没有遇到过加载更多失效的问题。

**Comment by dkzwm** [comment]
@renzhenfei  我拉取了分支`issue85`，修改了`测试横向刷新界面(TestHorizontalRefreshActivity)`，你可以检下来测试下，我这边测试是能快速滑动的，同时加载更多也能够使用，没有问题。你可以查看下代码配置问题。

**Comment by renzhenfei** [comment]
[http://note.youdao.com/noteshare?id=788535d118b112f872babd09f4e52de0](url)
[http://note.youdao.com/noteshare?id=14c2b0e55877911653688dd6f904e4f3](url)
一个是我自己处理了滑动，刷新的效果生硬。另一个是你提供的，viewpager恢复的时候有点生硬，有空看一下

**Comment by dkzwm** [comment]
@renzhenfei 看录屏，怀疑可能是以下参数被修改了：
1.回滚时间
2.setEnable
3.setDisableRefresh(true)
4.setDisableLoadMore(true)
你可以打开SRL的debug开关，跟踪下日志，看是否有日志`reset()`被调用了。
或者将异常部分的日志贴出

**Comment by zqisheng** [comment]
@renzhenfei 解决这种滑动冲突，我是这个做的:先是判断用户手滑动方向，如果是向左或者右滑动角度不超过45度，就禁止刷新，设为不可用，如果超过45度就设置为可用

**Comment by liuhaifang** [comment]
我用的1.6.6.7版本，依然存在这个问题：
viewpager横向刷新，很难滑到下一个，快速滑动滑不过去

录了屏幕录像，楼主方便加一下qq（835695733）吗，我发视频给你

**Comment by dkzwm** [comment]
@liuhaifang 是否有使用 [ViewPagerTransforms](https://github.com/ToxicBakery/ViewPagerTransforms),如果有请去掉`ViewPagerTransforms`，其在触摸过程中会调用`setEnable`方法导致SRL触摸中断。如果没有打开log开关，查看下日志，这边我很久没用QQ了，视频的话你可以发邮件到`aidkzwm@gmail.com`，我抽空会看下，猜下是什么问题导致的。
