### ISSUE TITLE
横向刷新低版本，会出现没有加载动画的情况

### ISSUE THREAD

**Issue by lhpliu** [dkzwm/SmoothRefreshLayout#86]
当前版本1.6.6.1时，出现的情况，横向刷新时，转圈提示有占位，但是不显示
更新到1.6.6.4后就没事了 问下是什么情况

**Comment by dkzwm** [comment]
SRL高度为自适应同时内部视图高度也为自适应时高度？1.6.6.3的版本修复了这个问题，其它并没有大的修改。可以查看下每次版本的更新日志。

**Comment by lhpliu** [comment]
好的  多谢
