### ISSUE TITLE
上拉、加载更多只会出现一种，是什么问题？ Bug

### ISSUE THREAD

**Issue by jack-laowang** [dkzwm/SmoothRefreshLayout#88]
有时候只能上拉，有时候只能加载更多，不能同时出现
布局如下，

<me.dkzwm.widget.srl.SmoothRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
 <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

     </LinearLayout>

    </android.support.v4.widget.NestedScrollView>

</me.dkzwm.widget.srl.SmoothRefreshLayout>

**Comment by dkzwm** [comment]
@MinchinWang 你的意思是下拉刷新和上拉加载不能同时进行？

**Comment by jack-laowang** [comment]
嗯，要么只能上拉 要么只能下拉，所以很奇怪 SmoothRefreshLayout 嵌套 NestedScrollView

**Comment by dkzwm** [comment]
刷新库都是这么的，这2个操作理论上不可能同时进行，如果要单独维护上拉和下拉的刷新状态，必然导致逻辑复杂度直线上升，所以没有任何一款支持下拉刷新和上拉加载的库会同时支持2个操作。
如果你确定你必须支持这么操作，那么只能设置`OnUIPositionChangedListener`监听，当且仅当`IIndicator.hasTouched()==true`，判断下拉动作时，如果处于上拉加载中就提前`refreshComplete`，然后下拉刷新就可以触发了；判断上拉动作时，如果处于下拉刷新中就提前`refreshComplete`，然后上拉加载就可以触发了，我是不建议这么做的。
所以这并不是BUG，你应该考虑下这种操作是否合理。

**Comment by dkzwm** [comment]
```
        mRefreshLayout.addOnUIPositionChangedListener(new SmoothRefreshLayout.OnUIPositionChangedListener() {
            @Override
            public void onChanged(byte status, IIndicator indicator) {
                if (indicator.getMovingStatus() == Constants.MOVING_HEADER) {
                    if (status == SmoothRefreshLayout.SR_STATUS_LOADING_MORE) {
                        mRefreshLayout.refreshComplete();
                    }
                } else if (indicator.getMovingStatus() == Constants.MOVING_FOOTER) {
                    if (status == SmoothRefreshLayout.SR_STATUS_REFRESHING) {
                        mRefreshLayout.refreshComplete();
                    }
                }
            }
        });
```
大概这样操作，数据插入可能会不符合用户的感知，除非你的数据插入操作是可以取消的，例如一旦触发刷新就得保证可能还运行的加载对应的数据插入操作不能干扰刷新对应的数据插入操作。
所以功能是可以实现的，只是这样实现不是很合理而已。

**Comment by jack-laowang** [comment]
不是 就是可以下拉刷新 ，但是加载更多 连ui都显示不出来，或者 不能下拉刷新

**Comment by dkzwm** [comment]
@MinchinWang 是否是使用的`ext-classics`包，`ClassicHeader`和`ClassicFooter`就是这么专门设计的，当下拉刷新中去上拉加载是不会显示相关文字和图标的，避免明明提示松开加载却没有触发加载操作的尴尬问题，如果想触发显示相关文字和图标，请按照这样修改
> ```
>         mRefreshLayout.addOnUIPositionChangedListener(new SmoothRefreshLayout.OnUIPositionChangedListener() {
>             @Override
>             public void onChanged(byte status, IIndicator indicator) {
>                 if (indicator.getMovingStatus() == Constants.MOVING_HEADER) {
>                     if (status == SmoothRefreshLayout.SR_STATUS_LOADING_MORE) {
>                         mRefreshLayout.refreshComplete();
>                     }
>                 } else if (indicator.getMovingStatus() == Constants.MOVING_FOOTER) {
>                     if (status == SmoothRefreshLayout.SR_STATUS_REFRESHING) {
>                         mRefreshLayout.refreshComplete();
>                     }
>                 }
>             }
>         });
> ```
> 大概这样操作，数据插入可能会不符合用户的感知，除非你的数据插入操作是可以取消的，例如一旦触发刷新就得保证可能还运行的加载对应的数据插入操作不能干扰刷新对应的数据插入操作。
> 所以功能是可以实现的，只是这样实现不是很合理而已。

**Comment by dkzwm** [comment]
如果你需要显示相关文字和图标，那么你需要继承ClassicHeader和ClassicFooter，重载`onPureScrollPositionChanged`方法，在内部调用`onRefreshPositionChanged`进行参数传递，这样图标和文字就能显示。

**Comment by getglory** [comment]
我布局切换使用SmoothRefreshLayout，上拉加载更多用的BaseRecyclerViewDapterHelper

**Comment by jack-laowang** [comment]
就是下拉刷新完成了，然后再去上拉加载更多，就看不到上拉加载更多
你的demo里面，以下代码
上拉加载更多，第二次就上拉不了了

<?xml version="1.0" encoding="utf-8"?>
<me.dkzwm.widget.srl.SmoothRefreshLayout
    android:id="@+id/smoothRefreshLayout_test_base_recyclerView_adapter"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerView_test_base_recyclerView_adapter"
        android:layout_width="match_parent"
        android:nestedScrollingEnabled="false"
        android:layout_height="match_parent"/>
    </androidx.core.widget.NestedScrollView>
</me.dkzwm.widget.srl.SmoothRefreshLayout>
