### ISSUE TITLE
只从1.6.5以后，CoordinatorLayout嵌套会有问题

### ISSUE THREAD

**Issue by dnwalter** [dkzwm/SmoothRefreshLayout#89]
1.6.5的时候还可以，之后demo里面的CoordinatorLayout嵌套的界面，下滑的fling，会不流畅，且fling不会把APPBarLayout拉下来

**Comment by dkzwm** [comment]
@dnwalter 不好意思，这边测试验证没有覆盖到这种`app:layout_scrollFlags="scroll|exitUntilCollapsed"`场景，这边你更新下1.6.6.6版本

**Comment by dnwalter** [comment]
git主果然神速，但我也想知道原因。可以大概描述一下是为什么吗？

**Comment by dkzwm** [comment]
问题出现为SRL在onNestedScroll回调中判断了上层没有消耗距离就手动终止嵌套滚动。
AppBarLayout里的逻辑不是在onNestedPreScroll进行消耗距离，而是在onNestedScroll进行消耗，所以当上层不再进行提前消耗(onNestedPreScroll)即dyConsumed和dxConsumed都为0时SRL手动终止了嵌套滚动，去掉手动终止的代码就好了，后续只有实现NestedScrollingParent3后就能得到onNestedPreScroll各层消耗的值，在NestedScrollingParent2中是无法得知onNestedPreScroll各层消耗的值的。

**Comment by dkzwm** [comment]
嵌套滚动由Child触发并向上进行分发，一般情况下onNestedPreScroll由Child的父层级自下而上进行消耗，每一层消耗自己的距离，onNestedPreScroll逐层消耗后，再onNestedScroll由上向下通知已消耗的距离做剩余的处理。由于NestedScrollingParent2没有onNestedScroll过程中各层消耗的距离，所以停止嵌套滚动的逻辑只能交由AppBarLayout进行控制。SRL不再在这种场景下控制停止嵌套滚动。

**Comment by dnwalter** [comment]
非常感谢git主，我会照着你的源码再理解一下的了
