### ISSUE TITLE
为什么二级刷新和一级刷新的完成回调是同一个？如何判断是一级刷新完成还是二级刷新完成？谢谢！这是个很好的项目。

### ISSUE THREAD

**Issue by zqisheng** [dkzwm/SmoothRefreshLayout#90]
我二级调用刷新完成也是会调用一级刷新的完成，是否有状态变量判断是一级刷新还是二级刷新完成？

**Comment by dkzwm** [comment]
@ailuoyang 老版本吗，新版本已经去掉了刷新完成的回调，请提供你使用的版本信息，我好回看下代码实现，寻找解决办法。
原来考虑刷新完成的监听主要目的是用来做加载完成添加数据用，后面发现这样实现不能完整覆盖到所有添加数据的场景，就改用内部状态改变监听来替代，继而删除了刷新完成的监听接口。
主要是没有考虑到会有这种场景，调用刷新完成都是主动调用，所以调用者应该可以通过调用刷新完成方法前通过调用`isRefreshing/isTwoLevelRefreshing`方法得知是一级刷新还是二级刷新的。当然如果需要在回调中得知在新版本可以这么实现
```
        mRefreshLayout.addOnStatusChangedListener(new SmoothRefreshLayout.OnStatusChangedListener() {
            boolean isLastTwoLevelRefreshing = false;

            @Override
            public void onStatusChanged(byte old, byte now) {
                if (now == SmoothRefreshLayout.SR_STATUS_REFRESHING) {
                    isLastTwoLevelRefreshing = mRefreshLayout.isTwoLevelRefreshing();
                    return;
                }
                if (now == SmoothRefreshLayout.SR_STATUS_COMPLETE) {
                    if (isLastTwoLevelRefreshing) {
                        //上次是二级刷新完成
                    }
                }
                isLastTwoLevelRefreshing = false;
            }
        });
```

**Comment by zqisheng** [comment]
好的，问题已经解决了，我用的是6.5的版本，不过6.5的两个刷新调用的确实是同一个回调，这个回调函数是在IRefreshView接口中，谢谢了

**Comment by zqisheng** [comment]
而且，我发现你的代码中header刷新和footer刷新完成回调用的同一个回调，没有测试过，从代码看应该调用的是同一个回调

**Comment by dkzwm** [comment]
是同一个回调方法，因为Header和Footer都是继承自IRefreshView，而且Header和Footer本质上是一样的功能逻辑，只是一个在顶部一个在底部

**Comment by zqisheng** [comment]
请问二级刷新菜单怎么自动打开，我好像没有发现类似的api，只有自动触发到二级菜单提示位置？如果没有相关的api，希望作者下一个版本更新一下，还有如果自动刷新能有动画就好了，自动下拉的时候有些生硬 😁

**Comment by zqisheng** [comment]
还有，我在二级菜单头部view添加frament时，二级刷新结束后，fragment里面的view为什么会自动变为null，但是打开二级菜单后view又恢复了，是不是关闭二级菜单的时候内部有什么优化操作？还有有的时候二级菜单和一级菜单的headerview会莫名其妙无法显示，这种情况是出现在recyclerview拖动item结束后出现的，为了解决这个问题我只能在每次滑动结束的时候重新把之前的hraderview设置进去

**Comment by dkzwm** [comment]
@ailuoyang 
1.关于自动触发二级刷新的问题，这边没有看到过有这样需求的App，类似淘宝、京东都是手动触发打开，所以就没有做这个功能，实现没问题，可以在下个版本加入。
2.关于自动刷新动画，触发自动刷新的逻辑可能会由于主线程阻塞导致动画丢帧直接跳到最后一帧，如果你触发前主线程有耗时操作请手动延迟一定时间触发,且`autoRefresh(int action, boolean smoothScroll)`中的`smoothScroll`参数必须配置`true`。
3.关于View变`null`问题，可以肯定不是由SRL引起的，SRL内部只在`setHeaderView`和`setFooterView`
2个地方有对Header和Footer移除操作，不主动调用这2个方法是SRL是不会有移除操作的，自然不会由SRL导致View变`null`，怀疑是Fragment的添加移除操作存在问题、或者系统自动回收而创建代码写在了错误的位置导致系统重建Views时没有重建到。

**Comment by zqisheng** [comment]
@dkzwm 好的，期待下一个版本，主要是我这个有些功能在二楼显示，用户点击一些图标会自动进入二楼显示

**Comment by dkzwm** [comment]
@ailuoyang  你更新下`1.6.6.7`版本，添加了自动二级刷新功能。

**Comment by zqisheng** [comment]
@dkzwm 好的，谢谢，用上了:smile:
