### ISSUE TITLE
HorizontalSmoothRefreshLayout横向滑动

### ISSUE THREAD

**Issue by zhangyunpenggithub** [dkzwm/SmoothRefreshLayout#94]
不知道是不是用法不对，横向滑动完成后footer有的时候会缩回去，然后整个recyclerview向右移动，后面已经加载出来数据了，这样给人一种后面没有数据了的感觉

**Comment by dkzwm** [comment]
@zhangyunpenggithub  遇到这种情况一般情况下是Adapter设置数据后由于数据量大或者视图较复杂，View计算时间稍长，在Adapter设置数据后立马结束刷新可能导致视图没有完成计算布局，RecyclerView尾部视图仍未添加，此时RecyclerView正处于最底部自然就会缩回去，你可以尝试延迟refreshComplete(delay)，delay时长你可以按照经验设置，一般情况下几百毫秒就已足够

**Comment by zhangyunpenggithub** [comment]
非常感谢您能这么快回复，我刚刚看了一下，找到能稳定重现的原因了，当我分页加载，一页加载20个的时候，加入总数据有45条，第一次是正常的，当最后一页不足一页的时候就会出现上述的情况。稳定重现

**Comment by dkzwm** [comment]
@zhangyunpenggithub 好的，你可以调试确定是哪里的问题，如果是本库的Bug，这边后面后尝试修复，期待你的反馈！

**Comment by zhangyunpenggithub** [comment]
> 非常感谢您能这么快回复，我刚刚看了一下，找到能稳定重现的原因了，当我分页加载，一页加载20个的时候，加入总数据有45条，第一次是正常的，当最后一页不足一页的时候就会出现上述的情况。稳定重现



> @zhangyunpenggithub 遇到这种情况一般情况下是Adapter设置数据后由于数据量大或者视图较复杂，View计算时间稍长，在Adapter设置数据后立马结束刷新可能导致视图没有完成计算布局，RecyclerView尾部视图仍未添加，此时RecyclerView正处于最底部自然就会缩回去，你可以尝试延迟refreshComplete(delay)，delay时长你可以按照经验设置，一般情况下几百毫秒就已足够

我试过了不是这个原因，就是第二页不足一页的时候，缩回去指的是footer已经显示了，但是加载完下一页的数据，我隐藏footerview后recyclerview整体右移

**Comment by zhangyunpenggithub** [comment]
> @zhangyunpenggithub 好的，你可以调试确定是哪里的问题，如果是本库的Bug，这边后面后尝试修复，期待你的反馈！
下一页数据加载完后动画是在哪里执行的呢

**Comment by dkzwm** [comment]
你能贴下GIF吗，这边我有点相像不出是什么样的场景

**Comment by dkzwm** [comment]
你可以调用setOnLoadMoreScrollCallback，在onScroll回调中查看滚动动画每次移动的距离，本库是使用ScrollCompat.scrollCompat()方法进行的同步向上移动同等距离已达到显示追加数据View的效果

**Comment by zhangyunpenggithub** [comment]
category_channel_refresh_layout.refreshComplete()
   mChannelListAdapter?.refreshData(it, mMainModel.needclean)
   Tasks.postDelayed2UI(Runnable {
   category_channel_refresh_layout.setDisableLoadMore(it.size < BaseRepository.PAGE_SIZE)
            }, 500)

我发现我不调用setDisableLoadMore就没有问题，我尝试延迟调用setDisableLoadMore也没问题，只有当这样调用的时候切翻页处于最后一页的时候就会出现问题

   category_channel_refresh_layout.refreshComplete()
   mChannelListAdapter?.refreshData(it, mMainModel.needclean)
   category_channel_refresh_layout.setDisableLoadMore(it.size < BaseRepository.PAGE_SIZE)

**Comment by dkzwm** [comment]
可参照WithListViewActivity.java实现，禁用应该在回滚动画完成后

**Comment by dkzwm** [comment]
你可以设置setEnableSmoothRollbackWhenCompleted，这样刷新完成动画不会被触摸事件打断，然后在状态监听的回调方法里判断是否回到初始状态，在初始状态下再关闭footer

**Comment by zhangyunpenggithub** [comment]
> WithListViewActiv没找到你说的监听回到初始状态啊

**Comment by dkzwm** [comment]
OnStatusChangedListener中onStatusChanged中now为SR_STATUS_INIT就是初始状态，你可以记录下本次操作是刷新还是加载用来关闭Footer
