### ISSUE TITLE
有滑动到顶部或者底部 直接触发回调的功能吗? 不是按住屏幕拖动后触发，而是直接触发

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#96]
refreshLayout.setDisablePerformRefresh(false);
refreshLayout。setEnablePullToRefresh(true);
这些方法都测试下，都不是我说的效果

**Comment by dahai2070** [comment]
autoRefush（） 也不是

**Comment by dkzwm** [comment]
```java
setEnableAutoRefresh(true);//滚动到接近顶部或者顶部即自动触发刷新
setEnableAutoLoadMore(true);//滚动到接近底部或者底部即自动触发加载
```

**Comment by dahai2070** [comment]
感谢  ，马上试试

**Comment by dahai2070** [comment]
发现显示的header 遮住了recyclerView 的顶部，而不是像拖动刷新的效果，recyclerView 被header 往下顶开了，这个有现成的方法能实现吗？其实我下拉刷新的回调也是加载更多的本地消息，类型微信一样。

**Comment by dkzwm** [comment]
么有，可能使用material样式Header会好点，理论上这种应该通过使用RecyclerView的`OnScrollListener`来进行实现

**Comment by dahai2070** [comment]
我就是用的MaterialSmoothRefreshLayout，
我 尝试了用recyclerView 的监听，自己去判断，是否滑动到了顶部或者底部，也实现了上啦 下拉加载更多，但是没有header 和footer的效果了，我就想怎么把MaterialSmoothRefreshLayout 里面的header 和footer 利用起来。

![图片](https://user-images.githubusercontent.com/20382707/64237290-a37f8780-cf2e-11e9-8b48-8179a8f444cd.png)

**Comment by dkzwm** [comment]
你是想像官方的SwipeRefreshLayout一样，Header漂浮在RecyclerView上，还是说像普通刷新，直接跟随RecyclerView，下拉的时候刷新视图将RecyclerView下移？

**Comment by dahai2070** [comment]
我想实现 “
普通刷新，直接跟随RecyclerView，下拉的时候刷新视图将RecyclerView下移
”

**Comment by dkzwm** [comment]
普通刷新样式的话不能调用`materialStyle`方法,该方法会配置`setEnablePinContentView`和`setEnablePinRefreshViewWhileLoading`会将Header悬浮在RecyclerView上

**Comment by dahai2070** [comment]
意思 直接使用 SmoothRefreshLayout 就能实现吗？我试试

**Comment by dahai2070** [comment]
我一直使用的是  MaterialSmoothRefreshLayout

**Comment by dkzwm** [comment]
没有调用
```java
refreshLayout.setEnablePinContentView(true);
refreshLayout.setEnableKeepRefreshView(true);
refreshLayout.setEnablePinRefreshViewWhileLoading(true);
```
那么Header就是跟随RecyclerView的，你可以检查下配置

**Comment by dahai2070** [comment]
直接使用 SmoothRefreshLayout ，不调用  以下三个方法，header 就是跟随 RecyclerView，是这样意思吗？
refreshLayout.setEnablePinContentView(true);
refreshLayout.setEnableKeepRefreshView(true);
refreshLayout.setEnablePinRefreshViewWhileLoading(true);

**Comment by dahai2070** [comment]
另外 直接使用SmoothRefreshLayout ，是不是得配置 header 和 footer ?忘记了，，一直都是用的 MaterialSmoothRefreshLayout 了

**Comment by dkzwm** [comment]
l MaterialSmoothRefreshLayout默认也就是添加了Header和Footer，只需要配置
```java
refreshLayout.setDisableLoadMore(false);//开启Footer
refreshLayout.setEnableAutoRefresh(true);//滚动到接近顶部或者顶部即自动触发刷新
refreshLayout.setEnableAutoLoadMore(true);//滚动到接近底部或者底部即自动触发加载
refreshLayout.setOnRefreshListener(new SmoothRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefreshing() {
                
            }

            @Override
            public void onLoadingMore() {

            }
        });
```

**Comment by dahai2070** [comment]
header 仍然是覆盖在 recyclerView 之上，没有跟随的效果 ，下面是我的代码

import me.dkzwm.widget.srl.MaterialSmoothRefreshLayout;
import me.dkzwm.widget.srl.SmoothRefreshLayout;

public class MyRefreshLayout extends SmoothRefreshLayout {
    public MyRefreshLayout(Context context) {
        super(context);
    }

    public MyRefreshLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyRefreshLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }


    @Override
    protected void moveHeaderPos(float delta) {
        super.moveHeaderPos(delta);

        //移动 recyclerView
        if (mScrollTargetView != null) compatLoadMoreScroll(mScrollTargetView, delta);
        if (mAutoFoundScrollTargetView != null) {
            compatLoadMoreScroll(mAutoFoundScrollTargetView, delta);
        } else if (mTargetView != null) compatLoadMoreScroll(mTargetView, delta);

    }

    @Override
    protected void init(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super.init(context, attrs, defStyleAttr, defStyleRes);

        ChatMessageLoadHeader header = new ChatMessageLoadHeader(context);
        setHeaderView(header);
        ChatMessageLoadFooter footer = new ChatMessageLoadFooter(context);
        setFooterView(footer);

    }
}

**Comment by dahai2070** [comment]
![图片](https://user-images.githubusercontent.com/20382707/64241565-95356980-cf36-11e9-9ff8-cb6627f611ae.png)

配置的代码

**Comment by dkzwm** [comment]
你可以clone下`issue96`分支，查看下`WithRecyclerViewActivity`，看下是否是你说的效果

**Comment by dahai2070** [comment]
嗯，非常感谢你。

**Comment by dahai2070** [comment]
我很好奇，你是自己在创业吗，貌似你时间比较自由。

**Comment by dkzwm** [comment]
上班摸鱼
这边你Pull一下，有个小问题需要重写修复，你可以直接拷贝`SyncScrollingRefreshLayout`到项目使用

**Comment by dahai2070** [comment]
效果确实是这个效果，我也看到了 SyncScrollingRefreshLayout，配置我也是和WithRecyclerViewActivity 里面的配置一样啊，但是我的却是 覆盖的效果，哈哈，奇怪，，我直接复制你的试试。

**Comment by dahai2070** [comment]
你是哪儿人哦？我是重庆的，你呢

**Comment by dahai2070** [comment]
![图片](https://user-images.githubusercontent.com/20382707/64246438-5eb01c80-cf3f-11e9-915c-8f766829fe4f.png)
我远程依赖的，没法访问，这两个包级访问权限，可以不调用吗

**Comment by dkzwm** [comment]
我成都工作达州人
你自己新建个`me.dkzwm.widget.srl`包放进去呗

**Comment by dahai2070** [comment]
这些操作很牛逼啊，压根没想到，你做开发多少年了啊?

**Comment by dahai2070** [comment]
进入页面就会自动回调一次，这个可以取消吗？

**Comment by dahai2070** [comment]
没用现成的方法的话，就不麻烦你了

**Comment by dahai2070** [comment]
找到方法了  ，注释掉一下代码，就不会进入页面后直接刷新回调？
// refreshLayout.autoRefresh(false);
