### ISSUE TITLE
Horizontal Pull to Refresh

### ISSUE THREAD

**Issue by nyavuzcan** [dkzwm/SmoothRefreshLayout#97]
Hi. I try to do horizontal pull but i didn't do this. I am beginner programmer if you can explain with details ı will be happy. Thank you.

**Comment by nyavuzcan** [comment]
And can I DO THIS WITH ARROW ?

**Comment by dkzwm** [comment]
First at all，you must depends the following two libs
```java
    implementation 'me.dkzwm.widget.srl:core:1.6.6.8'
    implementation 'me.dkzwm.widget.srl:ext-horizontal:1.6.6.8'
```
  Only then can you use horizontal pull to refresh.

**Comment by nyavuzcan** [comment]
Ok thanks but latwr what will i do.

**Comment by nyavuzcan** [comment]
For example how can i write xml

**Comment by nyavuzcan** [comment]
I couldn't do this I want to left begin to end arrow horizantal pull to refresh. Always done vertical why ? how can i customize

**Comment by nyavuzcan** [comment]
Hey thank it ok. But I want to straight arrow like vertical pull. Can I do this ?

**Comment by dkzwm** [comment]
You can clone the  `app`, see the `TestHorizontalRefreshActivity` .
Then you will know how to do.
