### ISSUE TITLE
求助，我自定义了一个view，需要消费上下滑动事件，放在

### ISSUE THREAD

**Issue by dahai2070** [dkzwm/SmoothRefreshLayout#98]
<me.dkzwm.widget.srl.MaterialSmoothRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="50dp">

        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">
                  ......
                    <com.srwl.mytx.widget.TimeSelectorView
                        android:id="@+id/time_selector"
                        android:layout_width="match_parent"
                        android:layout_height="130dp"
                        android:layout_marginTop="5dp"
                        android:layout_marginBottom="5dp"/>

                  ......

            </LinearLayout>
        </ScrollView>
    </me.dkzwm.widget.srl.MaterialSmoothRefreshLayout>

我的布局是这样的，当我禁用MaterialSmoothRefreshLayout的上拉和下拉的时候，一切正常，但是我又需要使用 MaterialSmoothRefreshLayout的刷新和加载更多，
我猜是我这个自定义View 的事件分发写的有问题，能指点下吗，感谢，
下面是自定义View 事件分发的代码 
===========================================================

    @Override
    public boolean dispatchTouchEvent(MotionEvent event) {

        switch (event.getAction()) {

            case MotionEvent.ACTION_DOWN:
                Log.d(TAG, "dispatchTouchEvent: 按下了，，，，，");
                float downX = event.getX();
                float downY = event.getY();

                int downPosition = getCoordinateToPosition(downX, downY / childerHeight < 1);

                //如果按下的区域不是“上午”“下午”
                if (downPosition >= 0) {
                    checkToJoinList(downPosition);
                }

                break;
            case MotionEvent.ACTION_MOVE:
                Log.e(TAG, "dispatchTouchEvent: 移动了，，，，");
                float moveX = event.getX();
                float moveY = event.getY();

                int nowPosition = getCoordinateToPosition(moveX, moveY / childerHeight < 1);

                //如果当前滑动到view之外或上午、下午区域，则拦截
//                if (moveX < 0 || moveY < 0 || moveX > width || moveY > height || nowPosition < 0) {
//                    return false;
//                }
                if (nowPosition >= 0 && nowPosition != lastTouchPosition) {
                    checkToJoinList(nowPosition);
                }

                break;
            case MotionEvent.ACTION_UP:
                Log.d(TAG, "dispatchTouchEvent: 抬起了，，，，");
                lastTouchPosition = NONE;
                break;
        }
        //无论如何都返回 true ,
        return true;
    }
=======================================================
在 dispatchTouchEvent() 方法里面，我一直返回true,表示自己需要消费掉 各种事件，但是 滑动事件仍然会被拦截一部分，只有一开始滑动的时候，会进入，滑动距离长一点，就被拦截了。

**Comment by dkzwm** [comment]
这边不是很懂你的意思，大概是你自定义了一个视图，需要在一定条件下支撑消耗滑动事件？
理论上自定下边界判断逻辑应该能帮助到你，考虑到你的自定义视图是在SRL内部的，所以如果没有设置边界判断逻辑，默认触摸事件肯定是到SRL层就会被消费掉
`OnHeaderEdgeDetectCallBack.isNotYetInEdgeCannotMoveHeader`
`OnFooterEdgeDetectCallBack.isNotYetInEdgeCannotMoveFooter`
这2个方法配合`ACTION_DOWN `记录的按下位置应该可以进行控制。
简单来讲即`ACTION_DOWN `时记录位置，并将你的自定义视图理解为一个`ListView`来操作，此时列表是处于顶部还是处于底部。

**Comment by dahai2070** [comment]
我的这个自定义view 并不是要真的滑动，继承于View,当手指滑动的时候，能根据滑动的位置，修改view 里面小方格的背景色，给人以选中的效果。

**Comment by dahai2070** [comment]
我就想当在这个自定义View 上下滑动的时候，自己消费掉滑动事件，而不是父布局去消费。我在dispatchTouchEvent（） 中返回true 了，滑动事件仍然是被拦截的，我的对dispatchTouchEvent（）的理解是，当返回true 的时候，就是告诉父布局，我要消费这个事件，我这样理解有误吗

**Comment by dkzwm** [comment]
分发是由上而下的。刷新视图复写`dispatchTouchEvent`方法必然会在刷新视图层就拦截，由刷新视图来根据视图状态选择是否向下传递，你这样的需求可以配置`setEnableOldTouchHandling(false)`,然后在你的自定义View中的`dispatchTouchEvent`方法中获取父级即SRL里的`IIndicator`，拿到原始偏移量，再加上按下的坐标，即是`ACTION_MOVE `的真实坐标。

**Comment by dkzwm** [comment]
类似这样操作
```
public class TestViewGroup extends FrameLayout {
    protected int mTouchPointerId;
    private SmoothRefreshLayout mRefreshLayout;
    private float[] mLastPoint = new float[2];

    public TestViewGroup(@NonNull Context context) {
        super(context);
    }

    public TestViewGroup(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public TestViewGroup(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        View view = this;
        while (view.getParent() != null && view.getParent() instanceof View) {
            if (view.getParent() instanceof SmoothRefreshLayout) {
                mRefreshLayout = (SmoothRefreshLayout) view.getParent();
                mRefreshLayout.setEnableOldTouchHandling(false);
                break;
            }
            view = (View) view.getParent();
        }
    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        mRefreshLayout = null;
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        switch (ev.getActionMasked()) {
            case MotionEvent.ACTION_DOWN:
                mLastPoint[0] = ev.getX();
                mLastPoint[1] = ev.getY();
                mTouchPointerId = ev.getPointerId(0);
                break;
            case MotionEvent.ACTION_MOVE:
                IIndicator indicator = mRefreshLayout.getIndicator();
                float[] offset = indicator.getRawOffsets();
                mLastPoint[0] += offset[0];
                mLastPoint[1] += offset[1];
                //mLastPoint是就是当前MotionEvent在SRL层的原始x,y坐标
                break;
            case MotionEvent.ACTION_POINTER_UP:
                final int pointerIndex =
                        (ev.getAction() & MotionEvent.ACTION_POINTER_INDEX_MASK)
                                >> MotionEvent.ACTION_POINTER_INDEX_SHIFT;
                if (ev.getPointerId(pointerIndex) == mTouchPointerId) {
                    // Pick a new pointer to pick up the slack.
                    final int newIndex = pointerIndex == 0 ? 1 : 0;
                    mTouchPointerId = ev.getPointerId(newIndex);
                    mLastPoint[0] = ev.getX(newIndex);
                    mLastPoint[1] = ev.getY(newIndex);
                }
                break;
            case MotionEvent.ACTION_POINTER_DOWN:
                mTouchPointerId = ev.getPointerId(ev.getActionIndex());
                mLastPoint[0] = ev.getX(ev.getActionIndex());
                mLastPoint[1] = ev.getY(ev.getActionIndex());
                break;

        }
        return true;
    }
}
```

**Comment by dahai2070** [comment]
获得 这个东西IIndicator ，就可以了吗，空了试试。
刚才我用了一个很傻的方式解决了问题，在自定义View 里面的dispatchTouchEvent（）方法中，当出现滑动（ACTION_MOVE），我就回调出去，禁用掉SRL 的下拉和上拉功能，当滑动结束（ACTION_UP），，，

![图片](https://user-images.githubusercontent.com/20382707/65813010-af92f800-e201-11e9-8d76-2d2080ff95f4.png)
![图片](https://user-images.githubusercontent.com/20382707/65813020-c2a5c800-e201-11e9-892d-629451f7419e.png)
